import { defineStrings } from '../../../kernel/i18n';

/**
 * The sheet's own sentences (Phase C: the one-editor grid, the WPS ribbon, the filter arrows,
 * the phone bar), in Arabic and English. Registered under `office.` like the rest of the window,
 * so `t('office.…')` reads them; the two key sets are identical.
 */
defineStrings('office', {
  ar: {
    sheetGrid: 'خلايا الورقة',
    defaultSheetName: 'ورقة{n}',
    // ribbon
    tabFormulas: 'صيغ',
    groupClipboard: 'الحافظة',
    paste: 'لصق',
    cut: 'قص',
    copy: 'نسخ',
    formatPainter: 'نسخ التنسيق',
    painterHint: 'اختر الخلايا التي تأخذ التنسيق.',
    pasteBlocked: 'المتصفح لم يسمح بقراءة الحافظة. استخدم Ctrl+V.',
    mergeCenter: 'دمج وتوسيط',
    mergeCells: 'دمج الخلايا',
    unmerge: 'إلغاء الدمج',
    mergeKeepsFirst: 'الدمج يُبقي قيمة الخلية الأولى فقط، وتُمسح البقية.',
    condFormatting: 'تنسيق شرطي',
    cellStyles: 'أنماط الخلايا',
    cellStyle_normal: 'عادي',
    cellStyle_good: 'جيد',
    cellStyle_bad: 'سيئ',
    cellStyle_neutral: 'محايد',
    cellStyle_heading: 'عنوان',
    cellStyle_title: 'عنوان رئيسي',
    cellStyle_total: 'إجمالي',
    cellStyle_input: 'إدخال',
    cellStyle_note: 'ملاحظة',
    cellStyle_accent: 'تمييز',
    autoFunctions: 'دوال سريعة',
    autoCount: 'عدّ الأرقام',
    autoMax: 'الأكبر',
    autoMin: 'الأصغر',
    sortFilter: 'فرز وتصفية',
    sortAscShort: 'فرز تصاعدي',
    sortDescShort: 'فرز تنازلي',
    sortCustom: 'فرز مخصّص…',
    filterToggle: 'تصفية',
    findReplace: 'بحث واستبدال',
    groupSheetTables: 'الجداول',
    chartRemoveAll: 'احذف كل المخططات',
    groupLinks: 'الروابط',
    insertLink: 'رابط',
    groupFunctions: 'الدوال',
    insertFunction: 'إدراج دالة',
    groupFunctionLibrary: 'مكتبة الدوال',
    fnCat_math: 'رياضيات',
    fnCat_statistical: 'إحصاء',
    fnCat_logical: 'منطقية',
    fnCat_text: 'نص',
    fnCat_date: 'تاريخ ووقت',
    fnCat_lookup: 'بحث ومرجع',
    fnCat_financial: 'مالية',
    fnCat_info: 'معلومات',
    fnCat_more: 'المزيد',
    fnCat_all: 'كل الدوال',
    groupDataTools: 'أدوات البيانات',
    removeDuplicates: 'إزالة التكرار',
    groupWindow: 'النافذة',
    freezeMenu: 'تجميد الأجزاء',
    freezePanes: 'تجميد عند الخلية المحددة',
    freezeFirstCol: 'تجميد العمود الأول',
    unfreeze: 'إلغاء التجميد',
    gridlines: 'خطوط الشبكة',
    // insert function dialog
    fnSearch: 'ابحث عن دالة',
    fnCategory: 'الفئة',
    fnPick: 'اختر دالة',
    fnInsert: 'إدراج',
    fnNoHelp: 'اكتب قيمها بين القوسين وافصل بينها بفاصلة.',
    fnNone: 'لا توجد دالة بهذا الاسم.',
    fnHelp_SUM: 'مجموع الأرقام في النطاق.',
    fnHelp_AVERAGE: 'متوسط الأرقام في النطاق.',
    fnHelp_COUNT: 'عدد الخلايا التي فيها أرقام.',
    fnHelp_COUNTA: 'عدد الخلايا غير الفارغة.',
    fnHelp_MAX: 'أكبر رقم في النطاق.',
    fnHelp_MIN: 'أصغر رقم في النطاق.',
    fnHelp_IF: 'قيمة إذا تحقق الشرط، وأخرى إن لم يتحقق.',
    fnHelp_IFERROR: 'قيمة بديلة إذا كان الناتج خطأ.',
    fnHelp_AND: 'صحيح إذا تحققت كل الشروط.',
    fnHelp_OR: 'صحيح إذا تحقق أي شرط.',
    fnHelp_SUMIF: 'مجموع الخلايا التي تطابق شرطًا.',
    fnHelp_COUNTIF: 'عدد الخلايا التي تطابق شرطًا.',
    fnHelp_VLOOKUP: 'يبحث عن قيمة في العمود الأول ويعيد ما يقابلها.',
    fnHelp_XLOOKUP: 'يبحث عن قيمة في نطاق ويعيد ما يقابلها من نطاق آخر.',
    fnHelp_INDEX: 'القيمة في صف وعمود محددين من النطاق.',
    fnHelp_MATCH: 'موضع القيمة داخل النطاق.',
    fnHelp_ROUND: 'تقريب الرقم إلى عدد الخانات المطلوب.',
    fnHelp_TODAY: 'تاريخ اليوم.',
    fnHelp_NOW: 'التاريخ والوقت الآن.',
    fnHelp_DATE: 'تاريخ من السنة والشهر واليوم.',
    fnHelp_CONCAT: 'يجمع النصوص في نص واحد.',
    fnHelp_LEFT: 'الحروف الأولى من النص.',
    fnHelp_RIGHT: 'الحروف الأخيرة من النص.',
    fnHelp_LEN: 'عدد حروف النص.',
    fnHelp_TRIM: 'يحذف المسافات الزائدة.',
    fnHelp_TEXT: 'رقم مكتوب بتنسيق تختاره.',
    fnHelp_PMT: 'القسط الدوري لقرض.',
    fnHelp_HYPERLINK: 'رابط يُفتح بضغطة Ctrl على الخلية.',
    // link dialog
    linkTitle: 'إدراج رابط',
    linkAddress: 'العنوان',
    linkText: 'النص الظاهر',
    linkInvalid: 'اكتب عنوانًا يبدأ بـ https:// أو mailto:',
    linkOpenHint: 'Ctrl + نقرة لفتح الرابط',
    // find
    findWhat: 'ابحث عن',
    matchCase: 'مطابقة حالة الأحرف',
    wholeCell: 'مطابقة الخلية كاملة',
    findNone: 'لا نتائج.',
    findFound: 'وُجد في {cell}',
    // remove duplicates
    dedupeTitle: 'إزالة التكرار',
    dedupeColumns: 'الأعمدة التي تُقارَن',
    dedupeHeader: 'الصف الأول عناوين',
    dedupeApply: 'إزالة',
    dedupeDone: 'حُذف {n} صف مكرر.',
    dedupeNone: 'لا توجد صفوف مكررة.',
    dedupeFormulas: 'في النطاق صيغ، فلا تُزال الصفوف تلقائيًا. انسخ القيم أولًا.',
    // honest notes in the panels (plain words)
    chartSavedNote: 'يُحفظ المخطط مع الملف.',
    condSavedNote: 'يُحفظ التنسيق الشرطي مع الملف.',
    filterSavedNote: 'تُحفظ التصفية مع الملف.',
    chartFromRange: 'البيانات: {range}',
  },
  en: {
    sheetGrid: 'Sheet cells',
    defaultSheetName: 'Sheet{n}',
    tabFormulas: 'Formulas',
    groupClipboard: 'Clipboard',
    paste: 'Paste',
    cut: 'Cut',
    copy: 'Copy',
    formatPainter: 'Format painter',
    painterHint: 'Choose the cells that take the format.',
    pasteBlocked: 'The browser did not allow reading the clipboard. Use Ctrl+V.',
    mergeCenter: 'Merge & center',
    mergeCells: 'Merge cells',
    unmerge: 'Unmerge',
    mergeKeepsFirst: 'Merging keeps only the first cell’s value; the others are cleared.',
    condFormatting: 'Conditional formatting',
    cellStyles: 'Cell styles',
    cellStyle_normal: 'Normal',
    cellStyle_good: 'Good',
    cellStyle_bad: 'Bad',
    cellStyle_neutral: 'Neutral',
    cellStyle_heading: 'Heading',
    cellStyle_title: 'Title',
    cellStyle_total: 'Total',
    cellStyle_input: 'Input',
    cellStyle_note: 'Note',
    cellStyle_accent: 'Accent',
    autoFunctions: 'Quick functions',
    autoCount: 'Count numbers',
    autoMax: 'Max',
    autoMin: 'Min',
    sortFilter: 'Sort & filter',
    sortAscShort: 'Sort A to Z',
    sortDescShort: 'Sort Z to A',
    sortCustom: 'Custom sort…',
    filterToggle: 'Filter',
    findReplace: 'Find & replace',
    groupSheetTables: 'Tables',
    chartRemoveAll: 'Remove all charts',
    groupLinks: 'Links',
    insertLink: 'Link',
    groupFunctions: 'Functions',
    insertFunction: 'Insert function',
    groupFunctionLibrary: 'Function library',
    fnCat_math: 'Math',
    fnCat_statistical: 'Statistical',
    fnCat_logical: 'Logical',
    fnCat_text: 'Text',
    fnCat_date: 'Date & time',
    fnCat_lookup: 'Lookup & reference',
    fnCat_financial: 'Financial',
    fnCat_info: 'Information',
    fnCat_more: 'More',
    fnCat_all: 'All functions',
    groupDataTools: 'Data tools',
    removeDuplicates: 'Remove duplicates',
    groupWindow: 'Window',
    freezeMenu: 'Freeze panes',
    freezePanes: 'Freeze at the selected cell',
    freezeFirstCol: 'Freeze first column',
    unfreeze: 'Unfreeze',
    gridlines: 'Gridlines',
    fnSearch: 'Search for a function',
    fnCategory: 'Category',
    fnPick: 'Choose a function',
    fnInsert: 'Insert',
    fnNoHelp: 'Type its values between the brackets, separated by commas.',
    fnNone: 'No function by that name.',
    fnHelp_SUM: 'Adds the numbers in a range.',
    fnHelp_AVERAGE: 'The average of the numbers in a range.',
    fnHelp_COUNT: 'How many cells hold numbers.',
    fnHelp_COUNTA: 'How many cells are not empty.',
    fnHelp_MAX: 'The largest number in a range.',
    fnHelp_MIN: 'The smallest number in a range.',
    fnHelp_IF: 'One value when a condition is true, another when it is not.',
    fnHelp_IFERROR: 'A fallback value when the result is an error.',
    fnHelp_AND: 'True when every condition is true.',
    fnHelp_OR: 'True when any condition is true.',
    fnHelp_SUMIF: 'Adds the cells that meet a condition.',
    fnHelp_COUNTIF: 'Counts the cells that meet a condition.',
    fnHelp_VLOOKUP: 'Looks a value up in the first column and returns what is beside it.',
    fnHelp_XLOOKUP: 'Looks a value up in one range and returns the match from another.',
    fnHelp_INDEX: 'The value at a given row and column of a range.',
    fnHelp_MATCH: 'Where a value sits in a range.',
    fnHelp_ROUND: 'Rounds a number to the digits you ask for.',
    fnHelp_TODAY: 'Today’s date.',
    fnHelp_NOW: 'The date and time now.',
    fnHelp_DATE: 'A date from a year, month and day.',
    fnHelp_CONCAT: 'Joins texts into one.',
    fnHelp_LEFT: 'The first characters of a text.',
    fnHelp_RIGHT: 'The last characters of a text.',
    fnHelp_LEN: 'How many characters a text has.',
    fnHelp_TRIM: 'Removes extra spaces.',
    fnHelp_TEXT: 'A number written in a format you choose.',
    fnHelp_PMT: 'The regular payment of a loan.',
    fnHelp_HYPERLINK: 'A link, opened with Ctrl+click on the cell.',
    linkTitle: 'Insert link',
    linkAddress: 'Address',
    linkText: 'Text to show',
    linkInvalid: 'Type an address that starts with https:// or mailto:',
    linkOpenHint: 'Ctrl+click to open the link',
    findWhat: 'Find what',
    matchCase: 'Match case',
    wholeCell: 'Match the whole cell',
    findNone: 'No matches.',
    findFound: 'Found in {cell}',
    dedupeTitle: 'Remove duplicates',
    dedupeColumns: 'Columns to compare',
    dedupeHeader: 'The first row is headers',
    dedupeApply: 'Remove',
    dedupeDone: 'Removed {n} duplicate rows.',
    dedupeNone: 'No duplicate rows.',
    dedupeFormulas: 'The range holds formulas, so rows are not removed automatically. Copy the values first.',
    chartSavedNote: 'The chart is saved with the file.',
    condSavedNote: 'Conditional formatting is saved with the file.',
    filterSavedNote: 'The filter is saved with the file.',
    chartFromRange: 'Data: {range}',
  },
});
