import { defineStrings } from '../../kernel/i18n';

/**
 * Every visible string of the Photo Editor, Arabic and English with identical key sets.
 * `src/apps/web/strings.test.ts` compares the two tables key by key across the whole OS, so
 * a key added to one language only fails the suite — which is the point of centralising them
 * here instead of building sentences inline.
 *
 * The format names (PNG, JPEG, WebP, GIF, BMP, AVIF, SVG) are product names and stay the
 * same in both languages.
 */
defineStrings('photo', {
  ar: {
    title: 'محرّر الصور',
    openFile: 'فتح',
    openTitle: 'فتح صورة',
    openHint: 'المسار الكامل لصورة داخل المجلد الرئيسي',
    openPlaceholder: '/home/user/Pictures/photo.png',
    openAction: 'افتح',
    openCancel: 'إلغاء',
    loading: 'جارٍ فتح الصورة…',
    saveAsCopy: 'حفظ نسخة',
    overwrite: 'استبدال الأصل',
    exportTitle: 'تصدير',
    exportFormat: 'الصيغة',
    exportQuality: 'الجودة',
    exportTarget: 'المسار',
    exportHint: 'يُكتب داخل /home/user فقط.',
    exportConfirm: 'صدّر',
    exportDoneCopy: 'تم حفظ نسخة في {path}',
    exportDoneOverwrite: 'تم استبدال {path}، والنسخة الاحتياطية في {bak}',
    exportDoneOverwriteNoBak: 'تم استبدال {path} (أُنشئت نسخة احتياطية واحدة لأنها لم تكن موجودة)',
    exportFailed: 'تعذّر التصدير: {reason}',
    exportNoTarget: 'لا يوجد ملف أصلي لاستبداله — افتح ملفاً أولاً أو استخدم «حفظ نسخة».',
    exportTooBig: 'الملف الناتج أكبر من الحدّ الذي يقبله نظام الملفات (٢٠ ميجابايت). جرّب جودة أقل أو حجماً أصغر.',
    exportQuota: 'لا توجد مساحة كافية في نظام الملفات.',
    exportUnsupported: 'هذا المتصفح لا يستطيع ترميز {format}. اختر PNG أو JPEG.',

    undo: 'تراجع',
    redo: 'إعادة',
    reset: 'إرجاع الأصل',
    history: 'السجل',
    historyTitle: 'سجل التعديلات',
    historyTrimmed: 'أُسقط {count} خطوة قديمة لتوفير الذاكرة',
    historyMemory: 'السجل: {steps} خطوة ({size} من {budget} كحدّ أعلى)',
    historyPolicy:
      'السياسة: كل خطوة نسخة كاملة من الصورة (العرض×الارتفاع×٤ بايت)، ويُحتفظ بـ٢٠ خطوة على الأقل دائماً — حتى لو تجاوزت الميزانية — ثم يُسقط الأقدم عند {budget}. حدّ أقصى {steps} خطوة.',

    zoomIn: 'تكبير',
    zoomOut: 'تصغير',
    zoomFit: 'ملاءمة',
    zoomActual: '١٠٠٪',
    zoom: 'التقريب',

    toolsTitle: 'الأدوات',
    toolMove: 'تحريك',
    toolSelect: 'تحديد',
    toolCrop: 'قص',
    toolBrush: 'قلم',
    toolLine: 'خط',
    toolRect: 'مستطيل',
    toolEllipse: 'بيضاوي',
    toolArrow: 'سهم',
    toolText: 'نص',

    transformTitle: 'التحويل',
    rotateLeft: 'تدوير ٩٠° يساراً',
    rotateRight: 'تدوير ٩٠° يميناً',
    flipH: 'قلب أفقي',
    flipV: 'قلب رأسي',
    rotateFree: 'زاوية حرّة (درجات)',
    apply: 'تطبيق',
    cancel: 'إلغاء',

    cropTitle: 'القص',
    cropAspect: 'النسبة',
    cropFree: 'حرّة',
    cropApply: 'اقتطع',
    cropReset: 'إلغاء التحديد',
    cropHint: 'اسحب على الصورة لتحديد المستطيل، ثم «اقتطع».',
    cropInvalid: 'التحديد أصغر من بكسل واحد.',

    resizeTitle: 'تحجيم',
    resizeWidth: 'العرض',
    resizeHeight: 'الارتفاع',
    resizeLock: 'تثبيت النسبة',
    resizePercent: 'النسبة ٪',
    resizeApply: 'طبّق',
    resizeSame: 'الحجم نفسه — لا تغيير.',

    adjustTitle: 'تعديلات',
    adjBrightness: 'السطوع',
    adjContrast: 'التباين',
    adjSaturation: 'التشبّع',
    adjExposure: 'التعريض',
    adjTemperature: 'حرارة اللون',
    adjHighlights: 'الإضاءات',
    adjShadows: 'الظلال',
    adjResetAll: 'تصفير الكل',

    blurTitle: 'ضبابية',
    sharpenTitle: 'حِدّة',
    effectRadius: 'نصف القطر',
    effectAmount: 'المقدار',
    applyBlur: 'أضف ضبابية',
    applySharpen: 'أضف حِدّة',

    filtersTitle: 'فلاتر جاهزة',
    filterNone: 'بلا',
    filterMono: 'رمادي',
    filterSepia: 'سيبيا',
    filterVivid: 'زاهي',
    filterSoft: 'ناعم',
    filterPunch: 'حادّ',
    filterWarm: 'دافئ',
    filterCool: 'بارد',
    filterHint: 'الفلتر يضبط قيم التعديلات، ويمكن تعديلها بعده.',

    brushColor: 'اللون',
    brushSize: 'الحجم',
    shapeFill: 'تعبئة',
    textContent: 'النص',
    textPlaceholder: 'اكتب هنا',
    textSize: 'حجم الخط',
    textColor: 'لون النص',
    textHint: 'انقر على الصورة ثم اكتب — يُثبَّت النص عند الضغط على «أضف».',
    textAdd: 'أضف',
    textNeedsContent: 'اكتب نصاً أولاً.',

    selectHint: 'لتحديد جزء: اسحب داخل التحديد لنقله.',
    moveHint: 'أدوات الرسم تعمل على الصورة كاملة الآن.',

    fileTitle: 'الملف',
    sizeLabel: 'الحجم',
    colorspace: 'الفضاء اللوني',
    colorspaceRgb: 'RGB ٨ بت لكل قناة',

    capTitle: 'الصيغ المدعومة الآن',
    capOpens: 'فتح: {list}',
    capExports: 'تصدير: {list}',
    capProbe: 'الفحص جرى في هذا المتصفح عند فتح النافذة.',
    capUnsupported: 'غير مدعوم: {list}',
    capAnimFirst: 'الصورة المتحركة (GIF/WebP/APNG): تُفتح الأول فقط، والحفظ يُثبّت الإطار الأول — لا تحرير للحركة.',

    limitsTitle: 'حدود صريحة — ما لا يفعله هذا المحرّر',
    limitLayers: 'الطبقات تُحفظ كاملة فقط في ملف مشروع ‎.fphoto؛ التصدير إلى PNG أو JPEG أو WebP يدمجها في صورة واحدة. لا يُفتح ملف PSD.',
    limitCmyk: 'لا CMYK ولا إدارة ألوان ولا ملفات ICC.',
    limitRaw: 'لا RAW ولا HEIC/HEIF ولا TIFF ولا ICO.',
    limitAnim: 'لا تحرير للصور المتحركة (تُفتح الأولى فقط).',
    limitVector: 'لا تحرير متجهي لملفات SVG — تُحوَّل إلى نقاط عند الفتح.',
    limitText: 'طبقات النص تبقى قابلة للتحرير داخل المحرّر وفي ملف المشروع، وتُحوَّل إلى بكسلات عند التصدير فقط. الخطوط هي خطوط الجهاز، ولا يُنزَّل أي خط.',
    limitBrush: 'لا أقنعة طبقات ولا ملء ذكي ولا إزالة خلفية تلقائية.',
    limitQuota: 'الكتابة في نظام الملفات محدودة: ٢٠ ميجابايت للملف و٥٠ ميجابايت للمجموع.',
    limitColors: 'لا إدارة لكاميرا ولا بيانات EXIF عند الحفظ — الحفظ يعيد ترميز البكسلات فقط.',
    limitNoOriginal: 'فتح ملف لا يعدّله؛ لا يُكتب على القرص إلا عند الحفظ أو التصدير، واستبدال الأصل يحتفظ بنسخة ‎.bak واحدة.',
    limitClosing: 'التغييرات غير المحفوظة تُفقد عند إغلاق النافذة (يُسألك قبل الإغلاق).',

    discardTitle: 'تغييرات غير محفوظة',
    discardBody: 'لديك تغييرات لم تُحفظ. إغلاق النافذة يفقدها. أغلق على أي حال؟',

    errorTitle: 'تعذّر فتح الصورة',
    errorUnknown: 'خطأ غير معروف.',
    noImage: 'لا توجد صورة مفتوحة. استخدم «فتح» لاختيار صورة.',
    close: 'إغلاق',
  },
  en: {
    title: 'Photo Editor',
    openFile: 'Open',
    openTitle: 'Open an image',
    openHint: 'The full path of an image inside the home folder',
    openPlaceholder: '/home/user/Pictures/photo.png',
    openAction: 'Open',
    openCancel: 'Cancel',
    loading: 'Opening the image…',
    saveAsCopy: 'Save a copy',
    overwrite: 'Overwrite original',
    exportTitle: 'Export',
    exportFormat: 'Format',
    exportQuality: 'Quality',
    exportTarget: 'Path',
    exportHint: 'Writes inside /home/user only.',
    exportConfirm: 'Export',
    exportDoneCopy: 'Saved a copy to {path}',
    exportDoneOverwrite: 'Replaced {path}; the backup is at {bak}',
    exportDoneOverwriteNoBak: 'Replaced {path} (one backup was created, since none existed)',
    exportFailed: 'Export failed: {reason}',
    exportNoTarget: 'There is no original file to overwrite — open a file first, or use “Save a copy”.',
    exportTooBig: 'The result is larger than the file system accepts (20 MB). Try a lower quality or a smaller size.',
    exportQuota: 'The file system has no room left.',
    exportUnsupported: 'This browser cannot encode {format}. Choose PNG or JPEG.',

    undo: 'Undo',
    redo: 'Redo',
    reset: 'Revert to original',
    history: 'History',
    historyTitle: 'Edit history',
    historyTrimmed: '{count} older steps were dropped to save memory',
    historyMemory: 'History: {steps} steps ({size} of a {budget} ceiling)',
    historyPolicy:
      'Policy: each step is a full snapshot of the image (width×height×4 bytes); at least 20 steps are always kept — even past the budget — and the oldest are dropped above {budget}. Hard ceiling: {steps} steps.',

    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    zoomFit: 'Fit',
    zoomActual: '100%',
    zoom: 'Zoom',

    toolsTitle: 'Tools',
    toolMove: 'Move',
    toolSelect: 'Select',
    toolCrop: 'Crop',
    toolBrush: 'Brush',
    toolLine: 'Line',
    toolRect: 'Rectangle',
    toolEllipse: 'Ellipse',
    toolArrow: 'Arrow',
    toolText: 'Text',

    transformTitle: 'Transform',
    rotateLeft: 'Rotate 90° left',
    rotateRight: 'Rotate 90° right',
    flipH: 'Flip horizontally',
    flipV: 'Flip vertically',
    rotateFree: 'Free angle (degrees)',
    apply: 'Apply',
    cancel: 'Cancel',

    cropTitle: 'Crop',
    cropAspect: 'Aspect',
    cropFree: 'Free',
    cropApply: 'Crop',
    cropReset: 'Clear selection',
    cropHint: 'Drag on the image to mark the rectangle, then press “Crop”.',
    cropInvalid: 'The selection is smaller than one pixel.',

    resizeTitle: 'Resize',
    resizeWidth: 'Width',
    resizeHeight: 'Height',
    resizeLock: 'Lock aspect',
    resizePercent: 'Percent %',
    resizeApply: 'Apply',
    resizeSame: 'The size is unchanged — nothing to do.',

    adjustTitle: 'Adjustments',
    adjBrightness: 'Brightness',
    adjContrast: 'Contrast',
    adjSaturation: 'Saturation',
    adjExposure: 'Exposure',
    adjTemperature: 'Temperature',
    adjHighlights: 'Highlights',
    adjShadows: 'Shadows',
    adjResetAll: 'Reset all',

    blurTitle: 'Blur',
    sharpenTitle: 'Sharpen',
    effectRadius: 'Radius',
    effectAmount: 'Amount',
    applyBlur: 'Apply blur',
    applySharpen: 'Apply sharpen',

    filtersTitle: 'Filter presets',
    filterNone: 'None',
    filterMono: 'Grayscale',
    filterSepia: 'Sepia',
    filterVivid: 'Vivid',
    filterSoft: 'Soft',
    filterPunch: 'Punch',
    filterWarm: 'Warm',
    filterCool: 'Cool',
    filterHint: 'A preset sets the adjustment sliders; you can change them afterwards.',

    brushColor: 'Colour',
    brushSize: 'Size',
    shapeFill: 'Fill',
    textContent: 'Text',
    textPlaceholder: 'Type here',
    textSize: 'Font size',
    textColor: 'Text colour',
    textHint: 'Click the image, type, then press “Add” to burn the text in.',
    textAdd: 'Add',
    textNeedsContent: 'Type some text first.',

    selectHint: 'To select an area: drag inside the selection to move it.',
    moveHint: 'Drawing tools now work on the whole image.',

    fileTitle: 'File',
    sizeLabel: 'Size',
    colorspace: 'Colour space',
    colorspaceRgb: 'RGB, 8 bits per channel',

    capTitle: 'Formats supported right now',
    capOpens: 'Opens: {list}',
    capExports: 'Exports: {list}',
    capProbe: 'This check ran in this browser when the window opened.',
    capUnsupported: 'Not supported: {list}',
    capAnimFirst: 'Animated images (GIF/WebP/APNG): only the first frame is opened, and saving keeps that first frame — there is no animation editing.',

    limitsTitle: 'Honest limits — what this editor does not do',
    limitLayers: 'Layers are kept only in a .fphoto project; exporting to PNG, JPEG or WebP flattens them into one image. PSD files are not opened.',
    limitCmyk: 'No CMYK, no colour management, no ICC profiles.',
    limitRaw: 'No RAW, no HEIC/HEIF, no TIFF, no ICO.',
    limitAnim: 'No animation editing (only the first frame is opened).',
    limitVector: 'No vector editing of SVG files — they are rasterised on open.',
    limitText: 'Text layers stay editable in the editor and in the project file, and become pixels only on export. Fonts are the device’s own; nothing is downloaded.',
    limitBrush: 'No layer masks, no content-aware fill and no automatic background removal.',
    limitQuota: 'Writes are capped by the file system: 20 MB per file and 50 MB in total.',
    limitColors: 'No camera or EXIF metadata is written — saving re-encodes pixels only.',
    limitNoOriginal: 'Opening a file does not change it; nothing is written until you save or export, and replacing the original keeps exactly one .bak.',
    limitClosing: 'Unsaved changes are lost when the window closes (you are asked first).',

    discardTitle: 'Unsaved changes',
    discardBody: 'You have unsaved changes. Closing the window loses them. Close anyway?',

    errorTitle: 'Could not open the image',
    errorUnknown: 'Unknown error.',
    noImage: 'No image is open. Use “Open” to pick one.',
    close: 'Close',
  },
});

/*
 * The Image Studio strings (start screen, gallery, quick editor, layers, tools, selections,
 * project files, export). Same namespace, same parity rule: every key exists in both tables.
 */
defineStrings('photo', {
  ar: {
    appName: 'استوديو الصور',
    modeGallery: 'المعرض',
    modeQuick: 'تحرير سريع',
    modePro: 'احترافي',
    modeLabel: 'وضع العمل',
    menu: 'القائمة',
    untitled: 'بدون عنوان',
    unsavedMark: 'تغييرات غير محفوظة',
    savedMark: 'محفوظ',

    startTitle: 'استوديو الصور',
    startSubtitle: 'حرّر صورك بطبقات ونصوص عربية وفلاتر — كل شيء يبقى على جهازك.',
    startNew: 'لوحة جديدة',
    startNewHint: 'مربّع، قصة، HD، A4 أو مقاس مخصّص',
    startOpen: 'فتح من الملفات',
    startOpenHint: 'صورة أو مشروع ‎.fphoto من مجلدك',
    startDevice: 'فتح من الجهاز',
    startDeviceHint: 'اختر صورة من هذا الكمبيوتر أو الجوال',
    startGallery: 'معرض الصور',
    startGalleryHint: 'تصفّح مجلد الصور وكبّر وحرّك',
    recentTitle: 'الأخيرة',
    recentEmpty: 'لا توجد ملفات حديثة بعد. ما تفتحه أو تحفظه يظهر هنا.',
    recentMissing: 'الملف «{name}» لم يعد موجوداً؛ أُزيل من القائمة.',
    dropHint: 'أو اسحب صورة وأفلتها هنا',
    dropHere: 'أفلت الصورة لفتحها',

    newTitle: 'لوحة جديدة',
    presetSquare: 'منشور مربّع',
    presetStory: 'قصة',
    presetHd: 'Full HD',
    presetA4: 'A4 ‏(300 نقطة/بوصة)',
    presetWeb: 'ويب',
    presetCustom: 'مقاس مخصّص',
    bgLabel: 'الخلفية',
    bgWhite: 'بيضاء',
    bgTransparent: 'شفافة',
    bgColor: 'لون الواجهة',
    create: 'إنشاء',
    widthLabel: 'العرض',
    heightLabel: 'الارتفاع',
    pxUnit: '{w} × {h} بكسل',

    pickerTitle: 'فتح ملف',
    pickerFolderTitle: 'اختر مجلداً',
    pickerUp: 'المجلد الأعلى',
    pickerHome: 'المجلد الرئيسي',
    pickerEmpty: 'لا توجد صور أو مجلدات هنا.',
    pickerChooseFolder: 'اختر هذا المجلد',
    pickerLoading: 'جارٍ التحميل…',
    pickerOpen: 'فتح',

    galleryTitle: 'الصور',
    galleryEmpty: 'مجلد الصور فارغ',
    galleryEmptyHint: 'استورد صوراً من جهازك لتظهر هنا، أو احفظ صورة في /home/user/Pictures.',
    galleryImport: 'استيراد صور',
    galleryCount: '{count} صورة',
    galleryRefresh: 'تحديث',
    galleryImported: 'تم استيراد {count} صورة إلى مجلد الصور.',
    viewerBack: 'رجوع إلى المعرض',
    viewerPrev: 'السابقة',
    viewerNext: 'التالية',
    viewerEdit: 'تحرير سريع',
    viewerPro: 'تحرير احترافي',
    viewerLoading: 'جارٍ فتح الصورة…',

    toolHand: 'اليد (تحريك العرض)',
    toolZoom: 'التكبير',
    toolMarquee: 'تحديد مستطيل/بيضاوي',
    toolLasso: 'الوهق (تحديد حرّ)',
    toolWand: 'العصا السحرية',
    toolEraser: 'الممحاة',
    toolBucket: 'دلو الألوان',
    toolGradient: 'التدرّج',
    toolEyedropper: 'القطّارة',
    toolClone: 'ختم النسخ',
    toolShape: 'الأشكال',
    hintMove: 'اسحب لتحريك الطبقة. انقر على نص أو شكل لاختياره، وانقر مرتين على نص لتحريره.',
    hintHand: 'اسحب لتحريك العرض. Space + سحب يعمل مع أي أداة.',
    hintZoom: 'انقر للتكبير، وAlt + نقر للتصغير.',
    hintMarquee: 'اسحب لتحديد منطقة. Shift يضيف، Alt يطرح.',
    hintLasso: 'ارسم حول المنطقة بإصبعك أو الفأرة.',
    hintWand: 'انقر على لون لتحديد ما يشبهه.',
    hintCrop: 'اسحب الحواف أو الزوايا، ثم «تطبيق» أو Enter.',
    hintBrush: 'ارسم على الطبقة الحالية. [ و ] لتغيير الحجم.',
    hintEraser: 'امسح من الطبقة الحالية.',
    hintBucket: 'انقر لملء منطقة متشابهة اللون.',
    hintGradient: 'اسحب لرسم تدرّج من لون الواجهة إلى لون الخلفية.',
    hintEyedropper: 'انقر لالتقاط لون من الصورة.',
    hintClone: 'اختر المصدر أولاً (Alt + نقر أو زر «تحديد المصدر»)، ثم ارسم.',
    hintCloneSource: 'انقر على المكان الذي تريد النسخ منه.',
    hintText: 'انقر لإضافة نص، أو على نص موجود لتحريره.',
    hintShape: 'اسحب لرسم شكل جديد، أو انقر على شكل لتعديله.',

    optSize: 'الحجم',
    optHardness: 'الصلابة',
    optOpacity: 'العتامة',
    optColor: 'اللون',
    optTolerance: 'التسامح',
    optContiguous: 'متصل فقط',
    optSampleAll: 'كل الطبقات',
    optMode: 'طريقة التحديد',
    selReplace: 'تحديد جديد',
    selAdd: 'إضافة',
    selSubtract: 'طرح',
    selIntersect: 'تقاطع',
    shapeRectSel: 'مستطيل',
    shapeEllipseSel: 'بيضاوي',
    optFill: 'تعبئة',
    optStroke: 'حدّ',
    optStrokeWidth: 'سُمك الحدّ',
    optRadius: 'استدارة الزوايا',
    gradLinear: 'خطّي',
    gradRadial: 'دائري',
    gradToTransparent: 'إلى شفاف',
    optFont: 'الخط',
    fontSystem: 'خط النظام',
    fontNaskh: 'نسخ',
    fontKufi: 'كوفي',
    fontSerif: 'مذيّل',
    fontMono: 'ثابت العرض',
    fontDisplay: 'عريض للعناوين',
    optBold: 'عريض',
    optItalic: 'مائل',
    optAlign: 'المحاذاة',
    alignStart: 'بداية السطر',
    alignCenter: 'وسط',
    alignEnd: 'نهاية السطر',
    optDirection: 'الاتجاه',
    dirAuto: 'تلقائي',
    dirRtl: 'من اليمين',
    dirLtr: 'من اليسار',
    optOutline: 'إطار النص',
    textDefault: 'نص جديد',
    textField: 'النص',
    cloneSetSource: 'تحديد المصدر',
    foreground: 'لون الواجهة',
    background: 'لون الخلفية',
    swapColors: 'تبديل اللونين',
    resetColors: 'الأسود والأبيض',
    pickerSv: 'التشبّع والإضاءة',
    pickerHue: 'درجة اللون',
    pickerHex: 'رمز اللون',
    pickerSwatches: 'ألوان جاهزة',
    colorPicked: 'التُقط اللون {color}',
    toolOptions: 'خيارات الأداة',

    selectAll: 'تحديد الكل',
    deselect: 'إلغاء التحديد',
    invertSelection: 'عكس التحديد',
    deleteSelection: 'حذف المحدَّد',
    cropToSelection: 'قص إلى التحديد',
    fillSelection: 'ملء التحديد',
    copy: 'نسخ',
    cut: 'قص',
    paste: 'لصق',
    pasted: 'لُصقت الصورة كطبقة جديدة.',
    copied: 'نُسخ المحدَّد.',
    nothingToPaste: 'لا توجد صورة في الحافظة.',
    selectionNone: 'لا يوجد تحديد.',

    cropOriginal: 'الأصلية',
    straighten: 'تعديل الميلان',
    cropSize: '{w} × {h}',

    layersTitle: 'الطبقات',
    layerAdd: 'طبقة جديدة',
    layerDuplicate: 'تكرار الطبقة',
    layerDelete: 'حذف الطبقة',
    layerMergeDown: 'دمج مع السفلى',
    layerFlatten: 'تسطيح الصورة',
    layerUp: 'رفع الطبقة',
    layerDown: 'خفض الطبقة',
    layerRename: 'إعادة التسمية',
    layerShow: 'إظهار الطبقة',
    layerHide: 'إخفاء الطبقة',
    layerLock: 'قفل الطبقة',
    layerUnlock: 'فتح قفل الطبقة',
    layerOpacity: 'عتامة الطبقة',
    layerBlend: 'وضع الدمج',
    layerBackground: 'الخلفية',
    layerName: 'طبقة',
    layerCopySuffix: 'نسخة',
    layerLocked: 'الطبقة «{name}» مقفلة. افتح القفل أولاً.',
    layerNeedsRaster: 'هذه الأداة تعمل على طبقات البكسل؛ أُضيفت طبقة جديدة فوق «{name}».',
    layerAdjustNeedsRaster: 'التعديلات والفلاتر تعمل على طبقات البكسل. اختر طبقة صورة أو دمج الطبقات أولاً.',
    layerDragHint: 'اسحب لإعادة الترتيب',
    layerKindRaster: 'بكسل',
    layerKindText: 'نص',
    layerKindShape: 'شكل',
    blendNormal: 'عادي',
    blendMultiply: 'ضرب',
    blendScreen: 'شاشة',
    blendOverlay: 'تراكب',
    blendDarken: 'تغميق',
    blendLighten: 'تفتيح',
    blendColorDodge: 'تفادي اللون',
    blendColorBurn: 'حرق اللون',
    blendHardLight: 'ضوء قاسٍ',
    blendSoftLight: 'ضوء ناعم',
    blendDifference: 'فرق',
    blendExclusion: 'استبعاد',
    blendHue: 'درجة اللون',
    blendSaturation: 'تشبّع',
    blendColor: 'لون',
    blendLuminosity: 'إضاءة',

    adjTint: 'الصبغة',
    adjHue: 'درجة اللون',
    adjVibrance: 'الحيوية',
    adjInvert: 'عكس الألوان',
    adjGrayscale: 'تدرّج رمادي',
    groupLight: 'الإضاءة',
    groupColor: 'اللون',
    adjApply: 'تطبيق',
    adjCancel: 'إلغاء',
    adjTarget: 'على: {layer}',
    adjTargetSel: 'على: {layer} — داخل التحديد فقط',
    applying: 'جارٍ التطبيق…',
    appliedName: 'طُبّق: {name}',

    filterNoir: 'نوار',
    filterFade: 'باهت',
    filterInvert: 'سالب',
    filterBlur: 'ضبابية',
    filterSharpen: 'حِدّة',
    filterNoise: 'حُبيبات',
    filterVignette: 'تظليل الأطراف',
    filterGrayscale: 'رمادي',
    filterVintage: 'قديم',
    filterGolden: 'ذهبي',
    filterDesert: 'صحراوي',
    filterPixelate: 'بكسلة',
    filterPosterize: 'ملصق',
    filterEmboss: 'نقش بارز',
    filterEdges: 'حواف',
    filterAmount: 'الشدّة',
    filterPreviewHint: 'معاينة — «تطبيق» لتثبيت الفلتر.',

    histogramTitle: 'المدرّج التكراري',
    histogramLabel: 'توزيع الإضاءة والألوان في الصورة',

    hOpen: 'فتح',
    hNew: 'لوحة جديدة',
    hMove: 'تحريك',
    hBrush: 'فرشاة',
    hEraser: 'ممحاة',
    hFill: 'ملء',
    hGradient: 'تدرّج',
    hClone: 'ختم النسخ',
    hText: 'نص جديد',
    hTextEdit: 'تحرير نص',
    hShape: 'شكل جديد',
    hShapeEdit: 'تعديل شكل',
    hCrop: 'قص',
    hRotate: 'تدوير',
    hFlip: 'قلب',
    hResize: 'تحجيم',
    hLayerAdd: 'طبقة جديدة',
    hLayerDup: 'تكرار طبقة',
    hLayerDelete: 'حذف طبقة',
    hLayerOrder: 'ترتيب الطبقات',
    hLayerProps: 'خصائص الطبقة',
    hMerge: 'دمج للأسفل',
    hFlatten: 'تسطيح',
    hDelete: 'حذف المحدَّد',
    hPaste: 'لصق',
    hAdjust: 'تعديلات',
    hFilter: 'فلتر: {name}',

    imageTitle: 'الصورة',
    canvasSize: 'مقاس اللوحة',

    exportScale: 'المقاس',
    exportDims: '{w} × {h} بكسل',
    exportEstimate: 'الحجم التقريبي: {size}',
    exportEstimating: 'جارٍ حساب الحجم…',
    exportName: 'اسم الملف',
    exportFolder: 'المجلد',
    exportBrowse: 'استعراض',
    exportDownload: 'تنزيل إلى الجهاز',
    exportSave: 'حفظ في الملفات',
    exportReplace: 'استبدال الأصل (مع نسخة ‎.bak واحدة)',
    exportJpegNote: 'JPEG لا يدعم الشفافية؛ تُملأ المناطق الشفافة بالأبيض.',
    exportSaved: 'تم الحفظ والتحقق: {path}',
    exportVerifyFailed: 'كُتب الملف لكن قراءته للتحقق فشلت. جرّب الحفظ مرة أخرى.',
    downloadDone: 'بدأ تنزيل {name}.',
    exportQuick: 'تصدير سريع',

    saveProject: 'حفظ المشروع',
    saveProjectAs: 'حفظ المشروع باسم',
    projectSaved: 'حُفظ المشروع بطبقاته: {path}',
    projectPath: 'مسار المشروع',
    projectNotJson: 'ملف المشروع تالف: ليس JSON صالحاً.',
    projectWrongFormat: 'هذا الملف ليس مشروع استوديو الصور.',
    projectNewer: 'هذا المشروع من إصدار أحدث من المحرّر.',
    projectBadLayer: 'إحدى طبقات المشروع تالفة، فلم يُفتح.',
    projectTooLarge: 'المشروع أكبر من الحدّ الذي يفتحه المحرّر.',
    projectExtNote: 'يُحفظ بكل الطبقات والنصوص القابلة للتحرير بامتداد ‎.fphoto.',

    compare: 'قبل / بعد',
    compareHint: 'اضغط مطوّلاً أو فعّل للمقارنة بالأصل',
    help: 'المساعدة',
    shortcutsTitle: 'اختصارات لوحة المفاتيح',
    brushSmaller: 'تصغير الفرشاة',
    brushBigger: 'تكبير الفرشاة',
    newCanvas: 'لوحة جديدة',
    newLayerShortcut: 'طبقة جديدة',
    statusSize: '{w} × {h} بكسل',
    statusLayers: '{count} طبقات',
    statusReady: 'جاهز',
    busyOpening: 'جارٍ فتح «{name}»…',
    errorRetry: 'إعادة المحاولة',
    errorChooseAnother: 'اختر ملفاً آخر',
    errorFile: 'تعذّر فتح «{name}»: {reason}',
    discardOk: 'إغلاق بدون حفظ',
    discardCancel: 'متابعة التحرير',
    sheetClose: 'إغلاق اللوحة',
    navTools: 'الأدوات',
    navAdjust: 'تعديل',
    navFilters: 'فلاتر',
    navLayers: 'طبقات',
    navMore: 'المزيد',
    navCrop: 'قص',
    navExport: 'تصدير',
    panelCollapse: 'طيّ {name}',
    zoomValue: '{value}٪',
    rotateTitle: 'تدوير وقلب',
    quickLight: 'الإضاءة واللون',
    quickCropTitle: 'قص وتدوير',
    quickFiltersHint: 'نقرة واحدة تطبّق الفلتر، و«تراجع» يعيده.',
    viewReadOnly: 'عرض',
    importing: 'جارٍ الاستيراد…',
  },
  en: {
    appName: 'Image Studio',
    modeGallery: 'Gallery',
    modeQuick: 'Quick edit',
    modePro: 'Pro',
    modeLabel: 'Workspace',
    menu: 'Menu',
    untitled: 'Untitled',
    unsavedMark: 'Unsaved changes',
    savedMark: 'Saved',

    startTitle: 'Image Studio',
    startSubtitle: 'Edit photos with layers, Arabic text and filters — everything stays on your device.',
    startNew: 'New canvas',
    startNewHint: 'Square, story, HD, A4 or a custom size',
    startOpen: 'Open from Files',
    startOpenHint: 'An image or a .fphoto project from your folders',
    startDevice: 'Open from device',
    startDeviceHint: 'Pick an image from this computer or phone',
    startGallery: 'Photo gallery',
    startGalleryHint: 'Browse your Pictures folder, zoom and pan',
    recentTitle: 'Recent',
    recentEmpty: 'No recent files yet. What you open or save appears here.',
    recentMissing: '“{name}” no longer exists; it was removed from the list.',
    dropHint: 'or drag an image here and drop it',
    dropHere: 'Drop the image to open it',

    newTitle: 'New canvas',
    presetSquare: 'Square post',
    presetStory: 'Story',
    presetHd: 'Full HD',
    presetA4: 'A4 (300 dpi)',
    presetWeb: 'Web',
    presetCustom: 'Custom size',
    bgLabel: 'Background',
    bgWhite: 'White',
    bgTransparent: 'Transparent',
    bgColor: 'Foreground colour',
    create: 'Create',
    widthLabel: 'Width',
    heightLabel: 'Height',
    pxUnit: '{w} × {h} px',

    pickerTitle: 'Open a file',
    pickerFolderTitle: 'Choose a folder',
    pickerUp: 'Parent folder',
    pickerHome: 'Home folder',
    pickerEmpty: 'No images or folders here.',
    pickerChooseFolder: 'Choose this folder',
    pickerLoading: 'Loading…',
    pickerOpen: 'Open',

    galleryTitle: 'Photos',
    galleryEmpty: 'Your Pictures folder is empty',
    galleryEmptyHint: 'Import photos from your device to see them here, or save an image to /home/user/Pictures.',
    galleryImport: 'Import photos',
    galleryCount: '{count} photos',
    galleryRefresh: 'Refresh',
    galleryImported: 'Imported {count} photos into Pictures.',
    viewerBack: 'Back to the gallery',
    viewerPrev: 'Previous',
    viewerNext: 'Next',
    viewerEdit: 'Quick edit',
    viewerPro: 'Pro edit',
    viewerLoading: 'Opening the photo…',

    toolHand: 'Hand (pan the view)',
    toolZoom: 'Zoom',
    toolMarquee: 'Rectangle/ellipse select',
    toolLasso: 'Lasso (free select)',
    toolWand: 'Magic wand',
    toolEraser: 'Eraser',
    toolBucket: 'Paint bucket',
    toolGradient: 'Gradient',
    toolEyedropper: 'Eyedropper',
    toolClone: 'Clone stamp',
    toolShape: 'Shapes',
    hintMove: 'Drag to move the layer. Click text or a shape to pick it; double-click text to edit it.',
    hintHand: 'Drag to pan. Space + drag works with any tool.',
    hintZoom: 'Click to zoom in, Alt + click to zoom out.',
    hintMarquee: 'Drag to select an area. Shift adds, Alt subtracts.',
    hintLasso: 'Draw around the area with a finger or the mouse.',
    hintWand: 'Click a colour to select everything like it.',
    hintCrop: 'Drag the edges or corners, then Apply or press Enter.',
    hintBrush: 'Paint on the current layer. [ and ] change the size.',
    hintEraser: 'Erase from the current layer.',
    hintBucket: 'Click to fill a similar-coloured area.',
    hintGradient: 'Drag to draw a gradient from the foreground to the background colour.',
    hintEyedropper: 'Click to pick a colour from the image.',
    hintClone: 'Set a source first (Alt + click or “Set source”), then paint.',
    hintCloneSource: 'Click where you want to copy from.',
    hintText: 'Click to add text, or click existing text to edit it.',
    hintShape: 'Drag to draw a new shape, or click a shape to edit it.',

    optSize: 'Size',
    optHardness: 'Hardness',
    optOpacity: 'Opacity',
    optColor: 'Colour',
    optTolerance: 'Tolerance',
    optContiguous: 'Contiguous',
    optSampleAll: 'All layers',
    optMode: 'Selection mode',
    selReplace: 'New selection',
    selAdd: 'Add',
    selSubtract: 'Subtract',
    selIntersect: 'Intersect',
    shapeRectSel: 'Rectangle',
    shapeEllipseSel: 'Ellipse',
    optFill: 'Fill',
    optStroke: 'Stroke',
    optStrokeWidth: 'Stroke width',
    optRadius: 'Corner radius',
    gradLinear: 'Linear',
    gradRadial: 'Radial',
    gradToTransparent: 'To transparent',
    optFont: 'Font',
    fontSystem: 'System',
    fontNaskh: 'Naskh',
    fontKufi: 'Kufi',
    fontSerif: 'Serif',
    fontMono: 'Monospace',
    fontDisplay: 'Bold display',
    optBold: 'Bold',
    optItalic: 'Italic',
    optAlign: 'Alignment',
    alignStart: 'Line start',
    alignCenter: 'Centre',
    alignEnd: 'Line end',
    optDirection: 'Direction',
    dirAuto: 'Automatic',
    dirRtl: 'Right to left',
    dirLtr: 'Left to right',
    optOutline: 'Text outline',
    textDefault: 'New text',
    textField: 'Text',
    cloneSetSource: 'Set source',
    foreground: 'Foreground colour',
    background: 'Background colour',
    swapColors: 'Swap colours',
    resetColors: 'Black and white',
    pickerSv: 'Saturation and brightness',
    pickerHue: 'Hue',
    pickerHex: 'Colour code',
    pickerSwatches: 'Preset colours',
    colorPicked: 'Picked {color}',
    toolOptions: 'Tool options',

    selectAll: 'Select all',
    deselect: 'Deselect',
    invertSelection: 'Invert selection',
    deleteSelection: 'Delete selected',
    cropToSelection: 'Crop to selection',
    fillSelection: 'Fill selection',
    copy: 'Copy',
    cut: 'Cut',
    paste: 'Paste',
    pasted: 'Pasted the image as a new layer.',
    copied: 'Copied the selection.',
    nothingToPaste: 'There is no image on the clipboard.',
    selectionNone: 'Nothing is selected.',

    cropOriginal: 'Original',
    straighten: 'Straighten',
    cropSize: '{w} × {h}',

    layersTitle: 'Layers',
    layerAdd: 'New layer',
    layerDuplicate: 'Duplicate layer',
    layerDelete: 'Delete layer',
    layerMergeDown: 'Merge down',
    layerFlatten: 'Flatten image',
    layerUp: 'Move layer up',
    layerDown: 'Move layer down',
    layerRename: 'Rename',
    layerShow: 'Show layer',
    layerHide: 'Hide layer',
    layerLock: 'Lock layer',
    layerUnlock: 'Unlock layer',
    layerOpacity: 'Layer opacity',
    layerBlend: 'Blend mode',
    layerBackground: 'Background',
    layerName: 'Layer',
    layerCopySuffix: 'copy',
    layerLocked: 'The layer “{name}” is locked. Unlock it first.',
    layerNeedsRaster: 'This tool paints on pixel layers; a new layer was added above “{name}”.',
    layerAdjustNeedsRaster: 'Adjustments and filters work on pixel layers. Pick an image layer or merge the layers first.',
    layerDragHint: 'Drag to reorder',
    layerKindRaster: 'Pixels',
    layerKindText: 'Text',
    layerKindShape: 'Shape',
    blendNormal: 'Normal',
    blendMultiply: 'Multiply',
    blendScreen: 'Screen',
    blendOverlay: 'Overlay',
    blendDarken: 'Darken',
    blendLighten: 'Lighten',
    blendColorDodge: 'Colour dodge',
    blendColorBurn: 'Colour burn',
    blendHardLight: 'Hard light',
    blendSoftLight: 'Soft light',
    blendDifference: 'Difference',
    blendExclusion: 'Exclusion',
    blendHue: 'Hue',
    blendSaturation: 'Saturation',
    blendColor: 'Colour',
    blendLuminosity: 'Luminosity',

    adjTint: 'Tint',
    adjHue: 'Hue',
    adjVibrance: 'Vibrance',
    adjInvert: 'Invert colours',
    adjGrayscale: 'Grayscale',
    groupLight: 'Light',
    groupColor: 'Colour',
    adjApply: 'Apply',
    adjCancel: 'Cancel',
    adjTarget: 'On: {layer}',
    adjTargetSel: 'On: {layer} — inside the selection only',
    applying: 'Applying…',
    appliedName: 'Applied: {name}',

    filterNoir: 'Noir',
    filterFade: 'Fade',
    filterInvert: 'Negative',
    filterBlur: 'Blur',
    filterSharpen: 'Sharpen',
    filterNoise: 'Grain',
    filterVignette: 'Vignette',
    filterGrayscale: 'Grayscale',
    filterVintage: 'Vintage',
    filterGolden: 'Golden',
    filterDesert: 'Desert',
    filterPixelate: 'Pixelate',
    filterPosterize: 'Posterize',
    filterEmboss: 'Emboss',
    filterEdges: 'Edges',
    filterAmount: 'Strength',
    filterPreviewHint: 'Preview — press Apply to keep the filter.',

    histogramTitle: 'Histogram',
    histogramLabel: 'How light and colour are spread across the image',

    hOpen: 'Open',
    hNew: 'New canvas',
    hMove: 'Move',
    hBrush: 'Brush',
    hEraser: 'Eraser',
    hFill: 'Fill',
    hGradient: 'Gradient',
    hClone: 'Clone stamp',
    hText: 'New text',
    hTextEdit: 'Edit text',
    hShape: 'New shape',
    hShapeEdit: 'Edit shape',
    hCrop: 'Crop',
    hRotate: 'Rotate',
    hFlip: 'Flip',
    hResize: 'Resize',
    hLayerAdd: 'New layer',
    hLayerDup: 'Duplicate layer',
    hLayerDelete: 'Delete layer',
    hLayerOrder: 'Reorder layers',
    hLayerProps: 'Layer properties',
    hMerge: 'Merge down',
    hFlatten: 'Flatten',
    hDelete: 'Delete selected',
    hPaste: 'Paste',
    hAdjust: 'Adjustments',
    hFilter: 'Filter: {name}',

    imageTitle: 'Image',
    canvasSize: 'Canvas size',

    exportScale: 'Size',
    exportDims: '{w} × {h} px',
    exportEstimate: 'Estimated size: {size}',
    exportEstimating: 'Working out the size…',
    exportName: 'File name',
    exportFolder: 'Folder',
    exportBrowse: 'Browse',
    exportDownload: 'Download to device',
    exportSave: 'Save to Files',
    exportReplace: 'Replace the original (keeps one .bak)',
    exportJpegNote: 'JPEG has no transparency; transparent areas are filled with white.',
    exportSaved: 'Saved and verified: {path}',
    exportVerifyFailed: 'The file was written but reading it back to verify failed. Try saving again.',
    downloadDone: 'Downloading {name}.',
    exportQuick: 'Quick export',

    saveProject: 'Save project',
    saveProjectAs: 'Save project as',
    projectSaved: 'Saved the project with its layers: {path}',
    projectPath: 'Project path',
    projectNotJson: 'The project file is damaged: it is not valid JSON.',
    projectWrongFormat: 'This file is not an Image Studio project.',
    projectNewer: 'This project comes from a newer version of the editor.',
    projectBadLayer: 'One of the project’s layers is damaged, so it was not opened.',
    projectTooLarge: 'The project is larger than the editor opens.',
    projectExtNote: 'Saved with every layer and editable text, as .fphoto.',

    compare: 'Before / after',
    compareHint: 'Hold or toggle to compare with the original',
    help: 'Help',
    shortcutsTitle: 'Keyboard shortcuts',
    brushSmaller: 'Smaller brush',
    brushBigger: 'Bigger brush',
    newCanvas: 'New canvas',
    newLayerShortcut: 'New layer',
    statusSize: '{w} × {h} px',
    statusLayers: '{count} layers',
    statusReady: 'Ready',
    busyOpening: 'Opening “{name}”…',
    errorRetry: 'Try again',
    errorChooseAnother: 'Choose another file',
    errorFile: 'Could not open “{name}”: {reason}',
    discardOk: 'Close without saving',
    discardCancel: 'Keep editing',
    sheetClose: 'Close the panel',
    navTools: 'Tools',
    navAdjust: 'Adjust',
    navFilters: 'Filters',
    navLayers: 'Layers',
    navMore: 'More',
    navCrop: 'Crop',
    navExport: 'Export',
    panelCollapse: 'Collapse {name}',
    zoomValue: '{value}%',
    rotateTitle: 'Rotate and flip',
    quickLight: 'Light and colour',
    quickCropTitle: 'Crop and rotate',
    quickFiltersHint: 'One click applies a filter; Undo takes it back.',
    viewReadOnly: 'View',
    importing: 'Importing…',
  },
});
