import { defineStrings } from '../../kernel/i18n';

/**
 * Every visible string of the Photo Editor, Arabic and English with identical key sets.
 * `src/apps/web/strings.test.ts` compares the two tables key by key across the whole OS, so
 * a key added to one language only fails the suite — which is the point of centralising them
 * here instead of building sentences inline.
 *
 * The format names (PNG, JPEG, WebP, GIF, BMP, AVIF, SVG) are product names and stay the
 * same in both languages.
 */
defineStrings('photo', {
  ar: {
    title: 'محرّر الصور',
    openFile: 'فتح',
    openTitle: 'فتح صورة',
    openHint: 'المسار الكامل لصورة داخل المجلد الرئيسي',
    openPlaceholder: '/home/user/Pictures/photo.png',
    openAction: 'افتح',
    openCancel: 'إلغاء',
    loading: 'جارٍ فتح الصورة…',
    saveAsCopy: 'حفظ نسخة',
    overwrite: 'استبدال الأصل',
    exportTitle: 'تصدير',
    exportFormat: 'الصيغة',
    exportQuality: 'الجودة',
    exportTarget: 'المسار',
    exportHint: 'يُكتب داخل /home/user فقط.',
    exportConfirm: 'صدّر',
    exportDoneCopy: 'تم حفظ نسخة في {path}',
    exportDoneOverwrite: 'تم استبدال {path}، والنسخة الاحتياطية في {bak}',
    exportDoneOverwriteNoBak: 'تم استبدال {path} (أُنشئت نسخة احتياطية واحدة لأنها لم تكن موجودة)',
    exportFailed: 'تعذّر التصدير: {reason}',
    exportNoTarget: 'لا يوجد ملف أصلي لاستبداله — افتح ملفاً أولاً أو استخدم «حفظ نسخة».',
    exportTooBig: 'الملف الناتج أكبر من الحدّ الذي يقبله نظام الملفات (٢٠ ميجابايت). جرّب جودة أقل أو حجماً أصغر.',
    exportQuota: 'لا توجد مساحة كافية في نظام الملفات.',
    exportUnsupported: 'هذا المتصفح لا يستطيع ترميز {format}. اختر PNG أو JPEG.',

    undo: 'تراجع',
    redo: 'إعادة',
    reset: 'إرجاع الأصل',
    history: 'السجل',
    historyTitle: 'سجل التعديلات',
    historyTrimmed: 'أُسقط {count} خطوة قديمة لتوفير الذاكرة',
    historyMemory: 'السجل: {steps} خطوة ({size} من {budget} كحدّ أعلى)',
    historyPolicy:
      'السياسة: كل خطوة نسخة كاملة من الصورة (العرض×الارتفاع×٤ بايت)، ويُحتفظ بـ٢٠ خطوة على الأقل دائماً — حتى لو تجاوزت الميزانية — ثم يُسقط الأقدم عند {budget}. حدّ أقصى {steps} خطوة.',

    zoomIn: 'تكبير',
    zoomOut: 'تصغير',
    zoomFit: 'ملاءمة',
    zoomActual: '١٠٠٪',
    zoom: 'التقريب',

    toolsTitle: 'الأدوات',
    toolMove: 'تحريك',
    toolSelect: 'تحديد',
    toolCrop: 'قص',
    toolBrush: 'قلم',
    toolLine: 'خط',
    toolRect: 'مستطيل',
    toolEllipse: 'بيضاوي',
    toolArrow: 'سهم',
    toolText: 'نص',

    transformTitle: 'التحويل',
    rotateLeft: 'تدوير ٩٠° يساراً',
    rotateRight: 'تدوير ٩٠° يميناً',
    flipH: 'قلب أفقي',
    flipV: 'قلب رأسي',
    rotateFree: 'زاوية حرّة (درجات)',
    apply: 'تطبيق',
    cancel: 'إلغاء',

    cropTitle: 'القص',
    cropAspect: 'النسبة',
    cropFree: 'حرّة',
    cropApply: 'اقتطع',
    cropReset: 'إلغاء التحديد',
    cropHint: 'اسحب على الصورة لتحديد المستطيل، ثم «اقتطع».',
    cropInvalid: 'التحديد أصغر من بكسل واحد.',

    resizeTitle: 'تحجيم',
    resizeWidth: 'العرض',
    resizeHeight: 'الارتفاع',
    resizeLock: 'تثبيت النسبة',
    resizePercent: 'النسبة ٪',
    resizeApply: 'طبّق',
    resizeSame: 'الحجم نفسه — لا تغيير.',

    adjustTitle: 'تعديلات',
    adjBrightness: 'السطوع',
    adjContrast: 'التباين',
    adjSaturation: 'التشبّع',
    adjExposure: 'التعريض',
    adjTemperature: 'حرارة اللون',
    adjHighlights: 'الإضاءات',
    adjShadows: 'الظلال',
    adjResetAll: 'تصفير الكل',

    blurTitle: 'ضبابية',
    sharpenTitle: 'حِدّة',
    effectRadius: 'نصف القطر',
    effectAmount: 'المقدار',
    applyBlur: 'أضف ضبابية',
    applySharpen: 'أضف حِدّة',

    filtersTitle: 'فلاتر جاهزة',
    filterNone: 'بلا',
    filterMono: 'أبيض وأسود',
    filterSepia: 'سيبيا',
    filterVivid: 'زاهي',
    filterSoft: 'ناعم',
    filterPunch: 'حادّ',
    filterWarm: 'دافئ',
    filterCool: 'بارد',
    filterHint: 'الفلتر يضبط قيم التعديلات، ويمكن تعديلها بعده.',

    brushColor: 'اللون',
    brushSize: 'الحجم',
    shapeFill: 'تعبئة',
    textContent: 'النص',
    textPlaceholder: 'اكتب هنا',
    textSize: 'حجم الخط',
    textColor: 'لون النص',
    textHint: 'انقر على الصورة ثم اكتب — يُثبَّت النص عند الضغط على «أضف».',
    textAdd: 'أضف',
    textNeedsContent: 'اكتب نصاً أولاً.',

    selectHint: 'لتحديد جزء: اسحب داخل التحديد لنقله.',
    moveHint: 'أدوات الرسم تعمل على الصورة كاملة الآن.',

    fileTitle: 'الملف',
    sizeLabel: 'الحجم',
    colorspace: 'الفضاء اللوني',
    colorspaceRgb: 'RGB ٨ بت لكل قناة',

    capTitle: 'الصيغ المدعومة الآن',
    capOpens: 'فتح: {list}',
    capExports: 'تصدير: {list}',
    capProbe: 'الفحص جرى في هذا المتصفح عند فتح النافذة.',
    capUnsupported: 'غير مدعوم: {list}',
    capAnimFirst: 'الصورة المتحركة (GIF/WebP/APNG): تُفتح الأول فقط، والحفظ يُثبّت الإطار الأول — لا تحرير للحركة.',

    limitsTitle: 'حدود صريحة — ما لا يفعله هذا المحرّر',
    limitLayers: 'لا طبقات ولا أوضاع دمج: كل تعديل يُدمج في الصورة مباشرة.',
    limitCmyk: 'لا CMYK ولا إدارة ألوان ولا ملفات ICC.',
    limitRaw: 'لا RAW ولا HEIC/HEIF ولا TIFF ولا ICO.',
    limitAnim: 'لا تحرير للصور المتحركة (تُفتح الأولى فقط).',
    limitVector: 'لا تحرير متجهي لملفات SVG — تُحوَّل إلى نقاط عند الفتح.',
    limitText: 'النص يُثبَّت على الصورة كبكسلات عند الإضافة، ولا يبقى قابلاً للتحرير.',
    limitBrush: 'لا أقنعة ولا عصا سحرية ولا ملء ذكي.',
    limitQuota: 'الكتابة في نظام الملفات محدودة: ٢٠ ميجابايت للملف و٥٠ ميجابايت للمجموع.',
    limitColors: 'لا إدارة لكاميرا ولا بيانات EXIF عند الحفظ — الحفظ يعيد ترميز البكسلات فقط.',
    limitNoOriginal: 'فتح ملف لا يعدّله؛ لا يُكتب على القرص إلا عند «حفظ نسخة» أو «استبدال الأصل».',
    limitClosing: 'التغييرات غير المحفوظة تُفقد عند إغلاق النافذة (يُسألك قبل الإغلاق).',

    discardTitle: 'تغييرات غير محفوظة',
    discardBody: 'لديك تغييرات لم تُحفظ. إغلاق النافذة يفقدها. أغلق على أي حال؟',

    errorTitle: 'تعذّر فتح الصورة',
    errorUnknown: 'خطأ غير معروف.',
    noImage: 'لا توجد صورة مفتوحة. استخدم «فتح» لاختيار صورة.',
    close: 'إغلاق',
  },
  en: {
    title: 'Photo Editor',
    openFile: 'Open',
    openTitle: 'Open an image',
    openHint: 'The full path of an image inside the home folder',
    openPlaceholder: '/home/user/Pictures/photo.png',
    openAction: 'Open',
    openCancel: 'Cancel',
    loading: 'Opening the image…',
    saveAsCopy: 'Save a copy',
    overwrite: 'Overwrite original',
    exportTitle: 'Export',
    exportFormat: 'Format',
    exportQuality: 'Quality',
    exportTarget: 'Path',
    exportHint: 'Writes inside /home/user only.',
    exportConfirm: 'Export',
    exportDoneCopy: 'Saved a copy to {path}',
    exportDoneOverwrite: 'Replaced {path}; the backup is at {bak}',
    exportDoneOverwriteNoBak: 'Replaced {path} (one backup was created, since none existed)',
    exportFailed: 'Export failed: {reason}',
    exportNoTarget: 'There is no original file to overwrite — open a file first, or use “Save a copy”.',
    exportTooBig: 'The result is larger than the file system accepts (20 MB). Try a lower quality or a smaller size.',
    exportQuota: 'The file system has no room left.',
    exportUnsupported: 'This browser cannot encode {format}. Choose PNG or JPEG.',

    undo: 'Undo',
    redo: 'Redo',
    reset: 'Revert to original',
    history: 'History',
    historyTitle: 'Edit history',
    historyTrimmed: '{count} older steps were dropped to save memory',
    historyMemory: 'History: {steps} steps ({size} of a {budget} ceiling)',
    historyPolicy:
      'Policy: each step is a full snapshot of the image (width×height×4 bytes); at least 20 steps are always kept — even past the budget — and the oldest are dropped above {budget}. Hard ceiling: {steps} steps.',

    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    zoomFit: 'Fit',
    zoomActual: '100%',
    zoom: 'Zoom',

    toolsTitle: 'Tools',
    toolMove: 'Move',
    toolSelect: 'Select',
    toolCrop: 'Crop',
    toolBrush: 'Brush',
    toolLine: 'Line',
    toolRect: 'Rectangle',
    toolEllipse: 'Ellipse',
    toolArrow: 'Arrow',
    toolText: 'Text',

    transformTitle: 'Transform',
    rotateLeft: 'Rotate 90° left',
    rotateRight: 'Rotate 90° right',
    flipH: 'Flip horizontally',
    flipV: 'Flip vertically',
    rotateFree: 'Free angle (degrees)',
    apply: 'Apply',
    cancel: 'Cancel',

    cropTitle: 'Crop',
    cropAspect: 'Aspect',
    cropFree: 'Free',
    cropApply: 'Crop',
    cropReset: 'Clear selection',
    cropHint: 'Drag on the image to mark the rectangle, then press “Crop”.',
    cropInvalid: 'The selection is smaller than one pixel.',

    resizeTitle: 'Resize',
    resizeWidth: 'Width',
    resizeHeight: 'Height',
    resizeLock: 'Lock aspect',
    resizePercent: 'Percent %',
    resizeApply: 'Apply',
    resizeSame: 'The size is unchanged — nothing to do.',

    adjustTitle: 'Adjustments',
    adjBrightness: 'Brightness',
    adjContrast: 'Contrast',
    adjSaturation: 'Saturation',
    adjExposure: 'Exposure',
    adjTemperature: 'Temperature',
    adjHighlights: 'Highlights',
    adjShadows: 'Shadows',
    adjResetAll: 'Reset all',

    blurTitle: 'Blur',
    sharpenTitle: 'Sharpen',
    effectRadius: 'Radius',
    effectAmount: 'Amount',
    applyBlur: 'Apply blur',
    applySharpen: 'Apply sharpen',

    filtersTitle: 'Filter presets',
    filterNone: 'None',
    filterMono: 'Black & white',
    filterSepia: 'Sepia',
    filterVivid: 'Vivid',
    filterSoft: 'Soft',
    filterPunch: 'Punch',
    filterWarm: 'Warm',
    filterCool: 'Cool',
    filterHint: 'A preset sets the adjustment sliders; you can change them afterwards.',

    brushColor: 'Colour',
    brushSize: 'Size',
    shapeFill: 'Fill',
    textContent: 'Text',
    textPlaceholder: 'Type here',
    textSize: 'Font size',
    textColor: 'Text colour',
    textHint: 'Click the image, type, then press “Add” to burn the text in.',
    textAdd: 'Add',
    textNeedsContent: 'Type some text first.',

    selectHint: 'To select an area: drag inside the selection to move it.',
    moveHint: 'Drawing tools now work on the whole image.',

    fileTitle: 'File',
    sizeLabel: 'Size',
    colorspace: 'Colour space',
    colorspaceRgb: 'RGB, 8 bits per channel',

    capTitle: 'Formats supported right now',
    capOpens: 'Opens: {list}',
    capExports: 'Exports: {list}',
    capProbe: 'This check ran in this browser when the window opened.',
    capUnsupported: 'Not supported: {list}',
    capAnimFirst: 'Animated images (GIF/WebP/APNG): only the first frame is opened, and saving keeps that first frame — there is no animation editing.',

    limitsTitle: 'Honest limits — what this editor does not do',
    limitLayers: 'No layers and no blend modes: every edit is flattened into the image.',
    limitCmyk: 'No CMYK, no colour management, no ICC profiles.',
    limitRaw: 'No RAW, no HEIC/HEIF, no TIFF, no ICO.',
    limitAnim: 'No animation editing (only the first frame is opened).',
    limitVector: 'No vector editing of SVG files — they are rasterised on open.',
    limitText: 'Text is burned into pixels when added; it does not stay editable.',
    limitBrush: 'No masks, no magic wand, no content-aware fill.',
    limitQuota: 'Writes are capped by the file system: 20 MB per file and 50 MB in total.',
    limitColors: 'No camera or EXIF metadata is written — saving re-encodes pixels only.',
    limitNoOriginal: 'Opening a file does not change it; nothing is written until “Save a copy” or “Overwrite original”.',
    limitClosing: 'Unsaved changes are lost when the window closes (you are asked first).',

    discardTitle: 'Unsaved changes',
    discardBody: 'You have unsaved changes. Closing the window loses them. Close anyway?',

    errorTitle: 'Could not open the image',
    errorUnknown: 'Unknown error.',
    noImage: 'No image is open. Use “Open” to pick one.',
    close: 'Close',
  },
});
