import { defineStrings } from '../../kernel/i18n';

defineStrings('viewer', {
  ar: {
    title: 'عارض الملفات',
    download: 'تنزيل',
    openTab: 'فتح في تبويب',
    loading: 'جارٍ فتح الملف…',
    noFile: 'افتح أي ملف من تطبيق الملفات وسيظهر هنا.',
    unknown: 'لا يمكن عرض هذا النوع من الملفات هنا، لكنه محفوظ ويمكنك تنزيله وفتحه ببرنامجه.',
    readError: 'تعذّر قراءة الملف. ربما هو تالف أو بصيغة قديمة.',
    pdfNoViewer: 'هذا المتصفح لا يعرض ملفات PDF داخل النظام. افتحه في تبويب أو نزّله.',
    truncated: 'يُعرض أول {rows} صف و{cols} عمود فقط.',
    empty: 'الملف فارغ.',
    slide: 'الشريحة {n}',
    sheets: 'الأوراق',
    kindPdf: 'مستند PDF',
    kindSheet: 'جدول بيانات',
    kindDoc: 'مستند Word',
    kindSlides: 'عرض تقديمي',
    kindAudio: 'ملف صوتي',
    kindVideo: 'ملف فيديو',
    kindImage: 'صورة',
    kindText: 'ملف نصي',
    kindOther: 'ملف',
  },
  en: {
    title: 'File Viewer',
    download: 'Download',
    openTab: 'Open in tab',
    loading: 'Opening the file…',
    noFile: 'Open any file from the Files app and it shows here.',
    unknown: 'This kind of file can’t be shown here, but it is saved: download it and open it in its own program.',
    readError: 'Could not read the file. It may be damaged or in an old format.',
    pdfNoViewer: 'This browser can’t show PDFs inside the system. Open it in a tab or download it.',
    truncated: 'Showing only the first {rows} rows and {cols} columns.',
    empty: 'The file is empty.',
    slide: 'Slide {n}',
    sheets: 'Sheets',
    kindPdf: 'PDF document',
    kindSheet: 'Spreadsheet',
    kindDoc: 'Word document',
    kindSlides: 'Presentation',
    kindAudio: 'Audio file',
    kindVideo: 'Video file',
    kindImage: 'Image',
    kindText: 'Text file',
    kindOther: 'File',
  },
});
