import { defineStrings } from '../../kernel/i18n';

defineStrings('store', {
  ar: {
    title: 'المتجر',
    searchPlaceholder: 'ابحث عن تطبيق…',
    tabExplore: 'استكشف',
    tabInstalled: 'مثبّت',
    tabUpdates: 'التحديثات',
    categoryAll: 'الكل',
    categorySystem: 'النظام',
    categoryUtilities: 'أدوات',
    categoryAccessories: 'ملحقات',
    categoryMedia: 'وسائط',
    categoryDevelopment: 'تطوير',
    featuredBadge: 'مميّز',
    installedBadge: 'مثبّت',
    coreBadge: 'أساسي',
    install: 'تثبيت',
    open: 'فتح',
    remove: 'إزالة',
    removeConfirmTitle: 'إزالة {name}؟',
    removeConfirmBody: 'يمكنك تثبيته مرة أخرى في أي وقت من المتجر.',
    removeConfirmYes: 'إزالة',
    removeConfirmNo: 'إلغاء',
    coreCantRemove: 'تطبيق أساسي — لا يمكن إزالته',
    installing: 'جارٍ التثبيت…',
    removing: 'جارٍ الإزالة…',
    installedNotify: 'تم تثبيت {name}',
    removedNotify: 'تمت إزالة {name}',
    permissionsTitle: 'الأذونات',
    permissionsNone: 'لا يطلب هذا التطبيق أي أذونات.',
    permissionWarning: 'إذن قوي — يمنح هذا التطبيق تحكماً واسعاً بالنظام.',
    versionLabel: 'الإصدار',
    categoryLabel: 'التصنيف',
    noDescription: 'لا يوجد وصف لهذا التطبيق.',
    back: 'رجوع',
    emptyExplore: 'لا توجد تطبيقات مطابقة.',
    emptyInstalled: 'لم تُثبّت أي تطبيقات إضافية بعد.',
    upToDateTitle: 'كل التطبيقات محدَّثة',
    upToDateBody: 'جميع تطبيقاتك المثبَّتة على أحدث إصدار.',
    bannerCta: 'عرض التطبيق',
  },
  en: {
    title: 'Store',
    searchPlaceholder: 'Search for an app…',
    tabExplore: 'Explore',
    tabInstalled: 'Installed',
    tabUpdates: 'Updates',
    categoryAll: 'All',
    categorySystem: 'System',
    categoryUtilities: 'Utilities',
    categoryAccessories: 'Accessories',
    categoryMedia: 'Media',
    categoryDevelopment: 'Development',
    featuredBadge: 'Featured',
    installedBadge: 'Installed',
    coreBadge: 'System app',
    install: 'Install',
    open: 'Open',
    remove: 'Remove',
    removeConfirmTitle: 'Remove {name}?',
    removeConfirmBody: 'You can install it again from the Store at any time.',
    removeConfirmYes: 'Remove',
    removeConfirmNo: 'Cancel',
    coreCantRemove: "System app — can't be removed",
    installing: 'Installing…',
    removing: 'Removing…',
    installedNotify: '{name} installed',
    removedNotify: '{name} removed',
    permissionsTitle: 'Permissions',
    permissionsNone: 'This app requests no permissions.',
    permissionWarning: 'Powerful permission — this app has broad control over the system.',
    versionLabel: 'Version',
    categoryLabel: 'Category',
    noDescription: 'No description for this app.',
    back: 'Back',
    emptyExplore: 'No matching apps.',
    emptyInstalled: "You haven't installed any extra apps yet.",
    upToDateTitle: 'All apps are up to date',
    upToDateBody: 'Every installed app is on its latest version.',
    bannerCta: 'View app',
  },
});
