import { defineStrings } from '../../kernel/i18n';

/**
 * Every visible string of the PDF app, in Arabic and English.
 * The two blocks must hold exactly the same keys — a repo-wide parity test and the
 * app's own `strings.test.ts` both fail otherwise.
 */
defineStrings('pdf', {
  ar: {
    title: 'مستندات PDF',
    badge: 'محرّر PDF',
    tabView: 'عرض',
    tabEdit: 'تعديل',
    loading: 'جارٍ فتح الملف…',
    readError: 'تعذّرت قراءة الملف من نظام الملفات.',
    noFile: 'افتح ملف PDF من تطبيق الملفات وسيظهر هنا.',
    pagesCount: '{n} صفحة',
    pageCountOne: 'صفحة واحدة',
    sizeLabel: 'الحجم: {size}',
    modified: 'مُعدّل',
    reset: 'إعادة تعيين إلى الملف الأصلي',
    resetDone: 'رجعنا إلى الملف الأصلي.',
    busy: 'جارٍ العمل…',

    viewNoViewer: 'هذا المتصفح لا يعرض PDF داخل النظام. نزّل النتيجة أو افتحها في تبويب.',
    openInTab: 'فتح في تبويب',
    download: 'تنزيل النتيجة',
    print: 'طباعة',
    printReady: 'فُتحت نافذة طباعة هذا الملف.',
    printNoViewer: 'هذا المتصفح لا يعرض PDF داخل النظام، فلا نافذة طباعة له. نزّل الملف واطبعه من الخارج.',
    printFailed: 'تعذّر فتح نافذة الطباعة.',
    printNoBytes: 'لا يوجد ملف للطباعة.',
    previewNote: 'المعاينة تعرض النسخة العاملة: بعد التعديلات في الذاكرة وقبل الحفظ.',

    refusalTitle: 'تعذّر فتح هذا الملف',
    refusalEmpty: 'الملف فارغ (صفر بايت).',
    refusalNotPdf: 'هذا ليس ملف PDF: لا توجد ترويسة %PDF- في أوله.',
    refusalEncrypted: 'الملف محمي بكلمة مرور (مشفّر)، ومكتبة pdf-lib ترفض فتحه. أزل الحماية ببرنامج آخر ثم أعد المحاولة.',
    refusalCorrupt: 'يبدو ملف PDF لكن قراءته فشلت: قد يكون تالفاً أو ناقصاً.',
    refusalImageUnsupported: 'هذه الصورة ليست PNG ولا JPEG، ولا يمكن إدراج غير هذين النوعين.',
    refusalImageBroken: 'تعذّرت قراءة هذه الصورة: ترويستها صحيحة لكن بياناتها تالفة أو ناقصة.',
    refusalTextNotRenderable: 'في النص حروف لا تستطيع خطوط PDF المدمجة رسمها (العربية مثلاً). اكتب النص بحروف لاتينية، أو أضف الخط خارج النظام.',
    refusalNoForm: 'هذا المستند لا يحتوي على نموذج تفاعلي (AcroForm) لكتابة القيم فيه.',
    refusalEmptyResult: 'هذه العملية تترك صفر صفحات، ولن أكتب مستنداً فارغاً.',
    refusalOutsideHome: 'الحفظ خارج /home/user غير مسموح.',
    refusalWriteFailed: 'تعذّر الحفظ في نظام الملفات.',
    refusalUnknown: 'فشلت العملية ولم أتحقق من ناتج صالح، لذلك لم أحفظ شيئاً.',
    refusalDetail: 'تفاصيل تقنية: {detail}',
    noOverwrite: 'لم يُكتب أي ملف.',

    infoTitle: 'معلومات المستند',
    infoDesc: 'عدد الصفحات وحجم كل صفحة ودورانها، والبيانات الوصفية الحالية.',
    infoPages: 'الصفحات: {n}',
    infoMetaTitle: 'العنوان',
    infoAuthor: 'المؤلف',
    infoSubject: 'الموضوع',
    infoKeywords: 'الكلمات المفتاحية',
    infoNone: '—',
    infoPageLine: '{w} × {h} نقطة · دوران {rot}°',
    infoCropLine: 'القص: {w} × {h} عند ({x}, {y})',

    pagesTitle: 'الصفحات',
    pagesDesc: 'اختر الصفحات بالضغط على الصف، أو اكتب نطاقاً ثم «تحديد». رتّب بالسحب أو بالسهمين.',
    rangeLabel: 'نطاق الصفحات',
    rangePlaceholder: '1-3,5,8-',
    rangeApply: 'تحديد',
    selectAll: 'تحديد الكل',
    clearSelection: 'إلغاء التحديد',
    selectedCount: 'المحدد: {n}',
    selectionNone: 'لم تُحدَّد صفحات. اختر صفاً أو اكتب نطاقاً أولاً.',
    rangeErrorSyntax: 'جزء غير مفهوم في النطاق: {token}',
    rangeErrorEmpty: 'اكتب نطاقاً مثل 1-3,5.',
    rangeErrorReversed: 'النطاق معكوس: {from}-{to}.',
    rangeErrorOutOfRange: 'الصفحة {page} خارج المستند ({count} صفحة).',
    pagesLimited: 'القائمة تعرض أول {n} صفحة فقط؛ لما بعدها استخدم صندوق النطاق.',
    moveUp: 'لأعلى',
    moveDown: 'لأسفل',
    dragHint: 'اسحب الصف لتغيير ترتيبه (على الجوال استخدم السهمين).',
    reorderDone: 'أُعيد ترتيب الصفحات.',
    pageN: 'صفحة {n}',

    opsTitle: 'العمليات',
    deleteTitle: 'حذف الصفحات',
    deleteDesc: 'يحذف الصفحات المحددة من النسخة العاملة. لا شيء يُحفظ تلقائياً، وزرّ إعادة التعيين يرجع بالأصل.',
    deleteApply: 'حذف المحدد',
    deleteDone: 'حُذفت {n} صفحة.',
    rotateTitle: 'تدوير الصفحات',
    rotateDesc: 'يدوّر الصفحات المحددة 90 أو 180 أو 270 درجة، والدوران يُخزَّن مع الصفحة.',
    rotate90: '90°',
    rotate180: '180°',
    rotate270: '270°',
    rotateDone: 'دُوّرت {n} صفحة.',
    cropTitle: 'القص (صندوق القص)',
    cropDesc: 'يقص هوامش بالنقاط (72 نقطة = إنش) من كل جهة. القص يخفي المحتوى عند العرض ولا يحذفه.',
    cropTop: 'أعلى',
    cropRight: 'يمين',
    cropBottom: 'أسفل',
    cropLeft: 'يسار',
    cropApply: 'تطبيق القص',
    cropDone: 'قُصّت {n} صفحة.',
    cropErrorNegative: 'الهوامش لا تكون سالبة.',
    cropErrorNoArea: 'الهوامش أكبر من الصفحة: لا تبقى مساحة.',
    watermarkTitle: 'علامة مائية نصية',
    watermarkDesc: 'يرسم النص في وسط كل صفحة محددة بالحجم والشفافية والدوران الذين تختارها، فوق المحتوى الموجود دون تعديله. بلا تحديد يُطبَّق على كل الصفحات، والشفافية الافتراضية 0.15 فتظهر العلامة خفيفة.',
    watermarkText: 'النص',
    watermarkSize: 'حجم الخط',
    watermarkOpacity: 'الشفافية',
    watermarkRotation: 'الدوران',
    watermarkApply: 'إضافة العلامة المائية',
    watermarkDone: 'أُضيفت العلامة المائية إلى {n} صفحة.',
    watermarkErrorText: 'اكتب نص العلامة المائية.',
    watermarkErrorSize: 'حجم الخط بين 4 و400.',
    watermarkErrorOpacity: 'الشفافية أكبر من صفر وحتى 1.',
    watermarkErrorChars: 'حروف غير مدعومة: {chars} — خطوط PDF المدمجة لاتينية فقط.',
    watermarkRotationNote: 'الدوران نسبةً إلى اتجاه الصفحة نفسها.',

    textTitle: 'إضافة نص إلى صفحة',
    textDesc: 'اكتب نصاً جديداً فوق الصفحة: اختر الصفحة والنقطة (من يسار الصفحة ومن أسفلها بالنقاط، 72 نقطة = إنش) والخط القياسي والحجم واللون.',
    textValue: 'النص',
    textPage: 'الصفحة',
    textX: 'من اليسار (نقطة)',
    textY: 'من الأسفل (نقطة)',
    textSize: 'حجم الخط',
    textColor: 'اللون',
    textFont: 'الخط',
    textFontHelvetica: 'Helvetica',
    textFontHelveticaBold: 'Helvetica عريض',
    textFontTimesRoman: 'Times Roman',
    textFontTimesItalic: 'Times مائل',
    textFontCourier: 'Courier',
    textApply: 'إضافة النص',
    textDone: 'أُضيف النص إلى الصفحة {n}.',
    textNote: 'النص يُضاف طبقة جديدة فوق المحتوى، ولا يعدّل نص المستند الأصلي ولا يحذفه.',
    textErrorText: 'اكتب النص أولاً.',
    textErrorSize: 'حجم الخط بين 4 و400.',
    textErrorPoint: 'النقطة خارج الصفحة: أدخل قيمة من يسار الصفحة ومن أسفلها داخل حدودها.',
    textErrorColor: 'اللون غير مفهوم. استخدم قيمة مثل #1a1a1a.',
    textErrorFont: 'اختر خطاً من القائمة.',
    textErrorChars: 'حروف غير مدعومة: {chars} — الخطوط القياسية لاتينية فقط.',
    textErrorPage: 'رقم الصفحة بين 1 و{count}.',

    signTitle: 'إضافة توقيع',
    signDesc: 'توقيع بالكتابة (نص بخط كبير مائل) أو صورة توقيع PNG/JPEG من جهازك، يُرسم فوق الصفحة في المكان الذي تختاره.',
    signText: 'نص التوقيع',
    signApply: 'إضافة التوقيع بالكتابة',
    signDone: 'أُضيف التوقيع بالكتابة إلى الصفحة {n}.',
    signImage: 'صورة التوقيع',
    signImageAdd: 'اختيار صورة (PNG/JPEG)',
    signImageNone: 'لم تُختَر صورة توقيع بعد.',
    signImagePicked: 'صورة التوقيع: {name}',
    signImageWidth: 'عرض الصورة (نقطة)',
    signImageHeight: 'ارتفاع الصورة (نقطة)',
    signImageApply: 'إدراج صورة التوقيع',
    signImageDone: 'أُدرجت صورة التوقيع في الصفحة {n}.',
    signImageRefused: 'صورة التوقيع يجب أن تكون PNG أو JPEG. النوع المقروء: {code}',
    signImageErrorRect: 'مربع الصورة خارج الصفحة أو بلا مساحة: اضبط الإحداثيات والعرض والارتفاع.',

    coverTitle: 'تغطية منطقة (إخفاء)',
    coverDesc: 'يرسم مستطيلاً أو بيضاوياً مملوءاً فوق منطقة من الصفحة، فيخفي ما تحتها عند القراءة.',
    coverNote: 'تنبيه صريح: هذه تغطية/إخفاء وليست حجباً (Redaction). النص الأصلي يبقى داخل الملف ويمكن استخراجه، فإن كان المطلوب إزالة الكلام فعلاً فهذه الأداة لا تكفي.',
    coverShape: 'الشكل',
    coverRect: 'مستطيل',
    coverEllipse: 'بيضاوي',
    coverWidth: 'العرض (نقطة)',
    coverHeight: 'الارتفاع (نقطة)',
    coverApply: 'تغطية المنطقة',
    coverDone: 'غُطّيت منطقة في الصفحة {n}.',
    coverErrorRect: 'العرض والارتفاع أكبر من صفر.',
    coverErrorOutside: 'المنطقة خارج الصفحة: اضبط الإحداثيات.',
    coverErrorPage: 'رقم الصفحة بين 1 و{count}.',

    pageopsTitle: 'صفحة فارغة وتكرار الصفحات',
    pageopsDesc: 'أدرج صفحة فارغة قبل الموضع الذي تختاره (تأخذ مقاس الصفحة المجاورة)، أو كرّر الصفحات المحددة مرة واحدة لكل صفحة.',
    blankAt: 'أدرج قبل الصفحة رقم',
    blankApply: 'إدراج صفحة فارغة',
    blankDone: 'أُدرجت صفحة فارغة عند الموضع {n}.',
    duplicateApply: 'تكرار الصفحات المحددة',
    duplicateDone: 'كُرّرت {n} صفحة بعد نفسها.',
    pageopsNone: 'حدد صفحات أولاً لتكرارها؛ زر «تحديد الكل» يحدد كل الصفحات.',

    formTitle: 'تعبئة النموذج',
    formDesc: 'حقول النص ومربعات الاختيار الموجودة في المستند (AcroForm): عدّل القيم هنا ثم اكتبها في الملف، وتُقرأ مرة أخرى للتأكد قبل أن أقول إنها نجحت.',
    formAppearanceNote: 'تُكتب القيمة مع مظهر الحقل نفسه. وإن كانت بحروف لا ترسمها الخطوط القياسية (العربية مثلاً) فتُكتب القيمة ويُطلب من القارئ بناء المظهر (NeedAppearances)، ويعرضها القارئ الذي يحترم هذا الطلب.',
    formCount: 'حقول قابلة للتعبئة: {n}',
    formNone: 'هذا المستند لا يحتوي على نموذج تفاعلي (AcroForm)، فلا توجد حقول لتعبئتها.',
    formNoneFillable: 'النموذج موجود، لكن لا يوجد فيه حقول نص أو مربعات اختيار قابلة للتعبئة.',
    formOtherHint: 'حقول أخرى غير مدعومة هنا (أزرار أو قوائم أو توقيعات): {n}',
    formReadOnly: 'للقراءة فقط، لن تُكتب.',
    formCheckbox: 'مربع اختيار',
    formApply: 'كتابة القيم في الملف',
    formDone: 'كُتبت {n} قيمة في النموذج وتُحقّقت.',
    formError: 'تعذّرت قراءة النموذج: {message}',

    metadataTitle: 'البيانات الوصفية',
    metadataDesc: 'تُحفظ الحقول كما تظهر هنا؛ امسح الحقل لحذف قيمته. نص المستند نفسه لا يُعدَّل.',
    metadataApply: 'حفظ البيانات',
    metadataDone: 'حُفظت البيانات الوصفية.',
    keywordsHint: 'افصل الكلمات بفاصلة أو مسافة.',
    splitTitle: 'تقسيم / استخراج',
    splitDesc: 'ملف جديد لكل نطاق تكتبه: نطاق واحد = ملف واحد، ونطاقات متعددة = عدة ملفات.',
    splitApply: 'استخراج',
    splitDone: 'أُنشئ ملف: {path}',
    splitDoneMany: 'أُنشئت {n} ملفات.',
    mergeTitle: 'دمج ملفات PDF',
    mergeDesc: 'أضف ملفات من جهازك إلى ترتيب الدمج، ولكل ملف نطاق. الناتج يصبح النسخة العاملة.',
    mergeAdd: 'إضافة ملفات',
    mergeApply: 'دمج',
    mergeDone: 'دُمج {n} مصدراً في مستند من {pages} صفحة.',
    mergeEmpty: 'أضف ملفاً واحداً على الأقل غير المستند المفتوح.',
    mergeOpenDoc: 'المستند المفتوح',
    sourcePages: '{name} · {n} صفحة',
    sourceRangeLabel: 'نطاق هذا الملف',
    remove: 'إزالة',
    imagesTitle: 'صور ← PDF',
    imagesDesc: 'كل صورة في صفحة، PNG أو JPEG فقط، مع اختيار حجم الصفحة.',
    imagesAdd: 'إضافة صور',
    imagesPageSize: 'حجم الصفحة',
    imagesA4: 'A4',
    imagesLetter: 'Letter',
    imagesFit: 'مقاس الصورة',
    imagesApply: 'إنشاء PDF من الصور',
    imagesEmpty: 'أضف صورة واحدة على الأقل.',
    imagesDone: 'أُنشئ مستند من {n} صورة: {pages} صفحة.',
    imagesRefused: 'تُخطّيت {name}: {code}',
    opFailed: 'لم تُنفَّذ العملية: {message}',
    opVerified: 'تُحقّق من الناتج: {summary}',

    saveTitle: 'الحفظ',
    saveDesc: 'الحفظ الافتراضي ينشئ ملفاً جديداً بجانب الأصل ولا يلمسه. الاستبدال يحتاج تأكيداً ويكتب نسخة .bak واحدة أولاً.',
    saveTarget: 'المسار: {path}',
    saveCopy: 'حفظ كنسخة جديدة',
    saveCopySuffix: '-copy',
    saveOverwrite: 'استبدال الأصل',
    saveOverwriteConfirm: 'تأكيد الاستبدال (.bak أولاً)',
    saveOverwriteWarn: 'سيُستبدل الأصل «{name}» بالنسخة العاملة، بعد كتابة نسخة احتياطية واحدة باسم {bak}.',
    cancel: 'إلغاء',
    saveDoneCopy: 'حُفظت نسخة جديدة: {path}',
    saveDoneOverwrite: 'استُبدل الأصل، والنسخة الاحتياطية: {path}',
    saveNoBytes: 'لا توجد بيانات للحفظ (صفر بايت).',
    saveFailed: 'تعذّر الحفظ.',

    limitsTitle: 'حدود صريحة',
    limitTextEdit: 'لا تعديل لنص موجود داخل المستند ولا حذفه: يمكن إضافة نص جديد فوقه أو تغطيته، والنص الأصلي يبقى في الملف.',
    limitNoRedaction: 'لا حجب حقيقي (Redaction): التغطية ترسم فوق المحتوى ولا تحذف النص من الملف.',
    limitNoOcr: 'لا OCR: الصفحات الممسوحة تبقى صوراً ولا يُستخرج منها نص.',
    limitNoSign: 'لا توقيع رقمي ولا ختم زمني، ولا تحقّق من توقيع موجود.',
    limitNoForms: 'لا إنشاء نماذج جديدة ولا حذف حقول: تُعبّأ الحقول النصية ومربعات الاختيار الموجودة فقط.',
    limitNoRaster: 'لا تحويل للصفحات إلى صور، فلا معاينة مصغّرة لكل صفحة، لأن المكتبة لا ترسم الصفحات.',
    limitNoFonts: 'الكتابة بالخطوط القياسية المدمجة (لاتينية فقط): لا يمكن إدراج خط عربي ولا كتابة نص عربي في الملف.',
    limitEncrypted: 'الملفات المحمية بكلمة مرور تُرفض ولا تُفتح.',
    limitNoPassword: 'قفل PDF بكلمة مرور غير مدعوم محلياً بلا مكتبة تشفير ثقيلة: مكتبة pdf-lib لا تشفّر ولا تفكّ التشفير، ولن أخترع قفلاً غير حقيقي.',
    limitQuality: 'الصور تُدرج كما هي: لا ضغط ولا تصغير.',
    limitLarge: 'الملف يُقرأ كاملاً في الذاكرة، فقد يبطؤ النظام مع الملفات الكبيرة.',
    limitList: 'قائمة الصفحات تعرض أول {n} صفحة فقط.',
  },
  en: {
    title: 'PDF Documents',
    badge: 'PDF editor',
    tabView: 'View',
    tabEdit: 'Edit',
    loading: 'Opening the file…',
    readError: 'Could not read the file from the file system.',
    noFile: 'Open a PDF from the Files app and it shows here.',
    pagesCount: '{n} pages',
    pageCountOne: '1 page',
    sizeLabel: 'Size: {size}',
    modified: 'Modified',
    reset: 'Reset to the opened file',
    resetDone: 'Back to the opened file.',
    busy: 'Working…',

    viewNoViewer: 'This browser cannot show a PDF inside the system. Download the result or open it in a tab.',
    openInTab: 'Open in a tab',
    download: 'Download the result',
    print: 'Print',
    printReady: 'The print dialog for this file is open.',
    printNoViewer: 'This browser cannot show a PDF inside the system, so it cannot print it either. Download the file and print it outside.',
    printFailed: 'The print dialog could not be opened.',
    printNoBytes: 'There is no file to print.',
    previewNote: 'The preview shows the working copy: after the in-memory edits and before saving.',

    refusalTitle: 'Could not open this file',
    refusalEmpty: 'The file is empty (zero bytes).',
    refusalNotPdf: 'This is not a PDF: it has no %PDF- header.',
    refusalEncrypted: 'The file is password-protected (encrypted) and pdf-lib refuses to open it. Remove the protection with another program and try again.',
    refusalCorrupt: 'This looks like a PDF but it could not be parsed: it may be damaged or truncated.',
    refusalImageUnsupported: 'This image is neither PNG nor JPEG, and only those two can be embedded.',
    refusalImageBroken: 'This image could not be read: its signature is right but its data is damaged or truncated.',
    refusalTextNotRenderable: 'The text holds characters the built-in PDF fonts cannot draw (Arabic, for example). Write the text in Latin letters, or add the font outside the system.',
    refusalNoForm: 'This document has no interactive form (AcroForm) to write values into.',
    refusalEmptyResult: 'This operation would leave zero pages, and I will not write an empty document.',
    refusalOutsideHome: 'Saving outside /home/user is not allowed.',
    refusalWriteFailed: 'Could not write to the file system.',
    refusalUnknown: 'The operation failed and I could not verify a valid result, so nothing was saved.',
    refusalDetail: 'Technical detail: {detail}',
    noOverwrite: 'No file was written.',

    infoTitle: 'Document info',
    infoDesc: 'The page count, each page’s size and rotation, and the current metadata.',
    infoPages: 'Pages: {n}',
    infoMetaTitle: 'Title',
    infoAuthor: 'Author',
    infoSubject: 'Subject',
    infoKeywords: 'Keywords',
    infoNone: '—',
    infoPageLine: '{w} × {h} pt · rotation {rot}°',
    infoCropLine: 'Crop: {w} × {h} at ({x}, {y})',

    pagesTitle: 'Pages',
    pagesDesc: 'Tap a row to select a page, or type a range and press “Select”. Reorder by dragging or with the arrows.',
    rangeLabel: 'Page range',
    rangePlaceholder: '1-3,5,8-',
    rangeApply: 'Select',
    selectAll: 'Select all',
    clearSelection: 'Clear selection',
    selectedCount: 'Selected: {n}',
    selectionNone: 'No pages selected. Pick a row or type a range first.',
    rangeErrorSyntax: 'Unreadable part of the range: {token}',
    rangeErrorEmpty: 'Type a range such as 1-3,5.',
    rangeErrorReversed: 'The range runs backwards: {from}-{to}.',
    rangeErrorOutOfRange: 'Page {page} is outside the document ({count} pages).',
    pagesLimited: 'The list shows only the first {n} pages; use the range box beyond that.',
    moveUp: 'Move up',
    moveDown: 'Move down',
    dragHint: 'Drag a row to reorder it (on mobile use the arrows).',
    reorderDone: 'Pages reordered.',
    pageN: 'Page {n}',

    opsTitle: 'Operations',
    deleteTitle: 'Delete pages',
    deleteDesc: 'Removes the selected pages from the working copy. Nothing is saved automatically, and reset brings the original back.',
    deleteApply: 'Delete selected',
    deleteDone: 'Deleted {n} pages.',
    rotateTitle: 'Rotate pages',
    rotateDesc: 'Turns the selected pages by 90, 180 or 270 degrees; the rotation is stored with the page.',
    rotate90: '90°',
    rotate180: '180°',
    rotate270: '270°',
    rotateDone: 'Rotated {n} pages.',
    cropTitle: 'Crop (crop box)',
    cropDesc: 'Cuts margins in points (72 pt = 1 inch) from each side. Cropping hides the content when displayed; it does not delete it.',
    cropTop: 'Top',
    cropRight: 'Right',
    cropBottom: 'Bottom',
    cropLeft: 'Left',
    cropApply: 'Apply crop',
    cropDone: 'Cropped {n} pages.',
    cropErrorNegative: 'Margins cannot be negative.',
    cropErrorNoArea: 'The margins are larger than the page: no area is left.',
    watermarkTitle: 'Text watermark',
    watermarkDesc: 'Draws the text at the centre of every selected page with the size, opacity and rotation you choose, over the existing content, never editing it. With nothing selected it applies to every page, and the default opacity 0.15 keeps the mark light.',
    watermarkText: 'Text',
    watermarkSize: 'Font size',
    watermarkOpacity: 'Opacity',
    watermarkRotation: 'Rotation',
    watermarkApply: 'Add watermark',
    watermarkDone: 'Watermark added to {n} pages.',
    watermarkErrorText: 'Type the watermark text.',
    watermarkErrorSize: 'The font size must be between 4 and 400.',
    watermarkErrorOpacity: 'Opacity must be above 0 and at most 1.',
    watermarkErrorChars: 'Unsupported characters: {chars} — the built-in PDF fonts are Latin only.',
    watermarkRotationNote: 'Rotation is relative to the page’s own orientation.',

    textTitle: 'Add text to a page',
    textDesc: 'Write new text over the page: choose the page and the point (in points from the page’s left edge and from its bottom, 72 pt = 1 inch), the standard font, the size and the colour.',
    textValue: 'Text',
    textPage: 'Page',
    textX: 'From the left (pt)',
    textY: 'From the bottom (pt)',
    textSize: 'Font size',
    textColor: 'Colour',
    textFont: 'Font',
    textFontHelvetica: 'Helvetica',
    textFontHelveticaBold: 'Helvetica Bold',
    textFontTimesRoman: 'Times Roman',
    textFontTimesItalic: 'Times Italic',
    textFontCourier: 'Courier',
    textApply: 'Add the text',
    textDone: 'Text added to page {n}.',
    textNote: 'The text is added as a new layer over the content; it does not edit or delete the document’s own text.',
    textErrorText: 'Type the text first.',
    textErrorSize: 'The font size must be between 4 and 400.',
    textErrorPoint: 'The point is outside the page: give a position within the page’s left and bottom edges.',
    textErrorColor: 'That colour cannot be read. Use a value such as #1a1a1a.',
    textErrorFont: 'Choose one of the listed fonts.',
    textErrorChars: 'Unsupported characters: {chars} — the standard fonts are Latin only.',
    textErrorPage: 'The page number must be between 1 and {count}.',

    signTitle: 'Add a signature',
    signDesc: 'A typed signature (large italic text) or a PNG/JPEG signature picture from your device, drawn over the page where you choose.',
    signText: 'Signature text',
    signApply: 'Add the typed signature',
    signDone: 'The typed signature was added to page {n}.',
    signImage: 'Signature picture',
    signImageAdd: 'Choose a picture (PNG/JPEG)',
    signImageNone: 'No signature picture has been chosen yet.',
    signImagePicked: 'Signature picture: {name}',
    signImageWidth: 'Picture width (pt)',
    signImageHeight: 'Picture height (pt)',
    signImageApply: 'Insert the signature picture',
    signImageDone: 'The signature picture was inserted on page {n}.',
    signImageRefused: 'The signature picture must be a PNG or JPEG. The type read was: {code}',
    signImageErrorRect: 'The picture box is outside the page or has no area: adjust the coordinates, width and height.',

    coverTitle: 'Cover a region (hiding)',
    coverDesc: 'Draws a filled rectangle or ellipse over a region of a page, hiding what is under it when the page is read.',
    coverNote: 'Stated plainly: this is covering/hiding, NOT redaction. The original text stays inside the file and can still be extracted, so if the goal is to really remove the words, this tool is not enough.',
    coverShape: 'Shape',
    coverRect: 'Rectangle',
    coverEllipse: 'Ellipse',
    coverWidth: 'Width (pt)',
    coverHeight: 'Height (pt)',
    coverApply: 'Cover the region',
    coverDone: 'Covered a region on page {n}.',
    coverErrorRect: 'The width and height must be greater than zero.',
    coverErrorOutside: 'The region is outside the page: adjust the coordinates.',
    coverErrorPage: 'The page number must be between 1 and {count}.',

    pageopsTitle: 'Blank page and duplicates',
    pageopsDesc: 'Insert a blank page before the position you choose (it takes the neighbouring page’s size), or duplicate the selected pages once each.',
    blankAt: 'Insert before page number',
    blankApply: 'Insert a blank page',
    blankDone: 'A blank page was inserted at position {n}.',
    duplicateApply: 'Duplicate the selected pages',
    duplicateDone: 'Duplicated {n} pages next to themselves.',
    pageopsNone: 'Select pages first to duplicate them; “Select all” selects every page.',

    formTitle: 'Fill the form',
    formDesc: 'The text fields and checkboxes the document already carries (AcroForm): edit the values here and write them into the file; they are read back before I say it worked.',
    formAppearanceNote: 'The value is written together with the field’s own appearance. If it holds characters the standard fonts cannot draw (Arabic, for example) the value is still written and the reader is asked to build the appearance (NeedAppearances), which readers that honour it will show.',
    formCount: 'Fillable fields: {n}',
    formNone: 'This document has no interactive form (AcroForm), so there are no fields to fill.',
    formNoneFillable: 'A form exists, but it holds no fillable text fields or checkboxes.',
    formOtherHint: 'Other fields that are not supported here (buttons, lists, signatures): {n}',
    formReadOnly: 'Read-only, it will not be written.',
    formCheckbox: 'Checkbox',
    formApply: 'Write the values into the file',
    formDone: 'Wrote {n} form values and verified them.',
    formError: 'The form could not be read: {message}',

    metadataTitle: 'Metadata',
    metadataDesc: 'The fields are saved exactly as shown here; clear a field to delete its value. The document’s own text is not edited.',
    metadataApply: 'Save metadata',
    metadataDone: 'Metadata saved.',
    keywordsHint: 'Separate keywords with a comma or a space.',
    splitTitle: 'Split / extract',
    splitDesc: 'A new file for every range you type: one range gives one file, several ranges give several files.',
    splitApply: 'Extract',
    splitDone: 'Created: {path}',
    splitDoneMany: 'Created {n} files.',
    mergeTitle: 'Merge PDFs',
    mergeDesc: 'Add files from your device to the merge order, with a range for each. The result becomes the working copy.',
    mergeAdd: 'Add files',
    mergeApply: 'Merge',
    mergeDone: 'Merged {n} sources into a {pages}-page document.',
    mergeEmpty: 'Add at least one file besides the open document.',
    mergeOpenDoc: 'The open document',
    sourcePages: '{name} · {n} pages',
    sourceRangeLabel: 'This file’s range',
    remove: 'Remove',
    imagesTitle: 'Images → PDF',
    imagesDesc: 'One image per page, PNG or JPEG only, with a choice of page size.',
    imagesAdd: 'Add images',
    imagesPageSize: 'Page size',
    imagesA4: 'A4',
    imagesLetter: 'Letter',
    imagesFit: 'Fit to image',
    imagesApply: 'Create a PDF from the images',
    imagesEmpty: 'Add at least one image.',
    imagesDone: 'Created a document from {n} images: {pages} pages.',
    imagesRefused: 'Skipped {name}: {code}',
    opFailed: 'The operation did not run: {message}',
    opVerified: 'Output verified: {summary}',

    saveTitle: 'Save',
    saveDesc: 'The default save creates a new file beside the original and never touches it. Replacing needs confirmation and writes one .bak copy first.',
    saveTarget: 'Target: {path}',
    saveCopy: 'Save as a new copy',
    saveCopySuffix: '-copy',
    saveOverwrite: 'Replace the original',
    saveOverwriteConfirm: 'Confirm replace (.bak first)',
    saveOverwriteWarn: 'The original “{name}” will be replaced by the working copy, after one backup is written as {bak}.',
    cancel: 'Cancel',
    saveDoneCopy: 'Saved a new copy: {path}',
    saveDoneOverwrite: 'The original was replaced; the backup is: {path}',
    saveNoBytes: 'There is nothing to save (zero bytes).',
    saveFailed: 'Saving failed.',

    limitsTitle: 'Honest limits',
    limitTextEdit: 'No editing or deleting of text already in the document: new text can be added over it or the region can be covered, and the original text stays in the file.',
    limitNoRedaction: 'No true redaction: covering draws over the content and does not remove the text from the file.',
    limitNoOcr: 'No OCR: scanned pages stay images and no text is extracted from them.',
    limitNoSign: 'No digital signatures and no timestamps, and existing signatures are not verified.',
    limitNoForms: 'No creating new forms and no deleting fields: only the existing text fields and checkboxes are filled.',
    limitNoRaster: 'No page rasterising, so no per-page thumbnail, because the library does not render pages.',
    limitNoFonts: 'Drawing uses the built-in standard (Latin-only) fonts: an Arabic font cannot be embedded and Arabic text cannot be written into the file.',
    limitEncrypted: 'Password-protected files are refused, not opened.',
    limitNoPassword: 'Locking a PDF with a password is not supported locally without a heavy encryption library: pdf-lib neither encrypts nor decrypts, and I will not invent a lock that is not real.',
    limitQuality: 'Images are embedded as they are: no recompression and no downscaling.',
    limitLarge: 'The file is read fully into memory, which can slow the system with large files.',
    limitList: 'The page list shows only the first {n} pages.',
  },
});
