import { defineStrings } from '../../kernel/i18n';

/**
 * Every visible string of the PDF app, in Arabic and English.
 * The two blocks must hold exactly the same keys — a repo-wide parity test and the
 * app's own `strings.test.ts` both fail otherwise.
 */
defineStrings('pdf', {
  ar: {
    title: 'مستندات PDF',
    loading: 'جارٍ فتح الملف…',
    readError: 'تعذّرت قراءة الملف من نظام الملفات.',
    pagesCount: '{n} صفحة',
    pageCountOne: 'صفحة واحدة',
    sizeLabel: 'الحجم: {size}',
    modified: 'مُعدّل',
    reset: 'إعادة تعيين إلى الملف الأصلي',
    resetDone: 'رجعنا إلى الملف الأصلي.',
    busy: 'جارٍ العمل…',

    viewNoViewer: 'تعذّر تحميل محرّك عرض الصفحات. العمليات والحفظ والتنزيل تعمل كالمعتاد.',
    openInTab: 'فتح في تبويب',
    download: 'تنزيل',
    print: 'طباعة',
    printReady: 'فُتحت نافذة طباعة هذا الملف.',
    printNoViewer: 'هذا المتصفح لا يعرض PDF داخل النظام، فلا نافذة طباعة له. نزّل الملف واطبعه من الخارج.',
    printFailed: 'تعذّر فتح نافذة الطباعة.',
    printNoBytes: 'لا يوجد ملف للطباعة.',

    refusalTitle: 'تعذّر فتح هذا الملف',
    refusalEmpty: 'الملف فارغ (صفر بايت).',
    refusalNotPdf: 'هذا ليس ملف PDF: لا توجد ترويسة %PDF- في أوله.',
    refusalEncrypted: 'الملف محمي بكلمة مرور (مشفّر)، ومكتبة pdf-lib ترفض فتحه. أزل الحماية ببرنامج آخر ثم أعد المحاولة.',
    refusalCorrupt: 'يبدو ملف PDF لكن قراءته فشلت: قد يكون تالفاً أو ناقصاً.',
    refusalImageUnsupported: 'هذه الصورة ليست PNG ولا JPEG، ولا يمكن إدراج غير هذين النوعين.',
    refusalImageBroken: 'تعذّرت قراءة هذه الصورة: ترويستها صحيحة لكن بياناتها تالفة أو ناقصة.',
    refusalTextNotRenderable: 'في النص حروف لا تستطيع خطوط PDF المدمجة رسمها (العربية مثلاً). اكتب النص بحروف لاتينية، أو أضف الخط خارج النظام.',
    refusalNoForm: 'هذا المستند لا يحتوي على نموذج تفاعلي (AcroForm) لكتابة القيم فيه.',
    refusalEmptyResult: 'هذه العملية تترك صفر صفحات، ولن أكتب مستنداً فارغاً.',
    refusalOutsideHome: 'الحفظ خارج /home/user غير مسموح.',
    refusalWriteFailed: 'تعذّر الحفظ في نظام الملفات.',
    refusalUnknown: 'فشلت العملية ولم أتحقق من ناتج صالح، لذلك لم أحفظ شيئاً.',
    refusalDetail: 'تفاصيل تقنية: {detail}',
    noOverwrite: 'لم يُكتب أي ملف.',

    infoTitle: 'معلومات المستند',
    infoDesc: 'عدد الصفحات وحجم كل صفحة ودورانها، والبيانات الوصفية الحالية.',
    infoPages: 'الصفحات: {n}',
    infoMetaTitle: 'العنوان',
    infoAuthor: 'المؤلف',
    infoSubject: 'الموضوع',
    infoKeywords: 'الكلمات المفتاحية',
    infoNone: '—',
    infoPageLine: '{w} × {h} نقطة · دوران {rot}°',
    infoCropLine: 'القص: {w} × {h} عند ({x}, {y})',

    pagesTitle: 'الصفحات',
    pagesDesc: 'اختر الصفحات بالضغط على الصف، أو اكتب نطاقاً ثم «تحديد». رتّب بالسحب أو بالسهمين.',
    rangeLabel: 'نطاق الصفحات',
    rangePlaceholder: '1-3,5,8-',
    rangeApply: 'تحديد',
    selectAll: 'تحديد الكل',
    clearSelection: 'إلغاء التحديد',
    selectedCount: 'المحدد: {n}',
    selectionNone: 'لم تُحدَّد صفحات. اختر صفاً أو اكتب نطاقاً أولاً.',
    rangeErrorSyntax: 'جزء غير مفهوم في النطاق: {token}',
    rangeErrorEmpty: 'اكتب نطاقاً مثل 1-3,5.',
    rangeErrorReversed: 'النطاق معكوس: {from}-{to}.',
    rangeErrorOutOfRange: 'الصفحة {page} خارج المستند ({count} صفحة).',
    pagesLimited: 'القائمة تعرض أول {n} صفحة فقط؛ لما بعدها استخدم صندوق النطاق.',
    moveUp: 'لأعلى',
    moveDown: 'لأسفل',
    dragHint: 'اسحب الصف لتغيير ترتيبه (على الجوال استخدم السهمين).',
    reorderDone: 'أُعيد ترتيب الصفحات.',
    pageN: 'صفحة {n}',

    opsTitle: 'العمليات',
    deleteTitle: 'حذف الصفحات',
    deleteDesc: 'يحذف الصفحات المحددة من النسخة العاملة. لا شيء يُحفظ تلقائياً، وزرّ إعادة التعيين يرجع بالأصل.',
    deleteApply: 'حذف المحدد',
    deleteDone: 'حُذفت {n} صفحة.',
    rotateTitle: 'تدوير الصفحات',
    rotateDesc: 'يدوّر الصفحات المحددة 90 أو 180 أو 270 درجة، والدوران يُخزَّن مع الصفحة.',
    rotate90: '90°',
    rotate180: '180°',
    rotate270: '270°',
    rotateDone: 'دُوّرت {n} صفحة.',
    cropTitle: 'القص (صندوق القص)',
    cropDesc: 'يقص هوامش بالنقاط (72 نقطة = إنش) من كل جهة. القص يخفي المحتوى عند العرض ولا يحذفه.',
    cropTop: 'أعلى',
    cropRight: 'يمين',
    cropBottom: 'أسفل',
    cropLeft: 'يسار',
    cropApply: 'تطبيق القص',
    cropDone: 'قُصّت {n} صفحة.',
    cropErrorNegative: 'الهوامش لا تكون سالبة.',
    cropErrorNoArea: 'الهوامش أكبر من الصفحة: لا تبقى مساحة.',
    watermarkTitle: 'علامة مائية نصية',
    watermarkDesc: 'يرسم النص في وسط كل صفحة محددة بالحجم والشفافية والدوران الذين تختارها، فوق المحتوى الموجود دون تعديله. بلا تحديد يُطبَّق على كل الصفحات، والشفافية الافتراضية 0.15 فتظهر العلامة خفيفة.',
    watermarkText: 'النص',
    watermarkSize: 'حجم الخط',
    watermarkOpacity: 'الشفافية',
    watermarkRotation: 'الدوران',
    watermarkApply: 'إضافة العلامة المائية',
    watermarkDone: 'أُضيفت العلامة المائية إلى {n} صفحة.',
    watermarkErrorText: 'اكتب نص العلامة المائية.',
    watermarkErrorSize: 'حجم الخط بين 4 و400.',
    watermarkErrorOpacity: 'الشفافية أكبر من صفر وحتى 1.',
    watermarkErrorChars: 'حروف غير مدعومة: {chars} — خطوط PDF المدمجة لاتينية فقط.',
    watermarkRotationNote: 'الدوران نسبةً إلى اتجاه الصفحة نفسها.',

    textTitle: 'إضافة نص إلى صفحة',
    textDesc: 'اكتب نصاً جديداً فوق الصفحة: اختر الصفحة والنقطة (من يسار الصفحة ومن أسفلها بالنقاط، 72 نقطة = إنش) والخط القياسي والحجم واللون.',
    textValue: 'النص',
    textPage: 'الصفحة',
    textX: 'من اليسار (نقطة)',
    textY: 'من الأسفل (نقطة)',
    textSize: 'حجم الخط',
    textColor: 'اللون',
    textFont: 'الخط',
    textFontHelvetica: 'Helvetica',
    textFontHelveticaBold: 'Helvetica عريض',
    textFontTimesRoman: 'Times Roman',
    textFontTimesItalic: 'Times مائل',
    textFontCourier: 'Courier',
    textApply: 'إضافة النص',
    textDone: 'أُضيف النص إلى الصفحة {n}.',
    textNote: 'النص يُضاف طبقة جديدة فوق المحتوى، ولا يعدّل نص المستند الأصلي ولا يحذفه.',
    textErrorText: 'اكتب النص أولاً.',
    textErrorSize: 'حجم الخط بين 4 و400.',
    textErrorPoint: 'النقطة خارج الصفحة: أدخل قيمة من يسار الصفحة ومن أسفلها داخل حدودها.',
    textErrorColor: 'اللون غير مفهوم. استخدم قيمة مثل #1a1a1a.',
    textErrorFont: 'اختر خطاً من القائمة.',
    textErrorChars: 'حروف غير مدعومة: {chars} — الخطوط القياسية لاتينية فقط.',
    textErrorPage: 'رقم الصفحة بين 1 و{count}.',

    signTitle: 'إضافة توقيع',
    signDesc: 'توقيع بالكتابة (نص بخط كبير مائل) أو صورة توقيع PNG/JPEG من جهازك، يُرسم فوق الصفحة في المكان الذي تختاره.',
    signText: 'نص التوقيع',
    signApply: 'إضافة التوقيع بالكتابة',
    signDone: 'أُضيف التوقيع بالكتابة إلى الصفحة {n}.',
    signImage: 'صورة التوقيع',
    signImageAdd: 'اختيار صورة (PNG/JPEG)',
    signImageNone: 'لم تُختَر صورة توقيع بعد.',
    signImagePicked: 'صورة التوقيع: {name}',
    signImageWidth: 'عرض الصورة (نقطة)',
    signImageHeight: 'ارتفاع الصورة (نقطة)',
    signImageApply: 'إدراج صورة التوقيع',
    signImageDone: 'أُدرجت صورة التوقيع في الصفحة {n}.',
    signImageRefused: 'صورة التوقيع يجب أن تكون PNG أو JPEG. النوع المقروء: {code}',
    signImageErrorRect: 'مربع الصورة خارج الصفحة أو بلا مساحة: اضبط الإحداثيات والعرض والارتفاع.',

    coverTitle: 'تغطية منطقة (إخفاء)',
    coverDesc: 'يرسم مستطيلاً أو بيضاوياً مملوءاً فوق منطقة من الصفحة، فيخفي ما تحتها عند القراءة.',
    coverNote: 'تنبيه صريح: هذه تغطية/إخفاء وليست حجباً (Redaction). النص الأصلي يبقى داخل الملف ويمكن استخراجه، فإن كان المطلوب إزالة الكلام فعلاً فهذه الأداة لا تكفي.',
    coverShape: 'الشكل',
    coverRect: 'مستطيل',
    coverEllipse: 'بيضاوي',
    coverWidth: 'العرض (نقطة)',
    coverHeight: 'الارتفاع (نقطة)',
    coverApply: 'تغطية المنطقة',
    coverDone: 'غُطّيت منطقة في الصفحة {n}.',
    coverErrorRect: 'العرض والارتفاع أكبر من صفر.',
    coverErrorOutside: 'المنطقة خارج الصفحة: اضبط الإحداثيات.',
    coverErrorPage: 'رقم الصفحة بين 1 و{count}.',

    pageopsTitle: 'صفحة فارغة وتكرار الصفحات',
    pageopsDesc: 'أدرج صفحة فارغة قبل الموضع الذي تختاره (تأخذ مقاس الصفحة المجاورة)، أو كرّر الصفحات المحددة مرة واحدة لكل صفحة.',
    blankAt: 'أدرج قبل الصفحة رقم',
    blankApply: 'إدراج صفحة فارغة',
    blankDone: 'أُدرجت صفحة فارغة عند الموضع {n}.',
    duplicateApply: 'تكرار الصفحات المحددة',
    duplicateDone: 'كُرّرت {n} صفحة بعد نفسها.',
    pageopsNone: 'حدد صفحات أولاً لتكرارها؛ زر «تحديد الكل» يحدد كل الصفحات.',

    formTitle: 'تعبئة النموذج',
    formDesc: 'حقول النص ومربعات الاختيار الموجودة في المستند (AcroForm): عدّل القيم هنا ثم اكتبها في الملف، وتُقرأ مرة أخرى للتأكد قبل أن أقول إنها نجحت.',
    formAppearanceNote: 'تُكتب القيمة مع مظهر الحقل نفسه. وإن كانت بحروف لا ترسمها الخطوط القياسية (العربية مثلاً) فتُكتب القيمة ويُطلب من القارئ بناء المظهر (NeedAppearances)، ويعرضها القارئ الذي يحترم هذا الطلب.',
    formCount: 'حقول قابلة للتعبئة: {n}',
    formNone: 'هذا المستند لا يحتوي على نموذج تفاعلي (AcroForm)، فلا توجد حقول لتعبئتها.',
    formNoneFillable: 'النموذج موجود، لكن لا يوجد فيه حقول نص أو مربعات اختيار قابلة للتعبئة.',
    formOtherHint: 'حقول أخرى غير مدعومة هنا (أزرار أو قوائم أو توقيعات): {n}',
    formReadOnly: 'للقراءة فقط، لن تُكتب.',
    formCheckbox: 'مربع اختيار',
    formApply: 'كتابة القيم في الملف',
    formDone: 'كُتبت {n} قيمة في النموذج وتُحقّقت.',
    formError: 'تعذّرت قراءة النموذج: {message}',

    metadataTitle: 'البيانات الوصفية',
    metadataDesc: 'تُحفظ الحقول كما تظهر هنا؛ امسح الحقل لحذف قيمته. نص المستند نفسه لا يُعدَّل.',
    metadataApply: 'حفظ البيانات',
    metadataDone: 'حُفظت البيانات الوصفية.',
    keywordsHint: 'افصل الكلمات بفاصلة أو مسافة.',
    splitTitle: 'تقسيم / استخراج',
    splitDesc: 'ملف جديد لكل نطاق تكتبه: نطاق واحد = ملف واحد، ونطاقات متعددة = عدة ملفات.',
    splitApply: 'استخراج',
    splitDone: 'أُنشئ ملف: {path}',
    splitDoneMany: 'أُنشئت {n} ملفات.',
    mergeTitle: 'دمج ملفات PDF',
    mergeDesc: 'أضف ملفات من جهازك إلى ترتيب الدمج، ولكل ملف نطاق. الناتج يصبح النسخة العاملة.',
    mergeAdd: 'إضافة ملفات',
    mergeApply: 'دمج',
    mergeDone: 'دُمج {n} مصدراً في مستند من {pages} صفحة.',
    mergeEmpty: 'أضف ملفاً واحداً على الأقل غير المستند المفتوح.',
    mergeOpenDoc: 'المستند المفتوح',
    sourcePages: '{name} · {n} صفحة',
    sourceRangeLabel: 'نطاق هذا الملف',
    remove: 'إزالة',
    imagesTitle: 'صور ← PDF',
    imagesDesc: 'كل صورة في صفحة، PNG أو JPEG فقط، مع اختيار حجم الصفحة.',
    imagesAdd: 'إضافة صور',
    imagesPageSize: 'حجم الصفحة',
    imagesA4: 'A4',
    imagesLetter: 'Letter',
    imagesFit: 'مقاس الصورة',
    imagesApply: 'إنشاء PDF من الصور',
    imagesEmpty: 'أضف صورة واحدة على الأقل.',
    imagesDone: 'أُنشئ مستند من {n} صورة: {pages} صفحة.',
    imagesRefused: 'تُخطّيت {name}: {code}',
    opFailed: 'لم تُنفَّذ العملية: {message}',
    opVerified: 'تُحقّق من الناتج.',

    saveTitle: 'الحفظ',
    saveDesc: 'الحفظ الافتراضي ينشئ ملفاً جديداً بجانب الأصل ولا يلمسه. الاستبدال يحتاج تأكيداً ويكتب نسخة .bak واحدة أولاً.',
    saveTarget: 'المسار: {path}',
    saveCopy: 'حفظ كنسخة جديدة',
    saveCopySuffix: '-copy',
    saveOverwrite: 'استبدال الأصل',
    saveOverwriteConfirm: 'تأكيد الاستبدال (.bak أولاً)',
    saveOverwriteWarn: 'سيُستبدل الأصل «{name}» بالنسخة العاملة، بعد كتابة نسخة احتياطية واحدة باسم {bak}.',
    cancel: 'إلغاء',
    saveDoneCopy: 'حُفظت نسخة جديدة: {path}',
    saveDoneOverwrite: 'استُبدل الأصل، والنسخة الاحتياطية: {path}',
    saveNoBytes: 'لا توجد بيانات للحفظ (صفر بايت).',
    saveFailed: 'تعذّر الحفظ.',

    limitsTitle: 'حدود صريحة',
    limitTextEdit: 'لا تعديل لنص موجود داخل المستند ولا حذفه: يمكن إضافة نص جديد فوقه أو تغطيته، والنص الأصلي يبقى في الملف.',
    limitNoRedaction: 'لا حجب حقيقي (Redaction): التغطية ترسم فوق المحتوى ولا تحذف النص من الملف.',
    limitNoOcr: 'لا OCR: الصفحات الممسوحة تبقى صوراً ولا يُستخرج منها نص.',
    limitNoSign: 'لا توقيع رقمي ولا ختم زمني، ولا تحقّق من توقيع موجود.',
    limitNoForms: 'لا إنشاء نماذج جديدة ولا حذف حقول: تُعبّأ الحقول النصية ومربعات الاختيار الموجودة فقط.',
    limitNoRaster: 'الصفحات تُرسم للعرض فقط: لا تصدير للصفحات كملفات صور.',
    limitNoFonts: 'النص العربي يُكتب بخط عربي مضمّن (Noto Naskh Arabic) مع تشكيل الحروف واتجاه الكتابة؛ العلامة المائية في لوحتها القديمة تبقى بالخطوط اللاتينية القياسية.',
    limitEncrypted: 'الملفات المحمية بكلمة مرور تُرفض ولا تُفتح.',
    limitNoPassword: 'قفل PDF بكلمة مرور غير مدعوم محلياً بلا مكتبة تشفير ثقيلة: مكتبة pdf-lib لا تشفّر ولا تفكّ التشفير، ولن أخترع قفلاً غير حقيقي.',
    limitQuality: 'الصور تُدرج كما هي: لا ضغط ولا تصغير.',
    limitLarge: 'الملف يُقرأ كاملاً في الذاكرة، فقد يبطؤ النظام مع الملفات الكبيرة.',
    limitList: 'قائمة الصفحات تعرض أول {n} صفحة فقط.',

    readOnlyBadge: 'عرض فقط',
    pageNumbersCmd: 'أرقام الصفحات',
    pageNumbersDone: 'أُضيفت أرقام الصفحات.',
    sideToggle: 'الشريط الجانبي',
    undo: 'تراجع',
    redo: 'إعادة',
    undone: 'تم التراجع عن آخر تعديل.',
    redone: 'أُعيد التعديل.',
    search: 'بحث',
    printTitle: 'طباعة مباشرة',
    help: 'مساعدة',
    save: 'حفظ',
    saveAs: 'حفظ باسم…',
    saveVerifyFailed: 'كُتب الملف لكن قراءته من جديد لم تطابق: لا تعتمد على {path} وأعد الحفظ.',
    ribbonLabel: 'شريط الأدوات',
    sideLabel: 'الصفحات والإشارات المرجعية والبحث',
    viewLabel: 'صفحات المستند',
    paneLabel: 'لوحة المهام',
    dismiss: 'إخفاء الرسالة',
    chooseAnother: 'اختر ملفاً آخر',
    closeTitle: 'تعديلات غير محفوظة',
    closeMessage: 'في «{name}» تعديلات لم تُحفظ بعد. إن تابعت ستضيع.',
    closeDiscard: 'تجاهل التعديلات',
    readOnlyRefused: 'هذا المستند محمي بكلمة مرور ومفتوح للعرض فقط: لا يمكن تعديله هنا.',
    readOnlyOpened: 'فُتح المستند المحمي للعرض فقط. التعديل والحفظ غير متاحين له.',
    opened: 'فُتح المستند: {n} صفحة.',
    placeOnPage: 'ضعه على الصفحة',
    advancedCoords: 'متقدم: بالإحداثيات',
    advancedText: 'نص بالإحداثيات',
    fontUnavailable: 'تعذّر تحميل الخط العربي المضمّن، فلم يُكتب شيء.',
    engineMissing: 'التعليقات المحفوظة داخل الملف غير متاحة في هذه النسخة بعد.',
    signDraw: 'توقيع بخط اليد',
    signTyped: 'توقيع بالكتابة',
    signPadLabel: 'مساحة رسم التوقيع',
    signPadHint: 'ارسم توقيعك بإصبعك أو بالقلم أو بالفأرة، ثم «استخدام» واضغط على الصفحة لوضعه وحرّكه وغيّر حجمه.',
    signClear: 'مسح',
    signUse: 'استخدام التوقيع',
    signEmpty: 'ارسم التوقيع أولاً.',
    signPlaced: 'وُضع التوقيع على الصفحة {n}.',
    imagePlaced: 'وُضعت الصورة على الصفحة {n}.',
    extractSuffix: '-صفحات',
    extractDone: 'استُخرجت {n} صفحة إلى {path}',
    mergeAddFiles: 'إضافة من ملفاتي',
    newFromImagesName: 'صور',
    mergedName: 'مدمج',
    untitled: 'مستند جديد',
    downloadDone: 'بدأ التنزيل.',
    fieldsPending: 'في النموذج قيم لم تُكتب في الملف بعد.',
    fieldsWrite: 'كتابة القيم',
    fieldsDiscard: 'تجاهل القيم',
    fieldsNeedEngine: 'قوائم الاختيار وأزرار الراديو تحتاج محرّك النماذج الذي لم يُدمج بعد.',
    formOnPageHint: 'الحقول تظهر على الصفحة نفسها: اضغط الحقل واكتب، وTab ينتقل للحقل التالي.',
    formListCmd: 'قائمة الحقول',
    securityTitle: 'الأمان والصلاحيات',
    securityDesc: 'ما يسمح به المستند، وما يستطيعه هذا التطبيق وما لا يستطيعه.',
    securityEncrypted: 'المستند مشفّر بكلمة مرور ومفتوح للعرض فقط.',
    securityOpen: 'المستند غير مشفّر.',
    securityCmd: 'الأمان',
    permAll: 'لا قيود: الطباعة والنسخ والتعديل مسموحة.',
    permPrint: 'الطباعة',
    permCopy: 'نسخ النص',
    permModify: 'تعديل المحتوى',
    permAnnotate: 'التعليقات والنماذج',
    permYes: 'مسموح',
    permNo: 'غير مسموح',
    linkExternal: 'رابط خارجي: {url}',
    linkInternal: 'انتقال داخل المستند',
    linkOpenTitle: 'فتح رابط خارجي؟',
    linkOpenMessage: 'سيُفتح هذا الرابط في تبويب جديد: {url}',
    linkOpen: 'فتح الرابط',
    close: 'إغلاق',
    multiSelect: 'تحديد عدة صفحات',
    multiSelectOn: 'التحديد المتعدد يعمل: كل ضغطة تضيف صفحة أو تزيلها.',
    multiSelectOff: 'التحديد المتعدد متوقف.',
    rotateLeft: 'تدوير لليسار',
    rotateRight: 'تدوير لليمين',
    duplicateCmd: 'تكرار',
    insertBefore: 'صفحة فارغة قبلها',
    insertAfter: 'صفحة فارغة بعدها',
    extractCmd: 'استخراج',
    deleteCmd: 'حذف',
    deleteConfirm: 'حذف {n} صفحة من النسخة العاملة؟ يمكنك التراجع بـ Ctrl+Z.',
    outlineEmpty: 'لا توجد إشارات مرجعية في هذا المستند.',
    commentsEmpty: 'لا تعليقات بعد. اختر أداة من تبويب «تعليق» وابدأ.',
    searchPlaceholder: 'ابحث في المستند',
    searchPrev: 'النتيجة السابقة',
    searchNext: 'النتيجة التالية',
    searching: 'جارٍ البحث…',
    searchNone: 'لا نتائج.',
    searchNoneHint: 'لم يُعثر على النص. الصفحات الممسوحة ضوئياً بلا نص لا يمكن البحث فيها.',
    searchCount: '{n} من {total}',
    sideThumbs: 'الصفحات',
    sideOutline: 'الإشارات المرجعية',
    sideComments: 'التعليقات',
    taskPages: 'تنظيم الصفحات',
    propertiesTitle: 'خصائص المستند',
    more: 'المزيد',
    openCmd: 'فتح',
    zoomIn: 'تكبير',
    zoomOut: 'تصغير',
    fitWidth: 'ملاءمة العرض',
    fitPage: 'ملاءمة الصفحة',
    actualSize: 'الحجم الفعلي',
    zoomLevel: 'نسبة التكبير',
    prevPage: 'الصفحة السابقة',
    nextPage: 'الصفحة التالية',
    pageNumber: 'رقم الصفحة',
    pageLabel: '({label})',
    pageMenu: 'خيارات الصفحة {n}',
    nightMode: 'القراءة الليلية',
    nightOn: 'القراءة الليلية تعمل.',
    nightOff: 'القراءة الليلية متوقفة.',
    shortcutsTitle: 'اختصارات لوحة المفاتيح',
    viewRotateLeft: 'تدوير العرض يساراً',
    viewRotateRight: 'تدوير العرض يميناً',
    viewNoCanvas: 'هذه البيئة لا ترسم الصفحات. العمليات والحفظ تعمل كالمعتاد.',
    viewRenderFailed: 'تعذّر رسم هذا المستند، مع أنه فُتح. العمليات والحفظ تعمل كالمعتاد.',
    tabHome: 'الرئيسية',
    tabComment: 'تعليق',
    tabEditRibbon: 'تحرير',
    tabOrganize: 'تنظيم',
    tabForms: 'نماذج',
    tabProtect: 'حماية وتوقيع',
    tabViewRibbon: 'عرض',
    groupFile: 'ملف',
    groupTools: 'أدوات',
    groupZoom: 'تكبير',
    groupQuick: 'سريع',
    groupMarkup: 'تعليم النص',
    groupNotes: 'ملاحظات',
    groupDraw: 'رسم',
    groupStyle: 'المظهر',
    groupManage: 'إدارة',
    groupAdd: 'إضافة',
    groupMarks: 'علامات',
    groupDocument: 'المستند',
    groupInsert: 'إدراج',
    groupPages: 'الصفحات',
    groupFill: 'التعبئة',
    groupSign: 'التوقيع',
    groupHide: 'إخفاء',
    groupSecurity: 'الأمان',
    groupRotateView: 'تدوير العرض',
    groupPanels: 'اللوحات',
    groupReading: 'القراءة',
    toolHand: 'يد',
    toolSelect: 'تحديد نص',
    toolHighlight: 'تمييز',
    toolUnderline: 'تسطير',
    toolStrikeout: 'شطب',
    toolNote: 'ملاحظة',
    toolTextbox: 'مربع نص',
    toolStamp: 'ختم',
    toolPen: 'قلم',
    toolRect: 'مستطيل',
    toolEllipse: 'بيضاوي',
    toolLine: 'خط',
    toolArrow: 'سهم',
    toolText: 'إضافة نص',
    toolImage: 'صورة',
    toolCover: 'تغطية',
    styleCmd: 'اللون والسُّمك',
    styleFor: 'مظهر: {tool}',
    customColor: 'لون مخصص',
    opacity: 'الشفافية',
    strokeWidth: 'السُّمك',
    fontSize: 'حجم الخط',
    watermarkCmd: 'علامة مائية',
    blankCmd: 'صفحة فارغة',
    mergeCmd: 'دمج ملفات',
    imagesCmd: 'من صور',
    cropCmd: 'قص',
    splitCmd: 'تقسيم',
    hintHand: 'اسحب لتحريك الصفحات.',
    hintSelect: 'حدد النص لنسخه، أو اضغط تعليقاً لتعديله.',
    hintMarkup: 'حدد النص على الصفحة وسيُعلَّم مباشرة.',
    hintPen: 'ارسم على الصفحة. يُحفظ الرسم بعد لحظة من التوقف.',
    hintShape: 'اسحب على الصفحة لرسم الشكل.',
    hintNote: 'اضغط على الصفحة حيث تريد الملاحظة.',
    hintTextbox: 'اسحب مربعاً على الصفحة ثم اكتب.',
    hintText: 'اضغط على الصفحة حيث يبدأ النص ثم اكتب. اسحب المربع لتحريكه.',
    hintCover: 'اسحب مستطيلاً فوق المنطقة التي تريد تغطيتها.',
    hintPlace: 'اضغط على الصفحة لوضعه، ثم حرّكه وغيّر حجمه واضغط ✓.',
    annotDone: 'أُضيف {kind}.',
    annotUpdated: 'عُدّل التعليق.',
    annotDeleted: 'حُذف التعليق.',
    annotDelete: 'حذف',
    annotEditText: 'تعديل النص',
    annotSelect: 'تعليق: {kind}',
    noteLabel: 'نص الملاحظة',
    typeHere: 'اكتب هنا',
    apply: 'تطبيق',
    placeLabel: 'عنصر للوضع: اسحبه أو غيّر حجمه من الزوايا',
    stampChoose: 'اختر ختماً أولاً من زر «ختم».',
    stampApproved: 'معتمد',
    stampDraft: 'مسودة',
    stampConfidential: 'سري',
    stampFinal: 'نهائي',
    stampReviewed: 'تمت المراجعة',
    kindHighlight: 'تمييز',
    kindUnderline: 'تسطير',
    kindStrikeout: 'شطب',
    kindInk: 'رسم حر',
    kindSquare: 'مستطيل',
    kindCircle: 'بيضاوي',
    kindLine: 'خط',
    kindArrow: 'سهم',
    kindNote: 'ملاحظة',
    kindFreetext: 'مربع نص',
    kindStamp: 'ختم',
    passwordTitle: 'مستند محمي بكلمة مرور',
    passwordLabel: 'كلمة المرور لعرض المستند',
    passwordRetry: 'كلمة المرور غير صحيحة، أعد المحاولة',
    startTitle: 'مستندات PDF',
    startSub: 'افتح مستنداً أو أنشئ واحداً جديداً. كل شيء يبقى على جهازك.',
    startHint: 'اختر مستنداً لتبدأ.',
    startOpenFiles: 'فتح من ملفاتي',
    startOpenFilesHint: 'ملفات PDF في مجلدك الشخصي',
    startOpenDevice: 'فتح من الجهاز',
    startOpenDeviceHint: 'ملف من جهازك مباشرة',
    startBlank: 'مستند فارغ',
    startBlankHint: 'صفحة A4 جديدة',
    startImages: 'من صور',
    startImagesHint: 'صور PNG/JPEG إلى PDF',
    startMerge: 'دمج ملفات',
    startMergeHint: 'عدة ملفات PDF في ملف واحد',
    recentTitle: 'الأخيرة',
    recentEmpty: 'لم تفتح مستندات بعد. آخر عشرة ملفات تظهر هنا.',
    recentForget: 'إزالة «{name}» من القائمة',
    backToDoc: 'العودة إلى المستند',
    pickTitle: 'فتح ملف PDF',
    pickManyTitle: 'اختر ملفات PDF',
    pickFilter: 'تصفية بالاسم',
    pickNone: 'لا توجد ملفات PDF في مجلدك بعد.',
    pickNoMatch: 'لا ملف يطابق هذا الاسم.',
    pickAdd: 'إضافة المحدد',
    keyNew: 'مستند فارغ جديد',
    keyOpen: 'فتح',
    keySave: 'حفظ',
    keySaveAs: 'حفظ باسم',
    keyPrint: 'طباعة',
    keyUndo: 'تراجع',
    keyRedo: 'إعادة',
    keyFind: 'بحث',
    keyFindNext: 'النتيجة التالية',
    keyFindPrev: 'النتيجة السابقة',
    keyGoto: 'الانتقال إلى صفحة',
    keyZoomIn: 'تكبير',
    keyZoomOut: 'تصغير',
    keyFit: 'ملاءمة الصفحة',
    keyActual: 'الحجم الفعلي',
    keyFirst: 'الصفحة الأولى',
    keyLast: 'الصفحة الأخيرة',
    keyNextPage: 'الصفحة التالية',
    keyPrevPage: 'الصفحة السابقة',
    keySelectAll: 'تحديد كل الصفحات (في لوحة الصفحات)',
    keyDelete: 'حذف الصفحات المحددة (في لوحة الصفحات)',
    keyEscape: 'إلغاء الأداة أو إغلاق اللوحة',
    keyHelp: 'هذه القائمة',
  },
  en: {
    title: 'PDF Documents',
    loading: 'Opening the file…',
    readError: 'Could not read the file from the file system.',
    pagesCount: '{n} pages',
    pageCountOne: '1 page',
    sizeLabel: 'Size: {size}',
    modified: 'Modified',
    reset: 'Reset to the opened file',
    resetDone: 'Back to the opened file.',
    busy: 'Working…',

    viewNoViewer: 'The page renderer could not be loaded. Operations, saving and download work as usual.',
    openInTab: 'Open in a tab',
    download: 'Download',
    print: 'Print',
    printReady: 'The print dialog for this file is open.',
    printNoViewer: 'This browser cannot show a PDF inside the system, so it cannot print it either. Download the file and print it outside.',
    printFailed: 'The print dialog could not be opened.',
    printNoBytes: 'There is no file to print.',

    refusalTitle: 'Could not open this file',
    refusalEmpty: 'The file is empty (zero bytes).',
    refusalNotPdf: 'This is not a PDF: it has no %PDF- header.',
    refusalEncrypted: 'The file is password-protected (encrypted) and pdf-lib refuses to open it. Remove the protection with another program and try again.',
    refusalCorrupt: 'This looks like a PDF but it could not be parsed: it may be damaged or truncated.',
    refusalImageUnsupported: 'This image is neither PNG nor JPEG, and only those two can be embedded.',
    refusalImageBroken: 'This image could not be read: its signature is right but its data is damaged or truncated.',
    refusalTextNotRenderable: 'The text holds characters the built-in PDF fonts cannot draw (Arabic, for example). Write the text in Latin letters, or add the font outside the system.',
    refusalNoForm: 'This document has no interactive form (AcroForm) to write values into.',
    refusalEmptyResult: 'This operation would leave zero pages, and I will not write an empty document.',
    refusalOutsideHome: 'Saving outside /home/user is not allowed.',
    refusalWriteFailed: 'Could not write to the file system.',
    refusalUnknown: 'The operation failed and I could not verify a valid result, so nothing was saved.',
    refusalDetail: 'Technical detail: {detail}',
    noOverwrite: 'No file was written.',

    infoTitle: 'Document info',
    infoDesc: 'The page count, each page’s size and rotation, and the current metadata.',
    infoPages: 'Pages: {n}',
    infoMetaTitle: 'Title',
    infoAuthor: 'Author',
    infoSubject: 'Subject',
    infoKeywords: 'Keywords',
    infoNone: '—',
    infoPageLine: '{w} × {h} pt · rotation {rot}°',
    infoCropLine: 'Crop: {w} × {h} at ({x}, {y})',

    pagesTitle: 'Pages',
    pagesDesc: 'Tap a row to select a page, or type a range and press “Select”. Reorder by dragging or with the arrows.',
    rangeLabel: 'Page range',
    rangePlaceholder: '1-3,5,8-',
    rangeApply: 'Select',
    selectAll: 'Select all',
    clearSelection: 'Clear selection',
    selectedCount: 'Selected: {n}',
    selectionNone: 'No pages selected. Pick a row or type a range first.',
    rangeErrorSyntax: 'Unreadable part of the range: {token}',
    rangeErrorEmpty: 'Type a range such as 1-3,5.',
    rangeErrorReversed: 'The range runs backwards: {from}-{to}.',
    rangeErrorOutOfRange: 'Page {page} is outside the document ({count} pages).',
    pagesLimited: 'The list shows only the first {n} pages; use the range box beyond that.',
    moveUp: 'Move up',
    moveDown: 'Move down',
    dragHint: 'Drag a row to reorder it (on mobile use the arrows).',
    reorderDone: 'Pages reordered.',
    pageN: 'Page {n}',

    opsTitle: 'Operations',
    deleteTitle: 'Delete pages',
    deleteDesc: 'Removes the selected pages from the working copy. Nothing is saved automatically, and reset brings the original back.',
    deleteApply: 'Delete selected',
    deleteDone: 'Deleted {n} pages.',
    rotateTitle: 'Rotate pages',
    rotateDesc: 'Turns the selected pages by 90, 180 or 270 degrees; the rotation is stored with the page.',
    rotate90: '90°',
    rotate180: '180°',
    rotate270: '270°',
    rotateDone: 'Rotated {n} pages.',
    cropTitle: 'Crop (crop box)',
    cropDesc: 'Cuts margins in points (72 pt = 1 inch) from each side. Cropping hides the content when displayed; it does not delete it.',
    cropTop: 'Top',
    cropRight: 'Right',
    cropBottom: 'Bottom',
    cropLeft: 'Left',
    cropApply: 'Apply crop',
    cropDone: 'Cropped {n} pages.',
    cropErrorNegative: 'Margins cannot be negative.',
    cropErrorNoArea: 'The margins are larger than the page: no area is left.',
    watermarkTitle: 'Text watermark',
    watermarkDesc: 'Draws the text at the centre of every selected page with the size, opacity and rotation you choose, over the existing content, never editing it. With nothing selected it applies to every page, and the default opacity 0.15 keeps the mark light.',
    watermarkText: 'Text',
    watermarkSize: 'Font size',
    watermarkOpacity: 'Opacity',
    watermarkRotation: 'Rotation',
    watermarkApply: 'Add watermark',
    watermarkDone: 'Watermark added to {n} pages.',
    watermarkErrorText: 'Type the watermark text.',
    watermarkErrorSize: 'The font size must be between 4 and 400.',
    watermarkErrorOpacity: 'Opacity must be above 0 and at most 1.',
    watermarkErrorChars: 'Unsupported characters: {chars} — the built-in PDF fonts are Latin only.',
    watermarkRotationNote: 'Rotation is relative to the page’s own orientation.',

    textTitle: 'Add text to a page',
    textDesc: 'Write new text over the page: choose the page and the point (in points from the page’s left edge and from its bottom, 72 pt = 1 inch), the standard font, the size and the colour.',
    textValue: 'Text',
    textPage: 'Page',
    textX: 'From the left (pt)',
    textY: 'From the bottom (pt)',
    textSize: 'Font size',
    textColor: 'Colour',
    textFont: 'Font',
    textFontHelvetica: 'Helvetica',
    textFontHelveticaBold: 'Helvetica Bold',
    textFontTimesRoman: 'Times Roman',
    textFontTimesItalic: 'Times Italic',
    textFontCourier: 'Courier',
    textApply: 'Add the text',
    textDone: 'Text added to page {n}.',
    textNote: 'The text is added as a new layer over the content; it does not edit or delete the document’s own text.',
    textErrorText: 'Type the text first.',
    textErrorSize: 'The font size must be between 4 and 400.',
    textErrorPoint: 'The point is outside the page: give a position within the page’s left and bottom edges.',
    textErrorColor: 'That colour cannot be read. Use a value such as #1a1a1a.',
    textErrorFont: 'Choose one of the listed fonts.',
    textErrorChars: 'Unsupported characters: {chars} — the standard fonts are Latin only.',
    textErrorPage: 'The page number must be between 1 and {count}.',

    signTitle: 'Add a signature',
    signDesc: 'A typed signature (large italic text) or a PNG/JPEG signature picture from your device, drawn over the page where you choose.',
    signText: 'Signature text',
    signApply: 'Add the typed signature',
    signDone: 'The typed signature was added to page {n}.',
    signImage: 'Signature picture',
    signImageAdd: 'Choose a picture (PNG/JPEG)',
    signImageNone: 'No signature picture has been chosen yet.',
    signImagePicked: 'Signature picture: {name}',
    signImageWidth: 'Picture width (pt)',
    signImageHeight: 'Picture height (pt)',
    signImageApply: 'Insert the signature picture',
    signImageDone: 'The signature picture was inserted on page {n}.',
    signImageRefused: 'The signature picture must be a PNG or JPEG. The type read was: {code}',
    signImageErrorRect: 'The picture box is outside the page or has no area: adjust the coordinates, width and height.',

    coverTitle: 'Cover a region (hiding)',
    coverDesc: 'Draws a filled rectangle or ellipse over a region of a page, hiding what is under it when the page is read.',
    coverNote: 'Stated plainly: this is covering/hiding, NOT redaction. The original text stays inside the file and can still be extracted, so if the goal is to really remove the words, this tool is not enough.',
    coverShape: 'Shape',
    coverRect: 'Rectangle',
    coverEllipse: 'Ellipse',
    coverWidth: 'Width (pt)',
    coverHeight: 'Height (pt)',
    coverApply: 'Cover the region',
    coverDone: 'Covered a region on page {n}.',
    coverErrorRect: 'The width and height must be greater than zero.',
    coverErrorOutside: 'The region is outside the page: adjust the coordinates.',
    coverErrorPage: 'The page number must be between 1 and {count}.',

    pageopsTitle: 'Blank page and duplicates',
    pageopsDesc: 'Insert a blank page before the position you choose (it takes the neighbouring page’s size), or duplicate the selected pages once each.',
    blankAt: 'Insert before page number',
    blankApply: 'Insert a blank page',
    blankDone: 'A blank page was inserted at position {n}.',
    duplicateApply: 'Duplicate the selected pages',
    duplicateDone: 'Duplicated {n} pages next to themselves.',
    pageopsNone: 'Select pages first to duplicate them; “Select all” selects every page.',

    formTitle: 'Fill the form',
    formDesc: 'The text fields and checkboxes the document already carries (AcroForm): edit the values here and write them into the file; they are read back before I say it worked.',
    formAppearanceNote: 'The value is written together with the field’s own appearance. If it holds characters the standard fonts cannot draw (Arabic, for example) the value is still written and the reader is asked to build the appearance (NeedAppearances), which readers that honour it will show.',
    formCount: 'Fillable fields: {n}',
    formNone: 'This document has no interactive form (AcroForm), so there are no fields to fill.',
    formNoneFillable: 'A form exists, but it holds no fillable text fields or checkboxes.',
    formOtherHint: 'Other fields that are not supported here (buttons, lists, signatures): {n}',
    formReadOnly: 'Read-only, it will not be written.',
    formCheckbox: 'Checkbox',
    formApply: 'Write the values into the file',
    formDone: 'Wrote {n} form values and verified them.',
    formError: 'The form could not be read: {message}',

    metadataTitle: 'Metadata',
    metadataDesc: 'The fields are saved exactly as shown here; clear a field to delete its value. The document’s own text is not edited.',
    metadataApply: 'Save metadata',
    metadataDone: 'Metadata saved.',
    keywordsHint: 'Separate keywords with a comma or a space.',
    splitTitle: 'Split / extract',
    splitDesc: 'A new file for every range you type: one range gives one file, several ranges give several files.',
    splitApply: 'Extract',
    splitDone: 'Created: {path}',
    splitDoneMany: 'Created {n} files.',
    mergeTitle: 'Merge PDFs',
    mergeDesc: 'Add files from your device to the merge order, with a range for each. The result becomes the working copy.',
    mergeAdd: 'Add files',
    mergeApply: 'Merge',
    mergeDone: 'Merged {n} sources into a {pages}-page document.',
    mergeEmpty: 'Add at least one file besides the open document.',
    mergeOpenDoc: 'The open document',
    sourcePages: '{name} · {n} pages',
    sourceRangeLabel: 'This file’s range',
    remove: 'Remove',
    imagesTitle: 'Images → PDF',
    imagesDesc: 'One image per page, PNG or JPEG only, with a choice of page size.',
    imagesAdd: 'Add images',
    imagesPageSize: 'Page size',
    imagesA4: 'A4',
    imagesLetter: 'Letter',
    imagesFit: 'Fit to image',
    imagesApply: 'Create a PDF from the images',
    imagesEmpty: 'Add at least one image.',
    imagesDone: 'Created a document from {n} images: {pages} pages.',
    imagesRefused: 'Skipped {name}: {code}',
    opFailed: 'The operation did not run: {message}',
    opVerified: 'Output verified.',

    saveTitle: 'Save',
    saveDesc: 'The default save creates a new file beside the original and never touches it. Replacing needs confirmation and writes one .bak copy first.',
    saveTarget: 'Target: {path}',
    saveCopy: 'Save as a new copy',
    saveCopySuffix: '-copy',
    saveOverwrite: 'Replace the original',
    saveOverwriteConfirm: 'Confirm replace (.bak first)',
    saveOverwriteWarn: 'The original “{name}” will be replaced by the working copy, after one backup is written as {bak}.',
    cancel: 'Cancel',
    saveDoneCopy: 'Saved a new copy: {path}',
    saveDoneOverwrite: 'The original was replaced; the backup is: {path}',
    saveNoBytes: 'There is nothing to save (zero bytes).',
    saveFailed: 'Saving failed.',

    limitsTitle: 'Honest limits',
    limitTextEdit: 'No editing or deleting of text already in the document: new text can be added over it or the region can be covered, and the original text stays in the file.',
    limitNoRedaction: 'No true redaction: covering draws over the content and does not remove the text from the file.',
    limitNoOcr: 'No OCR: scanned pages stay images and no text is extracted from them.',
    limitNoSign: 'No digital signatures and no timestamps, and existing signatures are not verified.',
    limitNoForms: 'No creating new forms and no deleting fields: only the existing text fields and checkboxes are filled.',
    limitNoRaster: 'Pages are drawn for viewing only: pages are not exported as image files.',
    limitNoFonts: 'Arabic text is written with an embedded Arabic font (Noto Naskh Arabic), shaped and in the right direction; the watermark panel still uses the standard Latin fonts.',
    limitEncrypted: 'Password-protected files are refused, not opened.',
    limitNoPassword: 'Locking a PDF with a password is not supported locally without a heavy encryption library: pdf-lib neither encrypts nor decrypts, and I will not invent a lock that is not real.',
    limitQuality: 'Images are embedded as they are: no recompression and no downscaling.',
    limitLarge: 'The file is read fully into memory, which can slow the system with large files.',
    limitList: 'The page list shows only the first {n} pages.',

    readOnlyBadge: 'View only',
    pageNumbersCmd: 'Page numbers',
    pageNumbersDone: 'Page numbers were added.',
    sideToggle: 'Sidebar',
    undo: 'Undo',
    redo: 'Redo',
    undone: 'The last edit was undone.',
    redone: 'The edit was redone.',
    search: 'Search',
    printTitle: 'Print directly',
    help: 'Help',
    save: 'Save',
    saveAs: 'Save as…',
    saveVerifyFailed: 'The file was written but reading it back did not match: do not rely on {path}; save again.',
    ribbonLabel: 'Toolbar',
    sideLabel: 'Pages, bookmarks and search',
    viewLabel: 'Document pages',
    paneLabel: 'Task pane',
    dismiss: 'Dismiss the message',
    chooseAnother: 'Choose another file',
    closeTitle: 'Unsaved changes',
    closeMessage: '“{name}” has changes that are not saved yet. If you go on they are lost.',
    closeDiscard: 'Discard changes',
    readOnlyRefused: 'This document is password-protected and open for viewing only: it cannot be edited here.',
    readOnlyOpened: 'The protected document is open for viewing only. Editing and saving are not available for it.',
    opened: 'Document opened: {n} pages.',
    placeOnPage: 'Place on the page',
    advancedCoords: 'Advanced: by coordinates',
    advancedText: 'Text by coordinates',
    fontUnavailable: 'The embedded Arabic font could not be loaded, so nothing was written.',
    engineMissing: 'Comments saved inside the file are not available in this build yet.',
    signDraw: 'Handwritten signature',
    signTyped: 'Typed signature',
    signPadLabel: 'Signature drawing area',
    signPadHint: 'Draw your signature with a finger, a pen or the mouse, then “Use” and tap the page to place it; move and resize it there.',
    signClear: 'Clear',
    signUse: 'Use signature',
    signEmpty: 'Draw the signature first.',
    signPlaced: 'The signature was placed on page {n}.',
    imagePlaced: 'The picture was placed on page {n}.',
    extractSuffix: '-pages',
    extractDone: '{n} pages extracted to {path}',
    mergeAddFiles: 'Add from my files',
    newFromImagesName: 'Images',
    mergedName: 'Merged',
    untitled: 'New document',
    downloadDone: 'The download started.',
    fieldsPending: 'The form has values not written into the file yet.',
    fieldsWrite: 'Write values',
    fieldsDiscard: 'Discard values',
    fieldsNeedEngine: 'Dropdowns and radio buttons need the forms engine, which is not merged yet.',
    formOnPageHint: 'The fields show on the page itself: tap a field and type; Tab moves to the next one.',
    formListCmd: 'Field list',
    securityTitle: 'Security and permissions',
    securityDesc: 'What the document allows, and what this app can and cannot do.',
    securityEncrypted: 'The document is password-encrypted and open for viewing only.',
    securityOpen: 'The document is not encrypted.',
    securityCmd: 'Security',
    permAll: 'No restrictions: printing, copying and editing are allowed.',
    permPrint: 'Printing',
    permCopy: 'Copying text',
    permModify: 'Changing content',
    permAnnotate: 'Comments and forms',
    permYes: 'allowed',
    permNo: 'not allowed',
    linkExternal: 'External link: {url}',
    linkInternal: 'Jump inside the document',
    linkOpenTitle: 'Open an external link?',
    linkOpenMessage: 'This link opens in a new tab: {url}',
    linkOpen: 'Open link',
    close: 'Close',
    multiSelect: 'Select several pages',
    multiSelectOn: 'Multi-select is on: each tap adds or removes a page.',
    multiSelectOff: 'Multi-select is off.',
    rotateLeft: 'Rotate left',
    rotateRight: 'Rotate right',
    duplicateCmd: 'Duplicate',
    insertBefore: 'Blank page before',
    insertAfter: 'Blank page after',
    extractCmd: 'Extract',
    deleteCmd: 'Delete',
    deleteConfirm: 'Delete {n} pages from the working copy? You can undo with Ctrl+Z.',
    outlineEmpty: 'This document has no bookmarks.',
    commentsEmpty: 'No comments yet. Pick a tool in the “Comment” tab to start.',
    searchPlaceholder: 'Search the document',
    searchPrev: 'Previous result',
    searchNext: 'Next result',
    searching: 'Searching…',
    searchNone: 'No results.',
    searchNoneHint: 'The text was not found. Scanned pages without text cannot be searched.',
    searchCount: '{n} of {total}',
    sideThumbs: 'Pages',
    sideOutline: 'Bookmarks',
    sideComments: 'Comments',
    taskPages: 'Organize pages',
    propertiesTitle: 'Document properties',
    more: 'More',
    openCmd: 'Open',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    fitWidth: 'Fit width',
    fitPage: 'Fit page',
    actualSize: 'Actual size',
    zoomLevel: 'Zoom level',
    prevPage: 'Previous page',
    nextPage: 'Next page',
    pageNumber: 'Page number',
    pageLabel: '({label})',
    pageMenu: 'Page {n} options',
    nightMode: 'Night reading',
    nightOn: 'Night reading is on.',
    nightOff: 'Night reading is off.',
    shortcutsTitle: 'Keyboard shortcuts',
    viewRotateLeft: 'Rotate view left',
    viewRotateRight: 'Rotate view right',
    viewNoCanvas: 'This environment cannot draw pages. Operations and saving work as usual.',
    viewRenderFailed: 'This document opened but could not be drawn. Operations and saving work as usual.',
    tabHome: 'Home',
    tabComment: 'Comment',
    tabEditRibbon: 'Edit',
    tabOrganize: 'Organize',
    tabForms: 'Forms',
    tabProtect: 'Protect & Sign',
    tabViewRibbon: 'View',
    groupFile: 'File',
    groupTools: 'Tools',
    groupZoom: 'Zoom',
    groupQuick: 'Quick',
    groupMarkup: 'Text markup',
    groupNotes: 'Notes',
    groupDraw: 'Draw',
    groupStyle: 'Style',
    groupManage: 'Manage',
    groupAdd: 'Add',
    groupMarks: 'Marks',
    groupDocument: 'Document',
    groupInsert: 'Insert',
    groupPages: 'Pages',
    groupFill: 'Fill',
    groupSign: 'Sign',
    groupHide: 'Hide',
    groupSecurity: 'Security',
    groupRotateView: 'Rotate view',
    groupPanels: 'Panels',
    groupReading: 'Reading',
    toolHand: 'Hand',
    toolSelect: 'Select text',
    toolHighlight: 'Highlight',
    toolUnderline: 'Underline',
    toolStrikeout: 'Strikeout',
    toolNote: 'Note',
    toolTextbox: 'Text box',
    toolStamp: 'Stamp',
    toolPen: 'Pen',
    toolRect: 'Rectangle',
    toolEllipse: 'Ellipse',
    toolLine: 'Line',
    toolArrow: 'Arrow',
    toolText: 'Add text',
    toolImage: 'Picture',
    toolCover: 'Cover',
    styleCmd: 'Colour and width',
    styleFor: 'Style: {tool}',
    customColor: 'Custom colour',
    opacity: 'Opacity',
    strokeWidth: 'Width',
    fontSize: 'Font size',
    watermarkCmd: 'Watermark',
    blankCmd: 'Blank page',
    mergeCmd: 'Merge files',
    imagesCmd: 'From images',
    cropCmd: 'Crop',
    splitCmd: 'Split',
    hintHand: 'Drag to move the pages.',
    hintSelect: 'Select text to copy it, or tap a comment to change it.',
    hintMarkup: 'Select text on the page and it is marked at once.',
    hintPen: 'Draw on the page. The drawing is saved a moment after you stop.',
    hintShape: 'Drag on the page to draw the shape.',
    hintNote: 'Tap the page where the note should go.',
    hintTextbox: 'Drag a box on the page, then type.',
    hintText: 'Tap the page where the text starts, then type. Drag the box to move it.',
    hintCover: 'Drag a rectangle over the area to cover.',
    hintPlace: 'Tap the page to place it, then move and resize it and press ✓.',
    annotDone: '{kind} added.',
    annotUpdated: 'The comment was changed.',
    annotDeleted: 'The comment was deleted.',
    annotDelete: 'Delete',
    annotEditText: 'Edit text',
    annotSelect: 'Comment: {kind}',
    noteLabel: 'Note text',
    typeHere: 'Type here',
    apply: 'Apply',
    placeLabel: 'Item to place: drag it, or resize it from the corners',
    stampChoose: 'Pick a stamp first with the “Stamp” button.',
    stampApproved: 'APPROVED',
    stampDraft: 'DRAFT',
    stampConfidential: 'CONFIDENTIAL',
    stampFinal: 'FINAL',
    stampReviewed: 'REVIEWED',
    kindHighlight: 'Highlight',
    kindUnderline: 'Underline',
    kindStrikeout: 'Strikeout',
    kindInk: 'Freehand',
    kindSquare: 'Rectangle',
    kindCircle: 'Ellipse',
    kindLine: 'Line',
    kindArrow: 'Arrow',
    kindNote: 'Note',
    kindFreetext: 'Text box',
    kindStamp: 'Stamp',
    passwordTitle: 'Password-protected document',
    passwordLabel: 'Password to view the document',
    passwordRetry: 'Wrong password, try again',
    startTitle: 'PDF Documents',
    startSub: 'Open a document or make a new one. Everything stays on your device.',
    startHint: 'Pick a document to start.',
    startOpenFiles: 'Open from my files',
    startOpenFilesHint: 'PDFs in your home folder',
    startOpenDevice: 'Open from device',
    startOpenDeviceHint: 'A file straight from your device',
    startBlank: 'Blank document',
    startBlankHint: 'A new A4 page',
    startImages: 'From images',
    startImagesHint: 'PNG/JPEG pictures to PDF',
    startMerge: 'Merge files',
    startMergeHint: 'Several PDFs into one',
    recentTitle: 'Recent',
    recentEmpty: 'No documents opened yet. The last ten files show here.',
    recentForget: 'Remove “{name}” from the list',
    backToDoc: 'Back to the document',
    pickTitle: 'Open a PDF',
    pickManyTitle: 'Choose PDF files',
    pickFilter: 'Filter by name',
    pickNone: 'There are no PDF files in your folder yet.',
    pickNoMatch: 'No file matches this name.',
    pickAdd: 'Add selected',
    keyNew: 'New blank document',
    keyOpen: 'Open',
    keySave: 'Save',
    keySaveAs: 'Save as',
    keyPrint: 'Print',
    keyUndo: 'Undo',
    keyRedo: 'Redo',
    keyFind: 'Search',
    keyFindNext: 'Next result',
    keyFindPrev: 'Previous result',
    keyGoto: 'Go to page',
    keyZoomIn: 'Zoom in',
    keyZoomOut: 'Zoom out',
    keyFit: 'Fit page',
    keyActual: 'Actual size',
    keyFirst: 'First page',
    keyLast: 'Last page',
    keyNextPage: 'Next page',
    keyPrevPage: 'Previous page',
    keySelectAll: 'Select all pages (in the pages panel)',
    keyDelete: 'Delete the selected pages (in the pages panel)',
    keyEscape: 'Cancel the tool or close the panel',
    keyHelp: 'This list',
  },
});

/* «حفظ باسم» — the format label for the shared shell dialog (src/shell/save-as.ts). */
defineStrings('pdf', {
  ar: { formatPdf: 'مستند PDF (.pdf)' },
  en: { formatPdf: 'PDF document (.pdf)' },
});
