import { defineStrings } from '../../kernel/i18n';

/**
 * Every visible string of the PDF app, in Arabic and English.
 * The two blocks must hold exactly the same keys — a repo-wide parity test and the
 * app's own `strings.test.ts` both fail otherwise.
 */
defineStrings('pdf', {
  ar: {
    title: 'مستندات PDF',
    badge: 'محرّر PDF',
    tabView: 'عرض',
    tabEdit: 'تعديل',
    loading: 'جارٍ فتح الملف…',
    readError: 'تعذّرت قراءة الملف من نظام الملفات.',
    noFile: 'افتح ملف PDF من تطبيق الملفات وسيظهر هنا.',
    pagesCount: '{n} صفحة',
    pageCountOne: 'صفحة واحدة',
    sizeLabel: 'الحجم: {size}',
    modified: 'مُعدّل',
    reset: 'إعادة تعيين إلى الملف الأصلي',
    resetDone: 'رجعنا إلى الملف الأصلي.',
    busy: 'جارٍ العمل…',

    viewNoViewer: 'هذا المتصفح لا يعرض PDF داخل النظام. نزّل النتيجة أو افتحها في تبويب.',
    openInTab: 'فتح في تبويب',
    download: 'تنزيل النتيجة',
    previewNote: 'المعاينة تعرض النسخة العاملة: بعد التعديلات في الذاكرة وقبل الحفظ.',

    refusalTitle: 'تعذّر فتح هذا الملف',
    refusalEmpty: 'الملف فارغ (صفر بايت).',
    refusalNotPdf: 'هذا ليس ملف PDF: لا توجد ترويسة %PDF- في أوله.',
    refusalEncrypted: 'الملف محمي بكلمة مرور (مشفّر)، ومكتبة pdf-lib ترفض فتحه. أزل الحماية ببرنامج آخر ثم أعد المحاولة.',
    refusalCorrupt: 'يبدو ملف PDF لكن قراءته فشلت: قد يكون تالفاً أو ناقصاً.',
    refusalImageUnsupported: 'هذه الصورة ليست PNG ولا JPEG، ولا يمكن إدراج غير هذين النوعين.',
    refusalImageBroken: 'تعذّرت قراءة هذه الصورة: ترويستها صحيحة لكن بياناتها تالفة أو ناقصة.',
    refusalTextNotRenderable: 'في النص حروف لا تستطيع خطوط PDF المدمجة رسمها (العربية مثلاً). اكتب العلامة المائية بحروف لاتينية.',
    refusalEmptyResult: 'هذه العملية تترك صفر صفحات، ولن أكتب مستنداً فارغاً.',
    refusalOutsideHome: 'الحفظ خارج /home/user غير مسموح.',
    refusalWriteFailed: 'تعذّر الحفظ في نظام الملفات.',
    refusalUnknown: 'فشلت العملية ولم أتحقق من ناتج صالح، لذلك لم أحفظ شيئاً.',
    refusalDetail: 'تفاصيل تقنية: {detail}',
    noOverwrite: 'لم يُكتب أي ملف.',

    infoTitle: 'معلومات المستند',
    infoDesc: 'عدد الصفحات وحجم كل صفحة ودورانها، والبيانات الوصفية الحالية.',
    infoPages: 'الصفحات: {n}',
    infoMetaTitle: 'العنوان',
    infoAuthor: 'المؤلف',
    infoSubject: 'الموضوع',
    infoKeywords: 'الكلمات المفتاحية',
    infoNone: '—',
    infoPageLine: '{w} × {h} نقطة · دوران {rot}°',
    infoCropLine: 'القص: {w} × {h} عند ({x}, {y})',

    pagesTitle: 'الصفحات',
    pagesDesc: 'اختر الصفحات بالضغط على الصف، أو اكتب نطاقاً ثم «تحديد». رتّب بالسحب أو بالسهمين.',
    rangeLabel: 'نطاق الصفحات',
    rangePlaceholder: '1-3,5,8-',
    rangeApply: 'تحديد',
    selectAll: 'تحديد الكل',
    clearSelection: 'إلغاء التحديد',
    selectedCount: 'المحدد: {n}',
    selectionNone: 'لم تُحدَّد صفحات. اختر صفاً أو اكتب نطاقاً أولاً.',
    rangeErrorSyntax: 'جزء غير مفهوم في النطاق: {token}',
    rangeErrorEmpty: 'اكتب نطاقاً مثل 1-3,5.',
    rangeErrorReversed: 'النطاق معكوس: {from}-{to}.',
    rangeErrorOutOfRange: 'الصفحة {page} خارج المستند ({count} صفحة).',
    pagesLimited: 'القائمة تعرض أول {n} صفحة فقط؛ لما بعدها استخدم صندوق النطاق.',
    moveUp: 'لأعلى',
    moveDown: 'لأسفل',
    dragHint: 'اسحب الصف لتغيير ترتيبه (على الجوال استخدم السهمين).',
    reorderDone: 'أُعيد ترتيب الصفحات.',
    pageN: 'صفحة {n}',

    opsTitle: 'العمليات',
    deleteTitle: 'حذف الصفحات',
    deleteDesc: 'يحذف الصفحات المحددة من النسخة العاملة. لا شيء يُحفظ تلقائياً، وزرّ إعادة التعيين يرجع بالأصل.',
    deleteApply: 'حذف المحدد',
    deleteDone: 'حُذفت {n} صفحة.',
    rotateTitle: 'تدوير الصفحات',
    rotateDesc: 'يدوّر الصفحات المحددة 90 أو 180 أو 270 درجة، والدوران يُخزَّن مع الصفحة.',
    rotate90: '90°',
    rotate180: '180°',
    rotate270: '270°',
    rotateDone: 'دُوّرت {n} صفحة.',
    cropTitle: 'القص (صندوق القص)',
    cropDesc: 'يقص هوامش بالنقاط (72 نقطة = إنش) من كل جهة. القص يخفي المحتوى عند العرض ولا يحذفه.',
    cropTop: 'أعلى',
    cropRight: 'يمين',
    cropBottom: 'أسفل',
    cropLeft: 'يسار',
    cropApply: 'تطبيق القص',
    cropDone: 'قُصّت {n} صفحة.',
    cropErrorNegative: 'الهوامش لا تكون سالبة.',
    cropErrorNoArea: 'الهوامش أكبر من الصفحة: لا تبقى مساحة.',
    watermarkTitle: 'علامة مائية نصية',
    watermarkDesc: 'يرسم النص في وسط الصفحة بالحجم والشفافية والدوران الذين تختارها، فوق المحتوى الموجود دون تعديله.',
    watermarkText: 'النص',
    watermarkSize: 'حجم الخط',
    watermarkOpacity: 'الشفافية',
    watermarkRotation: 'الدوران',
    watermarkApply: 'إضافة العلامة المائية',
    watermarkDone: 'أُضيفت العلامة المائية إلى {n} صفحة.',
    watermarkErrorText: 'اكتب نص العلامة المائية.',
    watermarkErrorSize: 'حجم الخط بين 4 و400.',
    watermarkErrorOpacity: 'الشفافية أكبر من صفر وحتى 1.',
    watermarkErrorChars: 'حروف غير مدعومة: {chars} — خطوط PDF المدمجة لاتينية فقط.',
    watermarkRotationNote: 'الدوران نسبةً إلى اتجاه الصفحة نفسها.',
    metadataTitle: 'البيانات الوصفية',
    metadataDesc: 'تُحفظ الحقول كما تظهر هنا؛ امسح الحقل لحذف قيمته. نص المستند نفسه لا يُعدَّل.',
    metadataApply: 'حفظ البيانات',
    metadataDone: 'حُفظت البيانات الوصفية.',
    keywordsHint: 'افصل الكلمات بفاصلة أو مسافة.',
    splitTitle: 'تقسيم / استخراج',
    splitDesc: 'ملف جديد لكل نطاق تكتبه: نطاق واحد = ملف واحد، ونطاقات متعددة = عدة ملفات.',
    splitApply: 'استخراج',
    splitDone: 'أُنشئ ملف: {path}',
    splitDoneMany: 'أُنشئت {n} ملفات.',
    mergeTitle: 'دمج ملفات PDF',
    mergeDesc: 'أضف ملفات من جهازك إلى ترتيب الدمج، ولكل ملف نطاق. الناتج يصبح النسخة العاملة.',
    mergeAdd: 'إضافة ملفات',
    mergeApply: 'دمج',
    mergeDone: 'دُمج {n} مصدراً في مستند من {pages} صفحة.',
    mergeEmpty: 'أضف ملفاً واحداً على الأقل غير المستند المفتوح.',
    mergeOpenDoc: 'المستند المفتوح',
    sourcePages: '{name} · {n} صفحة',
    sourceRangeLabel: 'نطاق هذا الملف',
    remove: 'إزالة',
    imagesTitle: 'صور ← PDF',
    imagesDesc: 'كل صورة في صفحة، PNG أو JPEG فقط، مع اختيار حجم الصفحة.',
    imagesAdd: 'إضافة صور',
    imagesPageSize: 'حجم الصفحة',
    imagesA4: 'A4',
    imagesLetter: 'Letter',
    imagesFit: 'مقاس الصورة',
    imagesApply: 'إنشاء PDF من الصور',
    imagesEmpty: 'أضف صورة واحدة على الأقل.',
    imagesDone: 'أُنشئ مستند من {n} صورة: {pages} صفحة.',
    imagesRefused: 'تُخطّيت {name}: {code}',
    opFailed: 'لم تُنفَّذ العملية: {message}',
    opVerified: 'تُحقّق من الناتج: {summary}',

    saveTitle: 'الحفظ',
    saveDesc: 'الحفظ الافتراضي ينشئ ملفاً جديداً بجانب الأصل ولا يلمسه. الاستبدال يحتاج تأكيداً ويكتب نسخة .bak واحدة أولاً.',
    saveTarget: 'المسار: {path}',
    saveCopy: 'حفظ كنسخة جديدة',
    saveCopySuffix: '-copy',
    saveOverwrite: 'استبدال الأصل',
    saveOverwriteConfirm: 'تأكيد الاستبدال (.bak أولاً)',
    saveOverwriteWarn: 'سيُستبدل الأصل «{name}» بالنسخة العاملة، بعد كتابة نسخة احتياطية واحدة باسم {bak}.',
    cancel: 'إلغاء',
    saveDoneCopy: 'حُفظت نسخة جديدة: {path}',
    saveDoneOverwrite: 'استُبدل الأصل، والنسخة الاحتياطية: {path}',
    saveNoBytes: 'لا توجد بيانات للحفظ (صفر بايت).',
    saveFailed: 'تعذّر الحفظ.',

    limitsTitle: 'حدود صريحة',
    limitTextEdit: 'لا تعديل لنص موجود في المستند: كلام داخل PDF لا يمكن تغييره ولا حذفه.',
    limitNoOcr: 'لا OCR: الصفحات الممسوحة تبقى صوراً ولا يُستخرج منها نص.',
    limitNoSign: 'لا توقيع رقمي ولا ختم زمني، ولا تحقّق من توقيع موجود.',
    limitNoForms: 'لا تعبئة نماذج: الحقول التفاعلية لا تُملأ ولا تُنشأ.',
    limitNoRaster: 'لا تحويل للصفحات إلى صور، فلا معاينة مصغّرة لكل صفحة، لأن المكتبة لا ترسم الصفحات.',
    limitNoFonts: 'الكتابة بخطوط PDF المدمجة (لاتينية فقط)، فلا يمكن إدراج خط عربي ولا كتابة علامة مائية عربية.',
    limitEncrypted: 'الملفات المحمية بكلمة مرور تُرفض ولا تُفتح.',
    limitQuality: 'الصور تُدرج كما هي: لا ضغط ولا تصغير.',
    limitLarge: 'الملف يُقرأ كاملاً في الذاكرة، فقد يبطؤ النظام مع الملفات الكبيرة.',
    limitList: 'قائمة الصفحات تعرض أول {n} صفحة فقط.',
  },
  en: {
    title: 'PDF Documents',
    badge: 'PDF editor',
    tabView: 'View',
    tabEdit: 'Edit',
    loading: 'Opening the file…',
    readError: 'Could not read the file from the file system.',
    noFile: 'Open a PDF from the Files app and it shows here.',
    pagesCount: '{n} pages',
    pageCountOne: '1 page',
    sizeLabel: 'Size: {size}',
    modified: 'Modified',
    reset: 'Reset to the opened file',
    resetDone: 'Back to the opened file.',
    busy: 'Working…',

    viewNoViewer: 'This browser cannot show a PDF inside the system. Download the result or open it in a tab.',
    openInTab: 'Open in a tab',
    download: 'Download the result',
    previewNote: 'The preview shows the working copy: after the in-memory edits and before saving.',

    refusalTitle: 'Could not open this file',
    refusalEmpty: 'The file is empty (zero bytes).',
    refusalNotPdf: 'This is not a PDF: it has no %PDF- header.',
    refusalEncrypted: 'The file is password-protected (encrypted) and pdf-lib refuses to open it. Remove the protection with another program and try again.',
    refusalCorrupt: 'This looks like a PDF but it could not be parsed: it may be damaged or truncated.',
    refusalImageUnsupported: 'This image is neither PNG nor JPEG, and only those two can be embedded.',
    refusalImageBroken: 'This image could not be read: its signature is right but its data is damaged or truncated.',
    refusalTextNotRenderable: 'The text holds characters the built-in PDF fonts cannot draw (Arabic, for example). Write the watermark in Latin letters.',
    refusalEmptyResult: 'This operation would leave zero pages, and I will not write an empty document.',
    refusalOutsideHome: 'Saving outside /home/user is not allowed.',
    refusalWriteFailed: 'Could not write to the file system.',
    refusalUnknown: 'The operation failed and I could not verify a valid result, so nothing was saved.',
    refusalDetail: 'Technical detail: {detail}',
    noOverwrite: 'No file was written.',

    infoTitle: 'Document info',
    infoDesc: 'The page count, each page’s size and rotation, and the current metadata.',
    infoPages: 'Pages: {n}',
    infoMetaTitle: 'Title',
    infoAuthor: 'Author',
    infoSubject: 'Subject',
    infoKeywords: 'Keywords',
    infoNone: '—',
    infoPageLine: '{w} × {h} pt · rotation {rot}°',
    infoCropLine: 'Crop: {w} × {h} at ({x}, {y})',

    pagesTitle: 'Pages',
    pagesDesc: 'Tap a row to select a page, or type a range and press “Select”. Reorder by dragging or with the arrows.',
    rangeLabel: 'Page range',
    rangePlaceholder: '1-3,5,8-',
    rangeApply: 'Select',
    selectAll: 'Select all',
    clearSelection: 'Clear selection',
    selectedCount: 'Selected: {n}',
    selectionNone: 'No pages selected. Pick a row or type a range first.',
    rangeErrorSyntax: 'Unreadable part of the range: {token}',
    rangeErrorEmpty: 'Type a range such as 1-3,5.',
    rangeErrorReversed: 'The range runs backwards: {from}-{to}.',
    rangeErrorOutOfRange: 'Page {page} is outside the document ({count} pages).',
    pagesLimited: 'The list shows only the first {n} pages; use the range box beyond that.',
    moveUp: 'Move up',
    moveDown: 'Move down',
    dragHint: 'Drag a row to reorder it (on mobile use the arrows).',
    reorderDone: 'Pages reordered.',
    pageN: 'Page {n}',

    opsTitle: 'Operations',
    deleteTitle: 'Delete pages',
    deleteDesc: 'Removes the selected pages from the working copy. Nothing is saved automatically, and reset brings the original back.',
    deleteApply: 'Delete selected',
    deleteDone: 'Deleted {n} pages.',
    rotateTitle: 'Rotate pages',
    rotateDesc: 'Turns the selected pages by 90, 180 or 270 degrees; the rotation is stored with the page.',
    rotate90: '90°',
    rotate180: '180°',
    rotate270: '270°',
    rotateDone: 'Rotated {n} pages.',
    cropTitle: 'Crop (crop box)',
    cropDesc: 'Cuts margins in points (72 pt = 1 inch) from each side. Cropping hides the content when displayed; it does not delete it.',
    cropTop: 'Top',
    cropRight: 'Right',
    cropBottom: 'Bottom',
    cropLeft: 'Left',
    cropApply: 'Apply crop',
    cropDone: 'Cropped {n} pages.',
    cropErrorNegative: 'Margins cannot be negative.',
    cropErrorNoArea: 'The margins are larger than the page: no area is left.',
    watermarkTitle: 'Text watermark',
    watermarkDesc: 'Draws the text at the centre of the page with the size, opacity and rotation you choose, over the existing content, never editing it.',
    watermarkText: 'Text',
    watermarkSize: 'Font size',
    watermarkOpacity: 'Opacity',
    watermarkRotation: 'Rotation',
    watermarkApply: 'Add watermark',
    watermarkDone: 'Watermark added to {n} pages.',
    watermarkErrorText: 'Type the watermark text.',
    watermarkErrorSize: 'The font size must be between 4 and 400.',
    watermarkErrorOpacity: 'Opacity must be above 0 and at most 1.',
    watermarkErrorChars: 'Unsupported characters: {chars} — the built-in PDF fonts are Latin only.',
    watermarkRotationNote: 'Rotation is relative to the page’s own orientation.',
    metadataTitle: 'Metadata',
    metadataDesc: 'The fields are saved exactly as shown here; clear a field to delete its value. The document’s own text is not edited.',
    metadataApply: 'Save metadata',
    metadataDone: 'Metadata saved.',
    keywordsHint: 'Separate keywords with a comma or a space.',
    splitTitle: 'Split / extract',
    splitDesc: 'A new file for every range you type: one range gives one file, several ranges give several files.',
    splitApply: 'Extract',
    splitDone: 'Created: {path}',
    splitDoneMany: 'Created {n} files.',
    mergeTitle: 'Merge PDFs',
    mergeDesc: 'Add files from your device to the merge order, with a range for each. The result becomes the working copy.',
    mergeAdd: 'Add files',
    mergeApply: 'Merge',
    mergeDone: 'Merged {n} sources into a {pages}-page document.',
    mergeEmpty: 'Add at least one file besides the open document.',
    mergeOpenDoc: 'The open document',
    sourcePages: '{name} · {n} pages',
    sourceRangeLabel: 'This file’s range',
    remove: 'Remove',
    imagesTitle: 'Images → PDF',
    imagesDesc: 'One image per page, PNG or JPEG only, with a choice of page size.',
    imagesAdd: 'Add images',
    imagesPageSize: 'Page size',
    imagesA4: 'A4',
    imagesLetter: 'Letter',
    imagesFit: 'Fit to image',
    imagesApply: 'Create a PDF from the images',
    imagesEmpty: 'Add at least one image.',
    imagesDone: 'Created a document from {n} images: {pages} pages.',
    imagesRefused: 'Skipped {name}: {code}',
    opFailed: 'The operation did not run: {message}',
    opVerified: 'Output verified: {summary}',

    saveTitle: 'Save',
    saveDesc: 'The default save creates a new file beside the original and never touches it. Replacing needs confirmation and writes one .bak copy first.',
    saveTarget: 'Target: {path}',
    saveCopy: 'Save as a new copy',
    saveCopySuffix: '-copy',
    saveOverwrite: 'Replace the original',
    saveOverwriteConfirm: 'Confirm replace (.bak first)',
    saveOverwriteWarn: 'The original “{name}” will be replaced by the working copy, after one backup is written as {bak}.',
    cancel: 'Cancel',
    saveDoneCopy: 'Saved a new copy: {path}',
    saveDoneOverwrite: 'The original was replaced; the backup is: {path}',
    saveNoBytes: 'There is nothing to save (zero bytes).',
    saveFailed: 'Saving failed.',

    limitsTitle: 'Honest limits',
    limitTextEdit: 'No editing of text already in the document: words inside a PDF cannot be changed or deleted.',
    limitNoOcr: 'No OCR: scanned pages stay images and no text is extracted from them.',
    limitNoSign: 'No digital signatures and no timestamps, and existing signatures are not verified.',
    limitNoForms: 'No form filling: interactive fields are neither filled nor created.',
    limitNoRaster: 'No page rasterising, so no per-page thumbnail, because the library does not render pages.',
    limitNoFonts: 'Drawing uses the built-in (Latin-only) PDF fonts, so an Arabic font cannot be embedded and an Arabic watermark cannot be written.',
    limitEncrypted: 'Password-protected files are refused, not opened.',
    limitQuality: 'Images are embedded as they are: no recompression and no downscaling.',
    limitLarge: 'The file is read fully into memory, which can slow the system with large files.',
    limitList: 'The page list shows only the first {n} pages.',
  },
});
