import { defineStrings } from '../../kernel/i18n';

defineStrings('browser', {
  ar: {
    title: 'المتصفح',
    newTab: 'لسان جديد',
    closeTab: 'إغلاق اللسان',
    back: 'رجوع',
    backHint: 'رجوع — يتنقّل بين الصفحات التي فتحتها هنا فقط؛ لا يمكن رؤية تنقّلك داخل الموقع نفسه (قيود المتصفح عبر النطاقات).',
    forward: 'تقدّم',
    forwardHint: 'تقدّم — الأمر نفسه: يتتبّع صفحاتك في هذا اللسان فقط، لا التنقّل داخل الموقع.',
    reload: 'تحديث',
    home: 'الصفحة الرئيسية',
    addressPlaceholder: 'ابحث في ويكيبيديا أو اكتب عنوان موقع',
    go: 'اذهب',
    openInTab: 'فتح في لسان حقيقي',
    star: 'حفظ في المفضلة',
    unstar: 'إزالة من المفضلة',
    homeSearchPlaceholder: 'ابحث في الويب',
    homeTitle: 'فيصل — تصفح آمن داخل النظام',
    homeSubtitle: 'المواقع تُعرض داخل إطار مضمّن؛ بعض المواقع الكبرى تمنع ذلك عمداً ولا توجد طريقة لتجاوز ذلك من هنا.',
    shortcuts: 'اختصارات',
    bookmarks: 'المفضلة',
    noBookmarks: 'لا توجد عناصر في المفضلة بعد. اضغط ★ بجانب أي صفحة لحفظها.',
    engineLabel: 'محرك البحث',
    engineWikipedia: 'ويكيبيديا (داخل الصفحة)',
    engineDuckDuckGo: 'DuckDuckGo (لسان جديد)',
    engineGoogle: 'Google (لسان جديد)',
    engineBing: 'Bing (لسان جديد)',
    blockedTitle: 'هذا الموقع لا يسمح بفتحه داخل مواقع أخرى',
    blockedBody: 'بعض المواقع (خاصة الشبكات الاجتماعية والبنوك والمنصات الكبرى) ترسل تعليمات صريحة لمنع عرضها داخل إطار مضمّن، حماية من هجمات clickjacking. هذا ليس خطأً في فيصل — لا توجد طريقة لتجاوزه من داخل المتصفح.',
    openReal: 'فتح في لسان حقيقي',
    refusesTitle: 'هذا الموقع يطلب عدم عرضه داخل إطار',
    refusesBody: 'هذا الموقع يطلب من المتصفح عدم عرضه داخل إطار (X-Frame-Options أو سياسة CSP)، وهذا حقّه. لا يحاول Fai$al OS تجاوز ذلك ولا تمرير المحتوى عبر وسيط — الطريقة الوحيدة للعرض هي فتح الموقع نفسه.',
    refusesOpen: 'فتح في المتصفح',
    refusesTry: 'المحاولة على أي حال',
    blankHint: 'الصفحة فارغة؟ قد يمنع هذا الموقع التضمين — جرّب فتحه في لسان حقيقي.',
    dismiss: 'إغلاق',
    tileWikipediaAr: 'ويكيبيديا (عربي)',
    tileWikipediaEn: 'ويكيبيديا (إنجليزي)',
    tileOsm: 'خرائط OpenStreetMap',
    tileYouTube: 'يوتيوب',
    tileYouTubeDesc: 'الصق رابط فيديو في شريط العنوان',
    tileArchive: 'أرشيف الإنترنت',
    tileMdn: 'توثيق MDN',
    tileBbc: 'بي بي سي عربي',
    opensInTab: 'يُفتح في لسان جديد',
    limitationsTitle: 'حدود هذا المتصفح',
    limitationsBody: 'هذا متصفح مبسّط يعمل داخل صفحة ويب واحدة. لا يمكنه رؤية عناوين الصفحات التي تُفتح داخل موقع (مثل نتائج بحث داخلية)، ولا يمكنه كشف حظر التضمين قبل المحاولة، ولا يحفظ أي سجل تصفح على القرص.',
    engineSettingsTitle: 'إعدادات البحث',
  },
  en: {
    title: 'Browser',
    newTab: 'New tab',
    closeTab: 'Close tab',
    back: 'Back',
    backHint: 'Back — only moves between pages you opened here; in-page navigation inside a site is invisible to us (cross-origin restriction).',
    forward: 'Forward',
    forwardHint: 'Forward — same limit: it tracks pages in this tab only, not navigation inside the site itself.',
    reload: 'Reload',
    home: 'Home',
    addressPlaceholder: 'Search Wikipedia or type a web address',
    go: 'Go',
    openInTab: 'Open in a real tab',
    star: 'Add bookmark',
    unstar: 'Remove bookmark',
    homeSearchPlaceholder: 'Search the web',
    homeTitle: 'Fai$al — safe browsing inside the OS',
    homeSubtitle: 'Sites are shown inside an embedded frame; some major sites deliberately block this and there is no way around it from here.',
    shortcuts: 'Shortcuts',
    bookmarks: 'Bookmarks',
    noBookmarks: 'No bookmarks yet. Tap ★ next to any page to save it.',
    engineLabel: 'Search engine',
    engineWikipedia: 'Wikipedia (in-page)',
    engineDuckDuckGo: 'DuckDuckGo (new tab)',
    engineGoogle: 'Google (new tab)',
    engineBing: 'Bing (new tab)',
    blockedTitle: "This site doesn't allow opening inside other sites",
    blockedBody: "Some sites (especially social networks, banks and major platforms) send explicit headers refusing to be shown in an embedded frame, to prevent clickjacking attacks. This isn't a Fai$al bug — there is no way to bypass it from inside the browser.",
    openReal: 'Open in a real tab',
    refusesTitle: 'This site asks not to be shown inside a frame',
    refusesBody: 'This site asks browsers not to display it inside a frame (X-Frame-Options or a CSP frame-ancestors rule), and that is its right. Fai$al OS does not try to bypass that and never proxies the content — the only way to view it is to open the site itself.',
    refusesOpen: 'Open in browser',
    refusesTry: 'Try embedding anyway',
    blankHint: 'Blank page? This site may block embedding — try opening it in a real tab.',
    dismiss: 'Dismiss',
    tileWikipediaAr: 'Wikipedia (Arabic)',
    tileWikipediaEn: 'Wikipedia (English)',
    tileOsm: 'OpenStreetMap',
    tileYouTube: 'YouTube',
    tileYouTubeDesc: 'Paste a video link in the address bar',
    tileArchive: 'Internet Archive',
    tileMdn: 'MDN Docs',
    tileBbc: 'BBC Arabic',
    opensInTab: 'Opens in a new tab',
    limitationsTitle: 'Limits of this browser',
    limitationsBody: "This is a simplified browser that runs inside a single web page. It can't see page titles from inside a site (like internal search results), can't detect an embedding block before trying, and keeps no browsing history on disk.",
    engineSettingsTitle: 'Search settings',
  },
});
