import { defineStrings } from '../../kernel/i18n';

/**
 * Every user-visible string of the video app, in both languages.
 *
 * Keys are kept in the same order in `ar` and `en` on purpose: a repo-wide parity
 * test compares the two tables key by key (see src/apps/web/strings.test.ts), and
 * reading them side by side is how a one-sided key is spotted before it ships.
 */
defineStrings('video', {
  ar: {
    title: 'استوديو الفيديو',
    badge: 'محرّر فيديو',
    openFile: 'فتح ملف',
    noFile: 'افتح ملف فيديو أو صوت من تطبيق الملفات، أو اختر ملفاً من هنا.',
    readError: 'تعذّر قراءة الملف. ربما هو تالف أو بصيغة لا يقرأها المتصفح.',
    loading: 'جارٍ فتح الملف…',
    emptyFile: 'الملف فارغ.',
    loadingMedia: 'جارٍ تحميل الوسائط…',
    kindAudio: 'ملف صوتي',

    playerTitle: 'المشغّل',
    play: 'تشغيل',
    pause: 'إيقاف',
    stop: 'إيقاف وإرجاع',
    stepBack: 'إطار للخلف',
    stepForward: 'إطار للأمام',
    volume: 'الصوت',
    mute: 'كتم',
    unmute: 'إلغاء الكتم',
    rate: 'السرعة',
    fullscreen: 'ملء الشاشة',
    fullscreenExit: 'الخروج من ملء الشاشة',
    fullscreenFailed: 'رفض المتصفح ملء الشاشة لهذه النافذة.',
    fullscreenUnsupported: 'هذا المتصفح لا يدعم ملء الشاشة.',
    timeline: 'الشريط الزمني',
    currentTime: 'الموضع',
    durationLabel: 'المدة',

    editTitle: 'القص',
    setIn: 'بداية (In)',
    setOut: 'نهاية (Out)',
    clearTrim: 'إلغاء التحديد',
    split: 'قصّ عند المؤشر',
    trimInfo: 'المحدَّد: {from} ← {to} ({len})',
    trimWhole: 'كامل المقطع (بلا تحديد)',
    addSelection: 'أضف المقطع المحدَّد إلى القائمة',
    addedToClips: 'أُضيف المقطع إلى القائمة.',

    clipsTitle: 'قائمة المقاطع',
    clipsEmpty: 'لا مقاطع بعد. حدّد البداية والنهاية ثم اضغط «أضف المقطع المحدَّد»، أو أضف الملف كاملاً.',
    addWhole: 'أضف الملف كاملاً',
    clipN: 'مقطع {n}',
    clipRange: '{from} ← {to}',
    clipLength: '{len}',
    moveUp: 'تقديم',
    moveDown: 'تأخير',
    removeClip: 'حذف',
    clipTotal: 'مجموع مدة التصدير: {total}',
    clearClips: 'حذف كل المقاطع',

    transformTitle: 'الدوران والقصّ والقلب',
    rotateLeft: 'دوران لليسار ٩٠°',
    rotateRight: 'دوران لليمين ٩٠°',
    rotate180: 'دوران ١٨٠°',
    flipH: 'قلب أفقي',
    flipV: 'قلب رأسي',
    resetTransform: 'إعادة الضبط',
    cropTitle: 'إطار القصّ (نسبة من الأصل)',
    cropX: 'من اليسار %',
    cropY: 'من الأعلى %',
    cropW: 'العرض %',
    cropH: 'الارتفاع %',
    cropReset: 'إطار كامل',
    transformState: 'الدوران {deg}° · قلب أفقي: {h} · قلب رأسي: {v} · القصّ {cw}×{ch}%',
    yes: 'نعم',
    no: 'لا',

    audioTitle: 'الصوت',
    gain: 'مضاعِف الصوت',
    gainValue: '{x}×',
    fadeIn: 'تلاشٍ للدخول (ثانية)',
    fadeOut: 'تلاشٍ للخروج (ثانية)',
    fadesInfo: 'التلاشي يُحسب على طول الصوت الناتج بعد القصّ.',
    muteExport: 'تصدير بلا صوت',

    captureTitle: 'التقاط إطار',
    captureFrame: 'احفظ الإطار الحالي PNG',
    capturing: 'جارٍ الحفظ…',
    captured: 'حُفظ الإطار في {path}',
    captureFailed: 'تعذّر حفظ الإطار. جرّب إيقاف الفيديو عند الإطار المطلوب أولاً.',
    captureTooBig: 'الإطار أكبر من حدّ الحفظ (٢٠ ميجابايت للملف). صغّر الأبعاد.',

    exportTitle: 'التصدير',
    exportFormat: 'الصيغة',
    exportButton: 'تصدير الملف المعدّل',
    exporting: 'جارٍ التصدير… {percent}%',
    exportCancel: 'إلغاء',
    exportCancelled: 'أُلغي التصدير، ولم تُحفظ أي ملف.',
    exportSaving: 'جارٍ حفظ الملف…',
    exportDone: 'تم: {path} ({size})',
    exportFailed: 'فشل التصدير: {reason}',
    exportNoEncoder: 'هذا المتصفح لا يوفّر مرمّزاً للتصدير، فلا يمكن حفظ ملف معدّل هنا.',
    exportAudioOnly: 'هذا ملف صوتي بلا صورة، والتصدير هنا للفيديو فقط: افتح ملف فيديو للقصّ والتصدير.',
    exportNoAudio: 'المصدر بلا مسار صوتي، لذا سيُصدَّر الفيديو وحده.',
    exportOverwriteBak: 'الملف موجود: سيُحفظ السابق باسم {bak} ثم يُكتب الجديد.',
    exportQuotaWarn: 'تنبيه: حدّ الحجم في هذا النظام ٢٠ ميجابايت للملف و٥٠ ميجابايت للمجموع. المدة الطويلة قد تتجاوز الحدّ فيفشل الحفظ.',
    engineLabel: 'محرّك التصدير المستخدم',
    engineWebCodecs: 'WebCodecs (VideoEncoder/AudioEncoder)',
    engineMediaRecorder: 'MediaRecorder',
    engineMeasured: 'المحرّك: {engine} · صيغة الملف: {mime} · الحجم: {size} · المدة المكتوبة: {len}',
    precisionFrame: 'دقّة القصّ المقيسة: إطار بإطار — المتصفح يدعم requestVideoFrameCallback.',
    precisionKeyframe: 'دقّة القصّ المقيسة: مقيّدة بالإطار المفتاحي (keyframe) — المتصفح لا يوفّر requestVideoFrameCallback هنا.',
    keyframeNote: 'البحث (seek) في MP4/WebM يقف عند أقرب إطار مفتاحي، لذا قد يبدأ المقطع المنتَج قبل نقطة القصّ أو بعدها بمقدار إطار إطار حتى الإطار المفتاحي التالي.',

    capsTitle: 'ما يستطيع هذا المتصفح تشغيله فعلاً',
    capsIntro: 'النتيجة أدناه مأخوذة من المتصفح نفسه الآن عبر canPlayType، لا من قائمة مفترضة.',
    capsElement: 'عنصر الوسائط',
    capsPlayable: 'يُشغَّل',
    capsNo: 'لا',
    capsMaybe: 'ربما',
    capsEncode: 'الترميز للتصدير',
    capsYes: 'مدعوم',
    capsUnknown: 'غير معروف',
    capsShow: 'اعرض الجدول',
    capsHide: 'أخفِ الجدول',
    capsUnsure: '«ربما» تعني أن المتصفح لم يتأكّد: قد يفشل الملف فعلاً عند التشغيل.',

    refuseTitle: 'لا يمكن تشغيل {ext} هنا',
    refuseBody:
      'المتصفح لا يفكّ ترميز هذه الصيغة، والملف لم يُعدّل. الصيغ التي تُشغَّل عادةً: MP4 (H.264) وWebM وOgg، وللصوت MP3 وWAV وOgg وM4A. صيغ مثل MKV وAVI غالباً لا تعمل داخل المتصفح، وحتى لو عملت في مشغّل سطح المكتب فهذا لا يعني أنها تعمل هنا.',
    refuseHint: 'حوّل الملف إلى MP4 أو WebM في برنامج خارجي ثم افتحه من جديد.',
    openAnyway: 'جرّب التشغيل على أي حال',

    capsPlayableNow: 'يُشغَّل الآن',
    capsNotNow: 'لا يُشغَّل',
    capsCheckedVia: 'طريقة الفحص: {how}',
    viaElement: 'HTMLMediaElement.canPlayType("{mime}") ← {answer}',
    viaSource: 'MediaSource.isTypeSupported("{mime}") ← {answer}',
    viaNothing: 'لا تُوجد نتيجة من المتصفح لهذه الصيغة (رفض صريح).',

    limitsTitle: 'حدود صريحة',
    limitNoEffects: 'لا مؤثّرات ولا انتقالات ثقيلة: القصّ، الدوران، القلب، إطار القصّ، الصوت والتلاشي فقط.',
    limitReencode: 'التصدير إعادة ترميز كاملة: يأخذ وقتاً بطول المقطع تقريباً، وقد يخسر جودة لأن الصورة تُعاد ضغطها.',
    limitNo4k: 'لا ضمان لدقّة ٤K: التصدير يعمل بالحجم الذي يسمح به المتصفح والمقطع المصدر.',
    limitRealtime: 'التسجيل يجري بالزمن الحقيقي: مقطع من ٣ دقائق يحتاج نحو ٣ دقائق تصديراً.',
    limitQuota: 'التخزين في هذا النظام محدود (٢٠ ميجابايت للملف، ٥٠ ميجابايت للمجموع)، والتصدير يفشل إذا تجاوزه.',
    limitAudio: 'مقاطع متعددة تُدمج بالتشغيل المتتابع؛ الانتقال بينها قد يُسمع كقطع بسيط في الصوت.',
    limitBrowser: 'الملف يعمل في المتصفح نفسه فقط: لا رفع ولا شبكة ولا خدمة خارجية.',

    aboutTitle: 'كيف يعمل التصدير',
    aboutBody:
      'يُعاد رسم كل إطار على لوحة (canvas) بالدوران والقلب والقصّ المطلوب، ويُسجَّل الصوت عبر مسار الصوت في المتصفح مع مضاعِف الصوت والتلاشي. عندما يوفّر المتصفح WebCodecs فعلياً (مع MediaStreamTrackGenerator) يُرمَّز الإطار بـ VideoEncoder، وإلا يُستخدم MediaRecorder مباشرة — والواجهة تقول أي محرّك استُخدم فعلاً بعد كل تصدير.',
  },
  en: {
    title: 'Video Studio',
    badge: 'Video editor',
    openFile: 'Open a file',
    noFile: 'Open a video or audio file from Files, or pick one here.',
    readError: 'Could not read the file. It may be damaged or in a format this browser cannot read.',
    loading: 'Opening the file…',
    emptyFile: 'The file is empty.',
    loadingMedia: 'Loading the media…',
    kindAudio: 'Audio file',

    playerTitle: 'Player',
    play: 'Play',
    pause: 'Pause',
    stop: 'Stop and rewind',
    stepBack: 'Previous frame',
    stepForward: 'Next frame',
    volume: 'Volume',
    mute: 'Mute',
    unmute: 'Unmute',
    rate: 'Speed',
    fullscreen: 'Fullscreen',
    fullscreenExit: 'Leave fullscreen',
    fullscreenFailed: 'The browser refused to make this window fullscreen.',
    fullscreenUnsupported: 'This browser has no fullscreen support.',
    timeline: 'Timeline',
    currentTime: 'Position',
    durationLabel: 'Duration',

    editTitle: 'Trim',
    setIn: 'Set In',
    setOut: 'Set Out',
    clearTrim: 'Clear selection',
    split: 'Split at playhead',
    trimInfo: 'Selected: {from} → {to} ({len})',
    trimWhole: 'Whole clip (no selection)',
    addSelection: 'Add selection to list',
    addedToClips: 'The selection was added to the list.',

    clipsTitle: 'Clip list',
    clipsEmpty: 'No clips yet. Set In and Out, then press “Add selection to list” — or add the whole file.',
    addWhole: 'Add the whole file',
    clipN: 'Clip {n}',
    clipRange: '{from} → {to}',
    clipLength: '{len}',
    moveUp: 'Move earlier',
    moveDown: 'Move later',
    removeClip: 'Remove',
    clipTotal: 'Total export length: {total}',
    clearClips: 'Remove all clips',

    transformTitle: 'Rotate, crop and flip',
    rotateLeft: 'Rotate left 90°',
    rotateRight: 'Rotate right 90°',
    rotate180: 'Rotate 180°',
    flipH: 'Flip horizontally',
    flipV: 'Flip vertically',
    resetTransform: 'Reset',
    cropTitle: 'Crop rectangle (fraction of the source)',
    cropX: 'From left %',
    cropY: 'From top %',
    cropW: 'Width %',
    cropH: 'Height %',
    cropReset: 'Full frame',
    transformState: 'Rotation {deg}° · flip H: {h} · flip V: {v} · crop {cw}×{ch}%',
    yes: 'yes',
    no: 'no',

    audioTitle: 'Audio',
    gain: 'Volume gain',
    gainValue: '{x}×',
    fadeIn: 'Fade in (seconds)',
    fadeOut: 'Fade out (seconds)',
    fadesInfo: 'The fades run across the length of the produced audio, after trimming.',
    muteExport: 'Export without audio',

    captureTitle: 'Capture a frame',
    captureFrame: 'Save the current frame as PNG',
    capturing: 'Saving…',
    captured: 'Frame saved to {path}',
    captureFailed: 'Could not save the frame. Try pausing on the exact frame first.',
    captureTooBig: 'The frame is larger than the save limit (20 MB per file). Reduce the dimensions.',

    exportTitle: 'Export',
    exportFormat: 'Format',
    exportButton: 'Export the edited file',
    exporting: 'Exporting… {percent}%',
    exportCancel: 'Cancel',
    exportCancelled: 'Export cancelled. No file was saved.',
    exportSaving: 'Saving the file…',
    exportDone: 'Done: {path} ({size})',
    exportFailed: 'Export failed: {reason}',
    exportNoEncoder: 'This browser offers no encoder for export, so an edited file cannot be saved here.',
    exportAudioOnly: 'This is an audio-only file with no picture, and export here is video only: open a video file to trim and export.',
    exportNoAudio: 'The source has no audio track, so video is exported on its own.',
    exportOverwriteBak: 'The file exists: the previous one is kept as {bak}, then the new file is written.',
    exportQuotaWarn: 'Note: this system limits a file to 20 MB and all storage to 50 MB. A long export can pass that and the save will fail.',
    engineLabel: 'Export engine actually used',
    engineWebCodecs: 'WebCodecs (VideoEncoder/AudioEncoder)',
    engineMediaRecorder: 'MediaRecorder',
    engineMeasured: 'Engine: {engine} · file format: {mime} · size: {size} · length written: {len}',
    precisionFrame: 'Measured cut precision: frame-accurate — this browser supports requestVideoFrameCallback.',
    precisionKeyframe: 'Measured cut precision: keyframe-limited — this browser has no requestVideoFrameCallback here.',
    keyframeNote: 'Seeking in MP4/WebM stops at the nearest keyframe, so a produced clip can start up to one keyframe-interval before or after the cut point.',

    capsTitle: 'What this browser can really play',
    capsIntro: 'The result below comes from the browser itself, through canPlayType, not from an assumed list.',
    capsElement: 'Media element',
    capsPlayable: 'Plays',
    capsNo: 'No',
    capsMaybe: 'Maybe',
    capsEncode: 'Export encoding',
    capsYes: 'supported',
    capsUnknown: 'unknown',
    capsShow: 'Show the table',
    capsHide: 'Hide the table',
    capsUnsure: '“Maybe” means the browser did not commit: the file may still fail when played.',

    refuseTitle: 'Cannot play {ext} here',
    refuseBody:
      'The browser cannot decode this format, and the file was not modified. Formats that usually play: MP4 (H.264), WebM and Ogg; for audio MP3, WAV, Ogg and M4A. Formats such as MKV and AVI frequently do not work inside a browser, and working in a desktop player does not mean it works here.',
    refuseHint: 'Convert the file to MP4 or WebM in an external program, then open it again.',
    openAnyway: 'Try to play it anyway',

    capsPlayableNow: 'Plays now',
    capsNotNow: 'Does not play',
    capsCheckedVia: 'How it was checked: {how}',
    viaElement: 'HTMLMediaElement.canPlayType("{mime}") → {answer}',
    viaSource: 'MediaSource.isTypeSupported("{mime}") → {answer}',
    viaNothing: 'The browser returned nothing for this format (an explicit refusal).',

    limitsTitle: 'Honest limits',
    limitNoEffects: 'No heavy effects or transitions: trim, rotate, flip, crop, audio gain and fades only.',
    limitReencode: 'Export is a full re-encode: it takes about as long as the clip, and quality can drop because the picture is compressed again.',
    limitNo4k: 'No 4K guarantee: export runs at whatever size the browser and the source allow.',
    limitRealtime: 'Recording runs in real time: a 3-minute clip needs roughly 3 minutes to export.',
    limitQuota: 'Storage here is limited (20 MB per file, 50 MB in total) and the export fails if it passes that.',
    limitAudio: 'Multiple clips are joined by playing them in sequence; the joins can be heard as a small click in the audio.',
    limitBrowser: 'The file works in this browser only: no upload, no network, no external service.',

    aboutTitle: 'How the export works',
    aboutBody:
      'Every frame is redrawn on a canvas with the requested rotation, flip and crop, and the audio goes through the browser’s audio graph with gain and fades. When the browser really offers WebCodecs (together with MediaStreamTrackGenerator) the frame is encoded by VideoEncoder; otherwise MediaRecorder is used directly — and the interface states which engine the export actually used afterwards.',
  },
});
