import { defineStrings } from '../../kernel/i18n';

/**
 * Every user-visible string of Video Studio, in both languages.
 *
 * Keys are kept in the same order in `ar` and `en` on purpose: strings.test.ts
 * compares the two tables key by key (and their {placeholders}), and reading
 * them side by side is how a one-sided key is spotted before it ships.
 */
defineStrings('video', {
  ar: {
    title: 'استوديو الفيديو',
    startSub: 'حرّر فيديوهاتك وشغّلها داخل النظام — بلا رفع ولا إنترنت.',
    home: 'الشاشة الرئيسية',
    mode: 'الوضع',
    modePlayer: 'المشغّل',
    modeEditor: 'المحرّر',
    undo: 'تراجع',
    redo: 'إعادة',
    undone: 'تم التراجع.',
    redone: 'تمت الإعادة.',
    help: 'مساعدة',
    more: 'المزيد',
    save: 'حفظ',
    saveAs: 'حفظ باسم…',
    export: 'تصدير',
    unsaved: 'تغييرات غير محفوظة',
    tools: 'الأدوات',
    close: 'إغلاق',
    closeSheet: 'إغلاق اللوحة',
    cancel: 'إلغاء',
    add: 'إضافة',
    open: 'فتح',
    import: 'استيراد',
    or: 'أو',
    untitledProject: 'مشروع بلا اسم',
    untitledText: 'نص',

    newProject: 'مشروع جديد',
    aspect169: 'أفقي · يوتيوب والعروض',
    aspect916: 'عمودي · ريلز وستوري',
    aspect11: 'مربّع · منشورات',
    aspect45: 'طولي · منشورات الخلاصة',
    aspectAuto: 'تلقائي',
    templateIntro: 'مقدّمة بعنوان',
    templateIntroHint: 'عنوان كبير ثم عنوان فرعي',
    templateIntroTitle: 'عنوان الفيديو',
    templateIntroSub: 'اكتب هنا وصفاً قصيراً',
    templateStoryName: 'قصة ٩:١٦',
    templateStoryHint: 'إطار عمودي مع تعليق',
    templateStory: 'قصتي اليوم',
    newProjectReady: 'مشروع جديد بنسبة {aspect}. أضف وسائط من اللوحة.',
    openSection: 'فتح',
    openProject: 'فتح مشروع',
    openProjectHint: 'ملف ‎.fvproj من ملفاتك',
    playVideo: 'تشغيل فيديو',
    playVideoHint: 'من الملفات إلى المشغّل مباشرة',
    importDevice: 'من الجهاز',
    importDeviceHint: 'اختر ملفات من هذا الجهاز',
    recentProjects: 'المشاريع الأخيرة',
    recentMedia: 'وسائط حديثة في ملفاتك',
    noRecentProjects: 'لا مشاريع محفوظة بعد. احفظ مشروعك بـ Ctrl+S ليظهر هنا.',
    noRecentMedia: 'لا فيديو أو صوت في ملفاتك بعد. استورد من الجهاز للبدء.',
    continueEditing: 'متابعة التحرير',
    restoreAsk: 'وُجد مشروع غير محفوظ من {time}.',
    restore: 'استعادة',
    restored: 'استُعيد المشروع غير المحفوظ.',
    restoreFailed: 'تعذّرت استعادة المشروع المحفوظ تلقائياً.',
    discard: 'تجاهل',
    discardTitle: 'تجاهل التغييرات؟',
    discardBody: 'في المشروع الحالي تغييرات غير محفوظة وستضيع.',
    closeUnsavedBody: 'في المشروع تغييرات غير محفوظة. إغلاق النافذة سيُضيعها.',
    closeExportTitle: 'التصدير ما زال يعمل',
    closeExportBody: 'إغلاق النافذة يوقف التصدير ولا يُحفظ أي ملف.',
    stopAndClose: 'إيقاف وإغلاق',

    mediaPool: 'الوسائط',
    navMedia: 'الوسائط',
    filterAll: 'الكل',
    filterVideo: 'فيديو',
    filterAudio: 'صوت',
    filterImage: 'صور',
    importFiles: 'من الملفات',
    importTitle: 'استيراد وسائط',
    imported: 'أُضيف {n} إلى الوسائط.',
    poolEmpty: 'لا وسائط بعد',
    poolEmptyHint: 'استورد فيديو أو صوتاً أو صوراً، ثم اسحبها إلى الشريط الزمني أو اضغط +.',
    addToTimeline: 'أضف {name} إلى الشريط الزمني',
    addedToTimeline: 'أُضيف {name} إلى الشريط الزمني.',
    removeFromPool: 'أزل {name} من الوسائط',
    offline: 'غير متصل — الملف مفقود',
    offlineMedia: 'لم يُعثر على {n} من ملفات المشروع. اضغط «إعادة ربط» عليها في لوحة الوسائط.',
    relink: 'إعادة ربط',
    relinkTitle: 'إعادة ربط {name}',
    relinked: 'أُعيد ربط {name}.',
    loadingMedia: 'جارٍ التحميل…',
    audioOnly: 'صوت فقط',
    notReady: 'الملف لم يجهز بعد.',
    refused: 'المتصفح لا يشغّل {ext}. حوّله إلى MP4 أو WebM ثم استورده.',
    unreadable: 'تعذّرت قراءة الملف.',
    unreadableWhy: 'تعذّرت قراءة الملف ({reason}).',
    emptyFile: 'الملف فارغ.',
    codecUnsupported: 'الترميز داخل ملف {ext} ({size}) غير مدعوم في هذا المتصفح (مثل HEVC/H.265). حوّله إلى MP4 بترميز H.264 أو إلى WebM.',
    tooBig: 'الملف أكبر من حدّ التخزين.',
    notCopied: 'لم يُنسخ {name} إلى الملفات (أكبر من الحدّ)، فلن يجده المشروع بعد إعادة الفتح.',
    searchFiles: 'ابحث بالاسم',
    scanning: 'جارٍ البحث في ملفاتك…',
    filesFound: 'وُجد {n} ملف.',
    pickerEmpty: 'لا ملفات مطابقة',
    pickerEmptyHint: 'جرّب نوعاً آخر، أو استورد من الجهاز.',
    projects: 'المشاريع',

    inspector: 'الخصائص',
    tabEdit: 'تحرير',
    tabAudio: 'صوت',
    tabText: 'نص',
    tabEffects: 'مؤثرات',
    nothingSelected: 'لم تحدّد مقطعاً',
    nothingSelectedHint: 'اضغط مقطعاً في الشريط الزمني لتعديله. هذه إعدادات المشروع:',
    projectSettings: 'المشروع',
    aspect: 'نسبة الإطار',
    background: 'لون الخلفية',
    type_video: 'فيديو',
    type_image: 'صورة',
    type_audio: 'صوت',
    type_text: 'نص',
    split: 'قصّ عند المؤشر',
    duplicate: 'تكرار',
    delete: 'حذف',
    detachAudio: 'فصل الصوت',
    captureFrame: 'حفظ الإطار PNG',
    speed: 'السرعة',
    speedNote: 'تُحفظ طبقة الصوت عند تغيير السرعة (بلا تغيّر في حدّة الصوت).',
    transform: 'الدوران والقلب',
    rotateLeft: 'تدوير لليسار',
    rotateRight: 'تدوير لليمين',
    flipH: 'قلب أفقي',
    flipV: 'قلب رأسي',
    fit: 'الملاءمة',
    fitContain: 'احتواء',
    fitCover: 'ملء',
    crop: 'القصّ',
    cropX: 'من اليسار',
    cropY: 'من الأعلى',
    cropW: 'العرض',
    cropH: 'الارتفاع',
    resetTransform: 'إعادة الضبط',
    layout: 'الحجم والموضع',
    scale: 'الحجم',
    posX: 'أفقياً',
    posY: 'رأسياً',
    opacity: 'الشفافية',
    layoutNote: 'اسحب الصورة على المعاينة لتحريكها، والمقبض في الزاوية لتكبيرها.',
    duration: 'المدة',

    volume: 'الصوت',
    muteClip: 'كتم هذا المقطع',
    fades: 'التلاشي',
    fadeIn: 'تلاشٍ للدخول',
    fadeOut: 'تلاشٍ للخروج',
    noAudioTrack: 'هذا الملف بلا مسار صوتي.',
    audioEmpty: 'حدّد مقطعاً صوتياً',
    audioEmptyHint: 'أو أضف موسيقى إلى مسار الصوت.',
    addMusic: 'إضافة موسيقى',
    tracks: 'المسارات',
    muteTrack: 'كتم المسار',
    unmuteTrack: 'إلغاء كتم المسار',
    hideTrack: 'إخفاء المسار',
    showTrack: 'إظهار المسار',

    addText: 'إضافة نص',
    addTitle: 'إضافة عنوان',
    textAdded: 'أُضيف نص عند المؤشر. اكتب نصك في اللوحة.',
    textHint: 'اختر شكلاً ليُضاف عند المؤشر، أو حدّد نصاً في الشريط الزمني لتعديله.',
    preset_title: 'عنوان',
    preset_title_sample: 'عنوان رئيسي',
    preset_subtitle: 'عنوان فرعي',
    preset_subtitle_sample: 'عنوان فرعي',
    preset_lower: 'شريط سفلي',
    preset_lower_sample: 'الاسم هنا',
    preset_caption: 'تعليق',
    preset_caption_sample: 'تعليق على المشهد',
    textContent: 'النص',
    font: 'الخط',
    font_sans: 'نسخ حديث',
    font_naskh: 'نسخ كلاسيكي',
    font_kufi: 'كوفي',
    font_display: 'عريض للعناوين',
    font_mono: 'أحادي المسافة',
    fontSize: 'حجم الخط',
    bold: 'عريض',
    align: 'المحاذاة',
    alignStart: 'البداية',
    alignCenter: 'الوسط',
    alignEnd: 'النهاية',
    colors: 'الألوان',
    textColor: 'لون النص',
    boxColor: 'خلفية النص',
    noBox: 'بلا خلفية',
    customColor: 'لون مخصّص',
    position: 'الموضع',
    posTop: 'أعلى',
    posMiddle: 'وسط',
    posBottom: 'أسفل',
    dragOnPreview: 'يمكنك سحب النص مباشرة على المعاينة.',
    animation: 'الحركة',
    animIn: 'حركة الدخول',
    animOut: 'حركة الخروج',
    animDuration: 'مدة الحركة',
    anim_none: 'بلا حركة',
    anim_fade: 'تلاشٍ',
    anim_slide: 'انزلاق',
    anim_pop: 'بروز',

    effectsEmpty: 'حدّد فيديو أو صورة',
    effectsEmptyHint: 'الألوان والانتقالات تُطبَّق على المقطع المحدد.',
    color: 'الألوان',
    brightness: 'السطوع',
    contrast: 'التباين',
    saturation: 'التشبّع',
    resetColor: 'إعادة الألوان',
    look_none: 'أصلي',
    look_vivid: 'حيوي',
    look_warm: 'دافئ',
    look_cinema: 'سينمائي',
    look_fade: 'باهت',
    look_mono: 'أبيض وأسود',
    transitions: 'الانتقالات',
    transition: 'نوع الانتقال',
    transitionDuration: 'مدة الانتقال',
    transition_none: 'بلا',
    transition_crossfade: 'مزج',
    transition_dip: 'عبر الأسود',
    transition_slide: 'انزلاق',
    transitionAll: 'طبّق على كل المقاطع',
    transitionApplied: 'طُبّق الانتقال على كل المقاطع.',
    transitionFirst: 'الانتقال يكون من المقطع السابق إلى هذا. حدّد المقطع الثاني أو ما بعده.',
    transitionMainOnly: 'الانتقالات للمسار الرئيسي فقط.',
    transitionNote: 'المزج والانزلاق يقصّران الفيلم بمدة الانتقال لأن المقطعين يتداخلان.',

    timeline: 'الشريط الزمني',
    timelineEmpty: 'اسحب وسائط هنا، أو اضغط + على بطاقة في لوحة الوسائط.',
    trackMain: 'فيديو',
    trackOverlay: 'طبقة',
    trackText: 'عناوين',
    trackAudio: 'صوت',
    trimStart: 'مقبض البداية',
    trimEnd: 'مقبض النهاية',
    snap: 'المحاذاة التلقائية',
    snapOn: 'المحاذاة التلقائية مفعّلة.',
    snapOff: 'المحاذاة التلقائية متوقفة.',
    zoom: 'تكبير الشريط الزمني',
    zoomIn: 'تكبير',
    zoomOut: 'تصغير',
    zoomFit: 'ملاءمة',
    splitDone: 'قُصّ المقطع عند المؤشر.',
    splitMissed: 'لا مقطع تحت المؤشر للقصّ.',
    deleted: 'حُذف المقطع.',
    detached: 'فُصل الصوت إلى مسار صوت، وكُتم الفيديو.',
    detachNeedsVideo: 'حدّد مقطع فيديو لفصل صوته.',
    markedIn: 'بدأ المقطع من المؤشر.',
    markedOut: 'انتهى المقطع عند المؤشر.',
    markMissed: 'ضع المؤشر داخل مقطع أولاً.',
    editorEmpty: 'ابدأ بإضافة وسائط',
    editorEmptyHint: 'استورد فيديو أو صورة أو صوتاً، ثم أضفه إلى الشريط الزمني.',

    play: 'تشغيل',
    pause: 'إيقاف مؤقت',
    stopped: 'توقّف.',
    shuttleIs: 'سرعة التنقّل {x}×',
    seekBar: 'موضع التشغيل',
    goStart: 'إلى البداية',
    goEnd: 'إلى النهاية',
    frameBack: 'إطار للخلف',
    frameForward: 'إطار للأمام',
    loop: 'تكرار',
    loopAll: 'تكرار الفيلم كاملاً.',
    loopClip: 'تكرار المقطع المحدد.',
    loopOff: 'أُوقف التكرار.',
    mute: 'كتم',
    unmute: 'إلغاء الكتم',
    fullscreen: 'ملء الشاشة',
    fullscreenFailed: 'رفض المتصفح ملء الشاشة.',
    fullscreenUnsupported: 'هذا المتصفح لا يدعم ملء الشاشة.',

    playlist: 'قائمة التشغيل',
    playlistEmpty: 'القائمة فارغة.',
    playlistHint: 'اسحب المقبض لإعادة الترتيب، واضغط مقطعاً لتشغيله.',
    addClips: 'إضافة مقاطع',
    playerEmpty: 'لا شيء للتشغيل بعد',
    playerEmptyHint: 'أضف مقطعاً أو أكثر إلى قائمة التشغيل.',
    previousClip: 'المقطع السابق',
    nextClip: 'المقطع التالي',
    removeFromPlaylist: 'أزل من القائمة',
    moveUp: 'تقديم',
    dragToReorder: 'اسحب لإعادة الترتيب',
    openInEditor: 'فتح في المحرّر',
    speedIs: 'السرعة {x}×',
    trimTool: 'القصّ',
    trimHint: 'اسحب المقبضين على شريط التشغيل لتحديد الجزء، ثم احفظه.',
    setIn: 'البداية هنا',
    setOut: 'النهاية هنا',
    resetTrim: 'كامل الملف',
    saveSelection: 'حفظ الجزء المحدد',
    selectionInfo: '{from} ← {to} · {len}',
    trimSuffix: 'مقطع',

    exportTitle: 'تصدير',
    fileName: 'اسم الملف',
    savedTo: 'يُحفظ في {dir}',
    exportKind: 'نوع التصدير',
    exportVideo: 'فيديو',
    exportAudioWav: 'صوت فقط (WAV)',
    format: 'الصيغة',
    resolution: 'الدقّة',
    resSource: 'الأصل',
    fps: 'الإطارات',
    quality: 'الجودة',
    qualityHigh: 'عالية',
    qualityMedium: 'متوسطة',
    qualityLow: 'منخفضة',
    estimate: '{w}×{h} · {fps} إطار/ث · {len} · نحو {size}',
    estimateAudio: 'صوت WAV · {len} · نحو {size}',
    noteRealtime: 'التصدير يعمل بالزمن الحقيقي: يستغرق نحو {len}. أبقِ النافذة مفتوحة.',
    noteMp4: 'MP4 (H.264) يعمل في أغلب المشغّلات والهواتف.',
    noteWebm: 'هذا المتصفح لا يسجّل MP4، لذا سيكون الملف WebM — يعمل في المتصفحات وVLC.',
    noteFellBack: 'الصيغة المطلوبة غير مدعومة للتسجيل هنا، فاستُخدمت البديلة.',
    noteWav: 'يُحسب الصوت كاملاً بسرعة (دون انتظار الزمن الحقيقي). تغيير السرعة يغيّر حدّة الصوت في هذا النوع.',
    quotaWarn: 'قد يتجاوز الملف حدّ التخزين ({max} للملف) فيفشل الحفظ. خفّض الدقة أو الجودة.',
    noRecorder: 'هذا المتصفح لا يوفّر مسجّلاً (MediaRecorder) للفيديو.',
    exportStart: 'تصدير',
    exportProgress: '{percent}% · مضى {elapsed} · متبقٍ {eta}',
    exportSaving: 'جارٍ الحفظ والتحقق…',
    exportDone: 'اكتمل.',
    exportSaved: 'حُفظ في {path} ({size}، المدة المقيسة {len}).',
    exportSavedShort: 'حُفظ: {path}',
    exportCancelled: 'أُلغي التصدير ولم يُحفظ أي ملف.',
    exportFailed: 'فشل التصدير: {reason}',
    playExport: 'تشغيل',
    showInFiles: 'عرض في الملفات',

    saveProjectTitle: 'حفظ المشروع',
    projectName: 'اسم المشروع',
    projectSaved: 'حُفظ المشروع في {path}.',
    projectOpened: 'فُتح {name}.',
    openFailed: 'تعذّر فتح {name}: {reason}',
    projectError_json: 'الملف ليس JSON صالحاً',
    projectError_format: 'ليس ملف مشروع لاستوديو الفيديو',
    projectError_version: 'نسخة المشروع أحدث من هذا التطبيق',
    projectError_shape: 'بنية المشروع ناقصة',
    saveFailed: 'تعذّر الحفظ: {reason}',
    verifyFailed: 'الملف المكتوب لا يطابق ما أُرسل',
    quotaFile: 'الملف أكبر من حدّ التخزين ({max})',
    outsideHome: 'الحفظ مسموح داخل مجلد المستخدم فقط',
    frameSaved: 'حُفظ الإطار في {path}.',

    shortcutsTitle: 'اختصارات لوحة المفاتيح',
    shortcutsNote: 'الاختصارات تعمل داخل نافذة الاستوديو فقط، ولا تعمل أثناء الكتابة في حقل نص.',
    key_playPause: 'تشغيل / إيقاف',
    key_shuttleBack: 'تشغيل للخلف (أسرع مع كل ضغطة)',
    key_shuttleStop: 'إيقاف',
    key_shuttleForward: 'تشغيل للأمام (أسرع مع كل ضغطة)',
    key_secondBack: 'ثانية للخلف',
    key_secondForward: 'ثانية للأمام',
    key_frameBack: 'إطار للخلف',
    key_frameForward: 'إطار للأمام',
    key_goStart: 'إلى البداية',
    key_goEnd: 'إلى النهاية',
    key_markIn: 'بداية المقطع عند المؤشر',
    key_markOut: 'نهاية المقطع عند المؤشر',
    key_split: 'قصّ عند المؤشر',
    key_delete: 'حذف المقطع',
    key_duplicate: 'تكرار المقطع',
    key_redo: 'إعادة',
    key_undo: 'تراجع',
    key_saveAs: 'حفظ باسم',
    key_save: 'حفظ المشروع',
    key_open: 'فتح مشروع',
    key_newProject: 'مشروع جديد',
    key_export: 'تصدير',
    key_zoomIn: 'تكبير الشريط الزمني',
    key_zoomOut: 'تصغير الشريط الزمني',
    key_zoomFit: 'ملاءمة الشريط الزمني',
    key_addText: 'إضافة عنوان',
    key_loop: 'تكرار',
    key_snap: 'المحاذاة التلقائية',
    key_fullscreen: 'ملء الشاشة',
    key_help: 'هذه القائمة',
    key_escape: 'إغلاق اللوحة أو إلغاء التحديد',

    limitsTitle: 'الحدود والصيغ',
    limitRealtime: 'تصدير الفيديو يعمل بالزمن الحقيقي: فيلم من ٣ دقائق يحتاج نحو ٣ دقائق.',
    limitReencode: 'التصدير إعادة ترميز كاملة، فقد تنخفض الجودة قليلاً عن الأصل.',
    limitFormats: 'MP4 يُصدَّر فقط إن كان المتصفح يسجّله، وإلا WebM. صيغ مثل MKV وAVI غالباً لا تُشغَّل في المتصفح.',
    limitSpeed: 'تغيير السرعة يحافظ على حدّة الصوت في المعاينة وتصدير الفيديو، أما تصدير الصوت فقط (WAV) فيغيّرها.',
    limitFonts: 'الخطوط من جهازك (لا تنزيل من الإنترنت)، فقد يختلف شكل الخط قليلاً بين الأجهزة.',
    limitQuota: 'التخزين في النظام محدود لكل ملف وللمجموع، والحفظ يفشل برسالة واضحة إذا تجاوزه.',
    limitBrowser: 'كل شيء يعمل داخل المتصفح: لا رفع ولا شبكة ولا خدمة خارجية.',
    capsTitle: 'ما يشغّله هذا المتصفح فعلاً',
    capsIntro: 'النتيجة مأخوذة من المتصفح الآن (canPlayType)، لا من قائمة مفترضة.',
    capsFormat: 'الصيغة',
    capsPlayable: 'يُشغَّل',
    capsYes: 'نعم',
    capsNo: 'لا',
    capsMaybe: 'ربما',
    recorderTitle: 'ما يستطيع تسجيله للتصدير (MediaRecorder)',
  },
  en: {
    title: 'Video Studio',
    startSub: 'Edit and play your videos inside the system — no upload, no internet.',
    home: 'Home screen',
    mode: 'Mode',
    modePlayer: 'Player',
    modeEditor: 'Editor',
    undo: 'Undo',
    redo: 'Redo',
    undone: 'Undone.',
    redone: 'Redone.',
    help: 'Help',
    more: 'More',
    save: 'Save',
    saveAs: 'Save as…',
    export: 'Export',
    unsaved: 'Unsaved changes',
    tools: 'Tools',
    close: 'Close',
    closeSheet: 'Close panel',
    cancel: 'Cancel',
    add: 'Add',
    open: 'Open',
    import: 'Import',
    or: 'or',
    untitledProject: 'Untitled project',
    untitledText: 'Text',

    newProject: 'New project',
    aspect169: 'Landscape · YouTube and slides',
    aspect916: 'Vertical · Reels and Stories',
    aspect11: 'Square · Posts',
    aspect45: 'Portrait · Feed posts',
    aspectAuto: 'Auto',
    templateIntro: 'Title intro',
    templateIntroHint: 'A big title, then a subtitle',
    templateIntroTitle: 'Your video title',
    templateIntroSub: 'Write a short description here',
    templateStoryName: '9:16 story',
    templateStoryHint: 'A vertical frame with a caption',
    templateStory: 'My story today',
    newProjectReady: 'New {aspect} project. Add media from the panel.',
    openSection: 'Open',
    openProject: 'Open project',
    openProjectHint: 'A .fvproj file from your files',
    playVideo: 'Play a video',
    playVideoHint: 'From Files straight to the player',
    importDevice: 'From device',
    importDeviceHint: 'Pick files on this device',
    recentProjects: 'Recent projects',
    recentMedia: 'Recent media in your files',
    noRecentProjects: 'No saved projects yet. Save one with Ctrl+S and it appears here.',
    noRecentMedia: 'No video or audio in your files yet. Import from your device to start.',
    continueEditing: 'Continue editing',
    restoreAsk: 'An unsaved project from {time} was found.',
    restore: 'Restore',
    restored: 'The unsaved project was restored.',
    restoreFailed: 'The autosaved project could not be restored.',
    discard: 'Discard',
    discardTitle: 'Discard changes?',
    discardBody: 'The current project has unsaved changes that will be lost.',
    closeUnsavedBody: 'The project has unsaved changes. Closing the window loses them.',
    closeExportTitle: 'An export is still running',
    closeExportBody: 'Closing the window stops the export, and no file is saved.',
    stopAndClose: 'Stop and close',

    mediaPool: 'Media',
    navMedia: 'Media',
    filterAll: 'All',
    filterVideo: 'Video',
    filterAudio: 'Audio',
    filterImage: 'Images',
    importFiles: 'From Files',
    importTitle: 'Import media',
    imported: '{n} added to Media.',
    poolEmpty: 'No media yet',
    poolEmptyHint: 'Import video, audio or images, then drag them onto the timeline or press +.',
    addToTimeline: 'Add {name} to the timeline',
    addedToTimeline: '{name} was added to the timeline.',
    removeFromPool: 'Remove {name} from Media',
    offline: 'Offline — file missing',
    offlineMedia: '{n} of the project files were not found. Press “Relink” on them in the Media panel.',
    relink: 'Relink',
    relinkTitle: 'Relink {name}',
    relinked: '{name} was relinked.',
    loadingMedia: 'Loading…',
    audioOnly: 'Audio only',
    notReady: 'The file is not ready yet.',
    refused: 'This browser cannot play {ext}. Convert it to MP4 or WebM, then import it.',
    unreadable: 'The file could not be read.',
    unreadableWhy: 'The file could not be read ({reason}).',
    emptyFile: 'The file is empty.',
    codecUnsupported: 'The codec inside this {ext} file ({size}) is not supported by this browser (for example HEVC/H.265). Convert it to MP4 with H.264, or to WebM.',
    tooBig: 'The file is larger than the storage limit.',
    notCopied: '{name} was not copied into Files (over the limit), so a saved project will not find it again.',
    searchFiles: 'Search by name',
    scanning: 'Looking through your files…',
    filesFound: '{n} files found.',
    pickerEmpty: 'No matching files',
    pickerEmptyHint: 'Try another type, or import from your device.',
    projects: 'Projects',

    inspector: 'Properties',
    tabEdit: 'Edit',
    tabAudio: 'Audio',
    tabText: 'Text',
    tabEffects: 'Effects',
    nothingSelected: 'Nothing selected',
    nothingSelectedHint: 'Tap a clip on the timeline to edit it. These are the project settings:',
    projectSettings: 'Project',
    aspect: 'Aspect ratio',
    background: 'Background colour',
    type_video: 'Video',
    type_image: 'Image',
    type_audio: 'Audio',
    type_text: 'Text',
    split: 'Split at playhead',
    duplicate: 'Duplicate',
    delete: 'Delete',
    detachAudio: 'Detach audio',
    captureFrame: 'Save frame as PNG',
    speed: 'Speed',
    speedNote: 'The pitch of the sound is kept when the speed changes.',
    transform: 'Rotate and flip',
    rotateLeft: 'Rotate left',
    rotateRight: 'Rotate right',
    flipH: 'Flip horizontal',
    flipV: 'Flip vertical',
    fit: 'Fit',
    fitContain: 'Fit',
    fitCover: 'Fill',
    crop: 'Crop',
    cropX: 'From left',
    cropY: 'From top',
    cropW: 'Width',
    cropH: 'Height',
    resetTransform: 'Reset',
    layout: 'Size and position',
    scale: 'Size',
    posX: 'Horizontal',
    posY: 'Vertical',
    opacity: 'Opacity',
    layoutNote: 'Drag the picture on the preview to move it, and the corner handle to resize it.',
    duration: 'Duration',

    volume: 'Volume',
    muteClip: 'Mute this clip',
    fades: 'Fades',
    fadeIn: 'Fade in',
    fadeOut: 'Fade out',
    noAudioTrack: 'This file has no audio track.',
    audioEmpty: 'Select an audio clip',
    audioEmptyHint: 'Or add music to an audio track.',
    addMusic: 'Add music',
    tracks: 'Tracks',
    muteTrack: 'Mute track',
    unmuteTrack: 'Unmute track',
    hideTrack: 'Hide track',
    showTrack: 'Show track',

    addText: 'Add text',
    addTitle: 'Add title',
    textAdded: 'Text added at the playhead. Type yours in the panel.',
    textHint: 'Pick a style to add it at the playhead, or select a text on the timeline to edit it.',
    preset_title: 'Title',
    preset_title_sample: 'Main title',
    preset_subtitle: 'Subtitle',
    preset_subtitle_sample: 'A subtitle',
    preset_lower: 'Lower third',
    preset_lower_sample: 'Name here',
    preset_caption: 'Caption',
    preset_caption_sample: 'A caption for the scene',
    textContent: 'Text',
    font: 'Font',
    font_sans: 'Modern sans',
    font_naskh: 'Classic naskh',
    font_kufi: 'Kufi',
    font_display: 'Bold display',
    font_mono: 'Monospace',
    fontSize: 'Font size',
    bold: 'Bold',
    align: 'Alignment',
    alignStart: 'Start',
    alignCenter: 'Centre',
    alignEnd: 'End',
    colors: 'Colours',
    textColor: 'Text colour',
    boxColor: 'Text background',
    noBox: 'No background',
    customColor: 'Custom colour',
    position: 'Position',
    posTop: 'Top',
    posMiddle: 'Middle',
    posBottom: 'Bottom',
    dragOnPreview: 'You can drag the text directly on the preview.',
    animation: 'Animation',
    animIn: 'In animation',
    animOut: 'Out animation',
    animDuration: 'Animation length',
    anim_none: 'None',
    anim_fade: 'Fade',
    anim_slide: 'Slide',
    anim_pop: 'Pop',

    effectsEmpty: 'Select a video or image',
    effectsEmptyHint: 'Colour and transitions apply to the selected clip.',
    color: 'Colour',
    brightness: 'Brightness',
    contrast: 'Contrast',
    saturation: 'Saturation',
    resetColor: 'Reset colour',
    look_none: 'Original',
    look_vivid: 'Vivid',
    look_warm: 'Warm',
    look_cinema: 'Cinema',
    look_fade: 'Faded',
    look_mono: 'Black & white',
    transitions: 'Transitions',
    transition: 'Transition type',
    transitionDuration: 'Transition length',
    transition_none: 'None',
    transition_crossfade: 'Crossfade',
    transition_dip: 'Dip to black',
    transition_slide: 'Slide',
    transitionAll: 'Apply to all clips',
    transitionApplied: 'The transition was applied to every clip.',
    transitionFirst: 'A transition goes from the previous clip into this one. Select the second clip or a later one.',
    transitionMainOnly: 'Transitions are for the main track only.',
    transitionNote: 'Crossfade and slide shorten the film by the transition length, because the two clips overlap.',

    timeline: 'Timeline',
    timelineEmpty: 'Drag media here, or press + on a card in the Media panel.',
    trackMain: 'Video',
    trackOverlay: 'Overlay',
    trackText: 'Titles',
    trackAudio: 'Audio',
    trimStart: 'Start handle',
    trimEnd: 'End handle',
    snap: 'Snapping',
    snapOn: 'Snapping is on.',
    snapOff: 'Snapping is off.',
    zoom: 'Timeline zoom',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    zoomFit: 'Fit',
    splitDone: 'The clip was split at the playhead.',
    splitMissed: 'There is no clip under the playhead to split.',
    deleted: 'The clip was deleted.',
    detached: 'The sound moved to an audio track, and the video was muted.',
    detachNeedsVideo: 'Select a video clip to detach its sound.',
    markedIn: 'The clip now starts at the playhead.',
    markedOut: 'The clip now ends at the playhead.',
    markMissed: 'Put the playhead inside a clip first.',
    editorEmpty: 'Start by adding media',
    editorEmptyHint: 'Import a video, image or sound, then add it to the timeline.',

    play: 'Play',
    pause: 'Pause',
    stopped: 'Stopped.',
    shuttleIs: 'Shuttle speed {x}×',
    seekBar: 'Playback position',
    goStart: 'Go to start',
    goEnd: 'Go to end',
    frameBack: 'Previous frame',
    frameForward: 'Next frame',
    loop: 'Loop',
    loopAll: 'Looping the whole film.',
    loopClip: 'Looping the selected clip.',
    loopOff: 'Loop is off.',
    mute: 'Mute',
    unmute: 'Unmute',
    fullscreen: 'Fullscreen',
    fullscreenFailed: 'The browser refused fullscreen.',
    fullscreenUnsupported: 'This browser has no fullscreen support.',

    playlist: 'Playlist',
    playlistEmpty: 'The playlist is empty.',
    playlistHint: 'Drag the handle to reorder, and tap a clip to play it.',
    addClips: 'Add clips',
    playerEmpty: 'Nothing to play yet',
    playerEmptyHint: 'Add one or more clips to the playlist.',
    previousClip: 'Previous clip',
    nextClip: 'Next clip',
    removeFromPlaylist: 'Remove from playlist',
    moveUp: 'Move up',
    dragToReorder: 'Drag to reorder',
    openInEditor: 'Open in editor',
    speedIs: 'Speed {x}×',
    trimTool: 'Trim',
    trimHint: 'Drag the two handles on the seek bar to pick the part, then save it.',
    setIn: 'Start here',
    setOut: 'End here',
    resetTrim: 'Whole file',
    saveSelection: 'Save selection',
    selectionInfo: '{from} → {to} · {len}',
    trimSuffix: 'clip',

    exportTitle: 'Export',
    fileName: 'File name',
    savedTo: 'Saved in {dir}',
    exportKind: 'Export type',
    exportVideo: 'Video',
    exportAudioWav: 'Audio only (WAV)',
    format: 'Format',
    resolution: 'Resolution',
    resSource: 'Source',
    fps: 'Frame rate',
    quality: 'Quality',
    qualityHigh: 'High',
    qualityMedium: 'Medium',
    qualityLow: 'Low',
    estimate: '{w}×{h} · {fps} fps · {len} · about {size}',
    estimateAudio: 'WAV audio · {len} · about {size}',
    noteRealtime: 'Export runs in real time: it takes about {len}. Keep the window open.',
    noteMp4: 'MP4 (H.264) plays in most players and phones.',
    noteWebm: 'This browser cannot record MP4, so the file is WebM — it plays in browsers and VLC.',
    noteFellBack: 'The format you chose cannot be recorded here, so the other one is used.',
    noteWav: 'The sound is computed quickly (not in real time). In this mode a speed change also changes the pitch.',
    quotaWarn: 'The file may pass the storage limit ({max} per file) and fail to save. Lower the resolution or quality.',
    noRecorder: 'This browser offers no video recorder (MediaRecorder).',
    exportStart: 'Export',
    exportProgress: '{percent}% · {elapsed} elapsed · {eta} left',
    exportSaving: 'Saving and checking…',
    exportDone: 'Done.',
    exportSaved: 'Saved to {path} ({size}, measured length {len}).',
    exportSavedShort: 'Saved: {path}',
    exportCancelled: 'Export cancelled. No file was saved.',
    exportFailed: 'Export failed: {reason}',
    playExport: 'Play',
    showInFiles: 'Show in Files',

    saveProjectTitle: 'Save project',
    projectName: 'Project name',
    projectSaved: 'Project saved to {path}.',
    projectOpened: '{name} opened.',
    openFailed: 'Could not open {name}: {reason}',
    projectError_json: 'the file is not valid JSON',
    projectError_format: 'it is not a Video Studio project',
    projectError_version: 'the project is newer than this app',
    projectError_shape: 'the project structure is incomplete',
    saveFailed: 'Could not save: {reason}',
    verifyFailed: 'the written file does not match what was sent',
    quotaFile: 'the file is larger than the storage limit ({max})',
    outsideHome: 'saving is only allowed inside the user folder',
    frameSaved: 'Frame saved to {path}.',

    shortcutsTitle: 'Keyboard shortcuts',
    shortcutsNote: 'Shortcuts work inside the Studio window only, and not while typing in a text field.',
    key_playPause: 'Play / pause',
    key_shuttleBack: 'Play backwards (faster each press)',
    key_shuttleStop: 'Stop',
    key_shuttleForward: 'Play forwards (faster each press)',
    key_secondBack: 'One second back',
    key_secondForward: 'One second forward',
    key_frameBack: 'Previous frame',
    key_frameForward: 'Next frame',
    key_goStart: 'Go to start',
    key_goEnd: 'Go to end',
    key_markIn: 'Clip starts at the playhead',
    key_markOut: 'Clip ends at the playhead',
    key_split: 'Split at playhead',
    key_delete: 'Delete clip',
    key_duplicate: 'Duplicate clip',
    key_redo: 'Redo',
    key_undo: 'Undo',
    key_saveAs: 'Save as',
    key_save: 'Save project',
    key_open: 'Open project',
    key_newProject: 'New project',
    key_export: 'Export',
    key_zoomIn: 'Zoom the timeline in',
    key_zoomOut: 'Zoom the timeline out',
    key_zoomFit: 'Fit the timeline',
    key_addText: 'Add a title',
    key_loop: 'Loop',
    key_snap: 'Snapping',
    key_fullscreen: 'Fullscreen',
    key_help: 'This list',
    key_escape: 'Close the panel or clear the selection',

    limitsTitle: 'Limits and formats',
    limitRealtime: 'Video export runs in real time: a 3-minute film takes about 3 minutes.',
    limitReencode: 'Export is a full re-encode, so quality can be slightly below the original.',
    limitFormats: 'MP4 is exported only when the browser can record it; otherwise WebM. Formats such as MKV and AVI often do not play in a browser.',
    limitSpeed: 'Speed changes keep the pitch in the preview and in video export; audio-only export (WAV) changes it.',
    limitFonts: 'Fonts come from your device (nothing is downloaded), so a font can look slightly different between devices.',
    limitQuota: 'Storage in the system is limited per file and in total; a save that passes it fails with a clear message.',
    limitBrowser: 'Everything runs inside the browser: no upload, no network, no outside service.',
    capsTitle: 'What this browser really plays',
    capsIntro: 'This comes from the browser right now (canPlayType), not from an assumed list.',
    capsFormat: 'Format',
    capsPlayable: 'Plays',
    capsYes: 'Yes',
    capsNo: 'No',
    capsMaybe: 'Maybe',
    recorderTitle: 'What it can record for export (MediaRecorder)',
  },
});
