#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev 2>/dev/null
mkdir -p /dev/pts /tmp /root
mount -t tmpfs tmpfs /tmp
hostname faisal-vm
stty -F /dev/ttyS0 sane 2>/dev/null
cat /etc/motd
