import { defineStrings } from '../kernel/i18n';

defineStrings('shell', {
  ar: {
    activities: 'الأنشطة',
    'win.minimize': 'تصغير',
    'win.maximize': 'تكبير/استعادة',
    'win.close': 'إغلاق',
    'search.placeholder': 'اكتب للبحث عن تطبيق…',
    'overview.empty': 'لا توجد نتائج',
    'overview.openWindows': 'النوافذ المفتوحة',
    'menu.appearance': 'المظهر',
    'menu.theme.light': 'فاتح',
    'menu.theme.dark': 'داكن',
    'menu.theme.system': 'النظام',
    'menu.language': 'اللغة',
    'menu.language.ar': 'العربية',
    'menu.language.en': 'English',
    'menu.about': 'حول Fai$al OS',
    'menu.fullscreen': 'ملء الشاشة (يفعّل زر الويندوز)',
    'menu.exitFullscreen': 'الخروج من ملء الشاشة',
    'notif.dismiss': 'إغلاق الإشعار',
  },
  en: {
    activities: 'Activities',
    'win.minimize': 'Minimize',
    'win.maximize': 'Maximize / Restore',
    'win.close': 'Close',
    'search.placeholder': 'Type to search apps…',
    'overview.empty': 'No results',
    'overview.openWindows': 'Open Windows',
    'menu.appearance': 'Appearance',
    'menu.theme.light': 'Light',
    'menu.theme.dark': 'Dark',
    'menu.theme.system': 'System',
    'menu.language': 'Language',
    'menu.language.ar': 'العربية',
    'menu.language.en': 'English',
    'menu.about': 'About Fai$al OS',
    'menu.fullscreen': 'Full screen (enables the Windows key)',
    'menu.exitFullscreen': 'Exit full screen',
    'notif.dismiss': 'Dismiss notification',
  },
});
