import { defineStrings } from '../kernel/i18n';

defineStrings('shell', {
  ar: {
    activities: 'الأنشطة',
    'win.minimize': 'تصغير',
    'win.maximize': 'تكبير/استعادة',
    'win.close': 'إغلاق',
    'search.placeholder': 'اكتب للبحث عن تطبيق…',
    'overview.empty': 'لا توجد نتائج',
    'overview.openWindows': 'النوافذ المفتوحة',
    'overview.webApps': 'تطبيقات الويب',
    'menu.appearance': 'المظهر',
    'menu.theme.light': 'فاتح',
    'menu.theme.dark': 'داكن',
    'menu.theme.system': 'النظام',
    'menu.language': 'اللغة',
    'menu.language.ar': 'العربية',
    'menu.language.en': 'English',
    'menu.about': 'حول Fai$al OS',
    'menu.fullscreen': 'ملء الشاشة (يفعّل زر الويندوز)',
    'menu.exitFullscreen': 'الخروج من ملء الشاشة',
    'notif.dismiss': 'إغلاق الإشعار',
    'notif.title': 'الإشعارات',
    'notif.clear': 'مسح الكل',
    'notif.empty': 'لا توجد إشعارات',
    'notif.dnd': 'عدم الإزعاج',
    'update.title': 'تحديث جديد لـ Fai$al OS',
    'update.body': 'أغلق كل تبويبات النظام ثم افتحه من جديد لتفعيل التحديث.',
    'update.reload': 'تم تحديث النظام أثناء فتحه. أعد تحميل الصفحة لفتح هذا التطبيق.',
    'menu.screenshot': 'لقطة شاشة (Win+Shift+S)',
    'menu.clipboard': 'الحافظة (Ctrl+Alt+V)',
    'clip.title': 'الحافظة',
    'clip.clear': 'مسح الكل',
    'clip.empty': 'ما نسخت شيئاً بعد. أي نص تنسخه في النظام يظهر هنا.',
    'clip.hint': 'اختر عنصراً لتلصقه حيث كنت تكتب. الأسهم للتنقل، Delete للحذف، Esc للإغلاق.',
    'clip.remove': 'حذف من الحافظة',
    'clip.close': 'إغلاق',
    'drop.saved': 'حُفظ في {place}',
    'drop.failed': 'تعذّر حفظ {count} من الملفات',
    'drop.quota': 'المساحة المتاحة لا تكفي (الحد {file} للملف و{total} للكل).',
    'drop.copy': 'نسخة',
    'drop.into': 'أفلِت في {name}',
    'drop.here': 'هنا',
    'drop.desktop': 'سطح المكتب',
    'drop.downloads': 'التنزيلات',
    'dnd.askTitle': 'نسخة أو نقل؟',
    'dnd.askBody': '«{name}» — نسخة تُبقي الأصل، أو نقل ينقله إلى هنا.',
    'dnd.move': 'نقل',
    'dnd.cancel': 'إلغاء',
    'dnd.countFiles': '{count} عناصر',
    'dnd.copied': 'نُسخ إلى {place}',
    'dnd.moved': 'انتقل إلى {place}',
    'dnd.refused': 'ما تمّت العملية',
    'dnd.refusedSelf': 'ما ينفع تنقل العنصر إلى نفسه.',
    'dnd.refusedSubtree': 'ما ينفع تنقل مجلداً إلى داخل نفسه.',
    'dnd.refusedSameParent': 'العنصر أصلاً في هذا المكان.',
    'dnd.refusedNameTaken': 'فيه عنصر بنفس الاسم في المكان المقصود.',
    'dnd.refusedNotDirectory': 'المكان المقصود مو مجلد.',
    'dnd.refusedMissing': 'المكان المقصود ما هو موجود.',
    'dnd.refusedUnknown': 'تعذّرت العملية.',
    'clip.copied': 'نُسخ إلى الحافظة',
    'clip.copiedBody': 'الصقه بـ Ctrl+V حيث تريد.',
    'shot.hint': 'اسحب لتحديد منطقة',
    'shot.full': 'الشاشة كاملة',
    'shot.cancel': 'إلغاء',
    'shot.saved': 'تم حفظ لقطة الشاشة في الصور',
    'shot.failed': 'تعذّر حفظ لقطة الشاشة',

    // Context menus
    'ctx.open': 'فتح',
    'ctx.newWindow': 'نافذة جديدة',
    'ctx.addToDesktop': 'إضافة إلى سطح المكتب',
    'ctx.removeFromDesktop': 'إزالة من سطح المكتب',
    'ctx.addToDash': 'تثبيت في اللوحة',
    'ctx.removeFromDash': 'إزالة من اللوحة',
    'ctx.appDetails': 'تفاصيل التطبيق',
    'ctx.uninstall': 'إزالة التثبيت',

    'ctx.openFiles': 'فتح الملفات',
    'ctx.openInFiles': 'فتح في الملفات',
    'ctx.delete': 'حذف',
    'ctx.openTerminal': 'فتح الطرفية',
    'ctx.newFolder': 'مجلد جديد',
    'ctx.changeBackground': 'تغيير الخلفية…',
    'ctx.display': 'العرض',
    'ctx.displayDark': 'التبديل إلى الوضع الداكن',
    'ctx.displayLight': 'التبديل إلى الوضع الفاتح',
    'ctx.arrangeIcons': 'ترتيب الأيقونات',
    'ctx.about': 'حول Fai$al OS',

    'ctx.minimize': 'تصغير',
    'ctx.maximizeWindow': 'تكبير',
    'ctx.restoreWindow': 'استعادة',
    'ctx.alwaysOnTop': 'البقاء في الأعلى دائماً',
    'ctx.closeWindow': 'إغلاق',

    'uninstall.title': 'إزالة تثبيت {name}؟',
    'uninstall.body': 'سيتم إغلاق كل نوافذ {name} وإزالته من الجهاز. يمكنك تثبيته من جديد لاحقاً من المتجر.',
    'uninstall.confirm': 'إزالة التثبيت',
    'uninstall.cancel': 'إلغاء',
    'uninstall.done': 'تمت إزالة تثبيت {name}',

    'desktop.newFolder': 'مجلد جديد',

    // Desktop entries (files and folders living in ~/Desktop)
    'fileDelete.title': 'حذف {name}؟',
    'fileDelete.fileBody': 'سيُحذف الملف نهائيًا من نظام الملفات.',
    'fileDelete.folderBody': 'سيُحذف المجلد وكل ما فيه نهائيًا من نظام الملفات.',
    'fileDelete.failed': 'تعذّر حذف {name}',

    // Session lock (opt-in privacy curtain)
    'lock.title': 'شاشة القفل',
    'lock.subtitle': 'أدخل كلمة المرور لفتح جلستك',
    'lock.password': 'كلمة المرور',
    'lock.confirm': 'تأكيد كلمة المرور',
    'lock.hint': 'تلميح (اختياري)',
    'lock.unlock': 'فتح',
    'lock.save': 'تعيين',
    'lock.remove': 'إزالة القفل',
    'lock.now': 'قفل الجلسة',
    'lock.change': 'كلمة مرور القفل…',
    'lock.setTitle': 'تعيين كلمة مرور القفل',
    'lock.setSubtitle': 'اختر كلمة مرور خاصة بك، ويمكنك تغييرها أو إزالتها لاحقًا.',
    'lock.manageTitle': 'إدارة كلمة مرور القفل',
    'lock.manageSubtitle': 'أدخل كلمة المرور الحالية للمتابعة.',
    'lock.current': 'كلمة المرور الحالية',
    'lock.continue': 'متابعة',
    'lock.changeTitle': 'تغيير كلمة مرور القفل',
    'lock.errShort': 'قصيرة جدًا — ٤ أحرف على الأقل',
    'lock.errMismatch': 'كلمتا المرور غير متطابقتين',
    'lock.errWrong': 'كلمة المرور غير صحيحة',
    'lock.errUnsupported': 'هذا المتصفح لا يوفّر WebCrypto',
    'lock.warnWeak': 'تم التعيين — أقل من ٨ أحرف، والأفضل أطول',
    'lock.hintShown': 'تلميحك',
    'lock.forgot': 'نسيت كلمة المرور؟ لا يوجد باب خلفي: أدوات المطوّر ← Application ← Local Storage ← احذف المفتاح faisal.lock.record (أو امسح بيانات الموقع، وستفقد معها ملفات النظام).',
    'lock.scope': 'هذا حاجز خصوصية داخل الصفحة، لا تشفيرًا للجهاز: من يملك ملف تعريف المتصفح يستطيع تجاوزه. الحماية الحقيقية هي قفل نظام التشغيل.',
  },
  en: {
    activities: 'Activities',
    'win.minimize': 'Minimize',
    'win.maximize': 'Maximize / Restore',
    'win.close': 'Close',
    'search.placeholder': 'Type to search apps…',
    'overview.empty': 'No results',
    'overview.openWindows': 'Open Windows',
    'overview.webApps': 'Web Apps',
    'menu.appearance': 'Appearance',
    'menu.theme.light': 'Light',
    'menu.theme.dark': 'Dark',
    'menu.theme.system': 'System',
    'menu.language': 'Language',
    'menu.language.ar': 'العربية',
    'menu.language.en': 'English',
    'menu.about': 'About Fai$al OS',
    'menu.fullscreen': 'Full screen (enables the Windows key)',
    'menu.exitFullscreen': 'Exit full screen',
    'notif.dismiss': 'Dismiss notification',
    'notif.title': 'Notifications',
    'notif.clear': 'Clear all',
    'notif.empty': 'No notifications',
    'notif.dnd': 'Do not disturb',
    'update.title': 'Fai$al OS update ready',
    'update.body': 'Close every Fai$al OS tab and open it again to use the new version.',
    'update.reload': 'The system was updated while it was open. Reload the page to open this app.',
    'menu.screenshot': 'Screenshot (Win+Shift+S)',
    'menu.clipboard': 'Clipboard (Ctrl+Alt+V)',
    'clip.title': 'Clipboard',
    'clip.clear': 'Clear all',
    'clip.empty': 'Nothing copied yet. Any text you copy in the OS shows up here.',
    'clip.hint': 'Pick an item to paste it where you were typing. Arrows to move, Delete to remove, Esc to close.',
    'clip.remove': 'Remove from clipboard',
    'clip.close': 'Close',
    'drop.saved': 'Saved to {place}',
    'drop.failed': 'Could not save {count} file(s)',
    'drop.quota': 'Not enough space (limit {file} per file, {total} in total).',
    'drop.copy': 'copy',
    'drop.into': 'Drop into {name}',
    'drop.here': 'here',
    'drop.desktop': 'Desktop',
    'drop.downloads': 'Downloads',
    'dnd.askTitle': 'Copy or move?',
    'dnd.askBody': '“{name}” — copy keeps the original, move puts it here.',
    'dnd.move': 'Move',
    'dnd.cancel': 'Cancel',
    'dnd.countFiles': '{count} items',
    'dnd.copied': 'Copied to {place}',
    'dnd.moved': 'Moved to {place}',
    'dnd.refused': 'Nothing changed',
    'dnd.refusedSelf': 'An item cannot be moved into itself.',
    'dnd.refusedSubtree': 'A folder cannot be moved into itself.',
    'dnd.refusedSameParent': 'The item is already in that place.',
    'dnd.refusedNameTaken': 'A file with that name is already there.',
    'dnd.refusedNotDirectory': 'That place is not a folder.',
    'dnd.refusedMissing': 'That place does not exist.',
    'dnd.refusedUnknown': 'The operation could not be done.',
    'clip.copied': 'Copied to the clipboard',
    'clip.copiedBody': 'Paste it with Ctrl+V wherever you like.',
    'shot.hint': 'Drag to select an area',
    'shot.full': 'Full screen',
    'shot.cancel': 'Cancel',
    'shot.saved': 'Screenshot saved to Pictures',
    'shot.failed': 'Could not save the screenshot',

    // Context menus
    'ctx.open': 'Open',
    'ctx.newWindow': 'New window',
    'ctx.addToDesktop': 'Add to desktop',
    'ctx.removeFromDesktop': 'Remove from desktop',
    'ctx.addToDash': 'Add to dash',
    'ctx.removeFromDash': 'Remove from dash',
    'ctx.appDetails': 'App details',
    'ctx.uninstall': 'Uninstall',

    'ctx.openFiles': 'Open Files',
    'ctx.openInFiles': 'Open in Files',
    'ctx.delete': 'Delete',
    'ctx.openTerminal': 'Open Terminal',
    'ctx.newFolder': 'New folder',
    'ctx.changeBackground': 'Change background…',
    'ctx.display': 'Display',
    'ctx.displayDark': 'Switch to dark mode',
    'ctx.displayLight': 'Switch to light mode',
    'ctx.arrangeIcons': 'Arrange icons',
    'ctx.about': 'About Fai$al OS',

    'ctx.minimize': 'Minimize',
    'ctx.maximizeWindow': 'Maximize',
    'ctx.restoreWindow': 'Restore',
    'ctx.alwaysOnTop': 'Always on top',
    'ctx.closeWindow': 'Close',

    'uninstall.title': 'Uninstall {name}?',
    'uninstall.body': 'All windows of {name} will close and it will be removed from this device. You can reinstall it later from the Store.',
    'uninstall.confirm': 'Uninstall',
    'uninstall.cancel': 'Cancel',
    'uninstall.done': '{name} was uninstalled',

    'desktop.newFolder': 'New folder',

    // Desktop entries (files and folders living in ~/Desktop)
    'fileDelete.title': 'Delete {name}?',
    'fileDelete.fileBody': 'This file will be permanently removed from the file system.',
    'fileDelete.folderBody': 'This folder and everything inside it will be permanently removed from the file system.',
    'fileDelete.failed': 'Could not delete {name}',

    // Session lock (opt-in privacy curtain)
    'lock.title': 'Lock screen',
    'lock.subtitle': 'Enter your password to unlock this session',
    'lock.password': 'Password',
    'lock.confirm': 'Confirm password',
    'lock.hint': 'Hint (optional)',
    'lock.unlock': 'Unlock',
    'lock.save': 'Set password',
    'lock.remove': 'Remove lock',
    'lock.now': 'Lock session',
    'lock.change': 'Lock password…',
    'lock.setTitle': 'Set a lock password',
    'lock.setSubtitle': 'Pick your own password; you can change or remove it later.',
    'lock.manageTitle': 'Manage the lock password',
    'lock.manageSubtitle': 'Enter the current password to continue.',
    'lock.current': 'Current password',
    'lock.continue': 'Continue',
    'lock.changeTitle': 'Change the lock password',
    'lock.errShort': 'Too short — 4 characters minimum',
    'lock.errMismatch': 'The two passwords do not match',
    'lock.errWrong': 'Wrong password',
    'lock.errUnsupported': 'This browser has no WebCrypto',
    'lock.warnWeak': 'Set — under 8 characters; longer is better',
    'lock.hintShown': 'Your hint',
    'lock.forgot': 'Forgot the password? There is no back door: DevTools → Application → Local Storage → delete the key faisal.lock.record (or clear site data, which also deletes the OS files).',
    'lock.scope': 'This is a privacy curtain inside the page, not device encryption: whoever owns the browser profile can bypass it. Real protection is the operating system login.',
  },
});
