import { defineStrings } from '../kernel/i18n';

defineStrings('shell', {
  ar: {
    activities: 'الأنشطة',
    'win.minimize': 'تصغير',
    'win.maximize': 'تكبير/استعادة',
    'win.close': 'إغلاق',
    'search.placeholder': 'اكتب للبحث عن تطبيق…',
    'overview.empty': 'لا توجد نتائج',
    'overview.openWindows': 'النوافذ المفتوحة',
    'overview.webApps': 'تطبيقات الويب',
    'menu.appearance': 'المظهر',
    'menu.theme.light': 'فاتح',
    'menu.theme.dark': 'داكن',
    'menu.theme.system': 'النظام',
    'menu.language': 'اللغة',
    'menu.language.ar': 'العربية',
    'menu.language.en': 'English',
    'menu.about': 'حول Fai$al OS',
    'menu.fullscreen': 'ملء الشاشة (يفعّل زر الويندوز)',
    'menu.exitFullscreen': 'الخروج من ملء الشاشة',
    'notif.dismiss': 'إغلاق الإشعار',
    'notif.title': 'الإشعارات',
    'notif.clear': 'مسح الكل',
    'notif.empty': 'لا توجد إشعارات',
    'notif.dnd': 'عدم الإزعاج',
    'update.title': 'تحديث جديد لـ Fai$al OS',
    'update.body': 'أغلق كل تبويبات النظام ثم افتحه من جديد لتفعيل التحديث.',
    'update.reload': 'تم تحديث النظام أثناء فتحه. أعد تحميل الصفحة لفتح هذا التطبيق.',
    'menu.screenshot': 'لقطة شاشة (Win+Shift+S)',
    'menu.clipboard': 'الحافظة (Ctrl+Alt+V)',
    'clip.title': 'الحافظة',
    'clip.clear': 'مسح الكل',
    'clip.empty': 'ما نسخت شيئاً بعد. أي نص تنسخه في النظام يظهر هنا.',
    'clip.hint': 'اختر عنصراً لتلصقه حيث كنت تكتب. الأسهم للتنقل، Delete للحذف، Esc للإغلاق.',
    'clip.remove': 'حذف من الحافظة',
    'clip.close': 'إغلاق',
    'drop.saved': 'حُفظ في {place}',
    'drop.failed': 'تعذّر حفظ {count} من الملفات',
    'drop.quota': 'المساحة المتاحة لا تكفي (الحد {file} للملف و{total} للكل).',
    'drop.copy': 'نسخة',
    'drop.into': 'أفلِت في {name}',
    'drop.here': 'هنا',
    'drop.desktop': 'سطح المكتب',
    'drop.downloads': 'التنزيلات',
    'dnd.askTitle': 'نسخة أو نقل؟',
    'dnd.askBody': '«{name}» — نسخة تُبقي الأصل، أو نقل ينقله إلى هنا.',
    'dnd.move': 'نقل',
    'dnd.cancel': 'إلغاء',
    'dnd.countFiles': '{count} عناصر',
    'dnd.copied': 'نُسخ إلى {place}',
    'dnd.moved': 'انتقل إلى {place}',
    'dnd.refused': 'ما تمّت العملية',
    'dnd.refusedSelf': 'ما ينفع تنقل العنصر إلى نفسه.',
    'dnd.refusedSubtree': 'ما ينفع تنقل مجلداً إلى داخل نفسه.',
    'dnd.refusedSameParent': 'العنصر أصلاً في هذا المكان.',
    'dnd.refusedNameTaken': 'فيه عنصر بنفس الاسم في المكان المقصود.',
    'dnd.refusedNotDirectory': 'المكان المقصود مو مجلد.',
    'dnd.refusedMissing': 'المكان المقصود ما هو موجود.',
    'dnd.refusedUnknown': 'تعذّرت العملية.',
    'clip.copied': 'نُسخ إلى الحافظة',
    'clip.copiedBody': 'الصقه بـ Ctrl+V حيث تريد.',
    'shot.hint': 'اسحب لتحديد منطقة',
    'shot.full': 'الشاشة كاملة',
    'shot.cancel': 'إلغاء',
    'shot.saved': 'تم حفظ لقطة الشاشة في الصور',
    'shot.failed': 'تعذّر حفظ لقطة الشاشة',

    // Context menus
    'ctx.open': 'فتح',
    'ctx.newWindow': 'نافذة جديدة',
    'ctx.addToDesktop': 'إضافة إلى سطح المكتب',
    'ctx.removeFromDesktop': 'إزالة من سطح المكتب',
    'ctx.addToDash': 'تثبيت في اللوحة',
    'ctx.removeFromDash': 'إزالة من اللوحة',
    'ctx.appDetails': 'تفاصيل التطبيق',
    'ctx.uninstall': 'إزالة التثبيت',

    'ctx.openFiles': 'فتح الملفات',
    'ctx.openInFiles': 'فتح في الملفات',
    'ctx.delete': 'حذف',
    'ctx.openTerminal': 'فتح الطرفية',
    'ctx.newFolder': 'مجلد جديد',
    'ctx.changeBackground': 'تغيير الخلفية…',
    'ctx.display': 'العرض',
    'ctx.displayDark': 'التبديل إلى الوضع الداكن',
    'ctx.displayLight': 'التبديل إلى الوضع الفاتح',
    'ctx.arrangeIcons': 'ترتيب الأيقونات',
    'ctx.about': 'حول Fai$al OS',

    'ctx.minimize': 'تصغير',
    'ctx.maximizeWindow': 'تكبير',
    'ctx.restoreWindow': 'استعادة',
    'ctx.alwaysOnTop': 'البقاء في الأعلى دائماً',
    'ctx.closeWindow': 'إغلاق',

    'uninstall.title': 'إزالة تثبيت {name}؟',
    'uninstall.body': 'سيتم إغلاق كل نوافذ {name} وإزالته من الجهاز. يمكنك تثبيته من جديد لاحقاً من المتجر.',
    'uninstall.confirm': 'إزالة التثبيت',
    'uninstall.cancel': 'إلغاء',
    'uninstall.done': 'تمت إزالة تثبيت {name}',

    'desktop.newFolder': 'مجلد جديد',

    // Desktop entries (files and folders living in ~/Desktop)
    'fileDelete.title': 'حذف {name}؟',
    'fileDelete.fileBody': 'سيُحذف الملف نهائيًا من نظام الملفات.',
    'fileDelete.folderBody': 'سيُحذف المجلد وكل ما فيه نهائيًا من نظام الملفات.',
    'fileDelete.failed': 'تعذّر حذف {name}',

    // Session lock (opt-in privacy curtain)
    'lock.title': 'شاشة القفل',
    'lock.subtitle': 'أدخل كلمة المرور لفتح جلستك',
    'lock.password': 'كلمة المرور',
    'lock.confirm': 'تأكيد كلمة المرور',
    'lock.hint': 'تلميح (اختياري)',
    'lock.unlock': 'فتح',
    'lock.save': 'تعيين',
    'lock.remove': 'إزالة القفل',
    'lock.now': 'قفل الجلسة',
    'lock.change': 'كلمة مرور القفل…',
    'lock.setTitle': 'تعيين كلمة مرور القفل',
    'lock.setSubtitle': 'اختر كلمة مرور خاصة بك، ويمكنك تغييرها أو إزالتها لاحقًا.',
    'lock.manageTitle': 'إدارة كلمة مرور القفل',
    'lock.manageSubtitle': 'أدخل كلمة المرور الحالية للمتابعة.',
    'lock.current': 'كلمة المرور الحالية',
    'lock.continue': 'متابعة',
    'lock.changeTitle': 'تغيير كلمة مرور القفل',
    'lock.errShort': 'قصيرة جدًا — ٤ أحرف على الأقل',
    'lock.errMismatch': 'كلمتا المرور غير متطابقتين',
    'lock.errWrong': 'كلمة المرور غير صحيحة',
    'lock.errUnsupported': 'هذا المتصفح لا يوفّر WebCrypto',
    'lock.warnWeak': 'تم التعيين — أقل من ٨ أحرف، والأفضل أطول',
    'lock.hintShown': 'تلميحك',
    'lock.forgot': 'نسيت كلمة المرور؟ لا يوجد باب خلفي: أدوات المطوّر ← Application ← Local Storage ← احذف المفتاح faisal.lock.record (أو امسح بيانات الموقع، وستفقد معها ملفات النظام).',
    'lock.scope': 'هذا حاجز خصوصية داخل الصفحة، لا تشفيرًا للجهاز: من يملك ملف تعريف المتصفح يستطيع تجاوزه. الحماية الحقيقية هي قفل نظام التشغيل.',
  },
  en: {
    activities: 'Activities',
    'win.minimize': 'Minimize',
    'win.maximize': 'Maximize / Restore',
    'win.close': 'Close',
    'search.placeholder': 'Type to search apps…',
    'overview.empty': 'No results',
    'overview.openWindows': 'Open Windows',
    'overview.webApps': 'Web Apps',
    'menu.appearance': 'Appearance',
    'menu.theme.light': 'Light',
    'menu.theme.dark': 'Dark',
    'menu.theme.system': 'System',
    'menu.language': 'Language',
    'menu.language.ar': 'العربية',
    'menu.language.en': 'English',
    'menu.about': 'About Fai$al OS',
    'menu.fullscreen': 'Full screen (enables the Windows key)',
    'menu.exitFullscreen': 'Exit full screen',
    'notif.dismiss': 'Dismiss notification',
    'notif.title': 'Notifications',
    'notif.clear': 'Clear all',
    'notif.empty': 'No notifications',
    'notif.dnd': 'Do not disturb',
    'update.title': 'Fai$al OS update ready',
    'update.body': 'Close every Fai$al OS tab and open it again to use the new version.',
    'update.reload': 'The system was updated while it was open. Reload the page to open this app.',
    'menu.screenshot': 'Screenshot (Win+Shift+S)',
    'menu.clipboard': 'Clipboard (Ctrl+Alt+V)',
    'clip.title': 'Clipboard',
    'clip.clear': 'Clear all',
    'clip.empty': 'Nothing copied yet. Any text you copy in the OS shows up here.',
    'clip.hint': 'Pick an item to paste it where you were typing. Arrows to move, Delete to remove, Esc to close.',
    'clip.remove': 'Remove from clipboard',
    'clip.close': 'Close',
    'drop.saved': 'Saved to {place}',
    'drop.failed': 'Could not save {count} file(s)',
    'drop.quota': 'Not enough space (limit {file} per file, {total} in total).',
    'drop.copy': 'copy',
    'drop.into': 'Drop into {name}',
    'drop.here': 'here',
    'drop.desktop': 'Desktop',
    'drop.downloads': 'Downloads',
    'dnd.askTitle': 'Copy or move?',
    'dnd.askBody': '“{name}” — copy keeps the original, move puts it here.',
    'dnd.move': 'Move',
    'dnd.cancel': 'Cancel',
    'dnd.countFiles': '{count} items',
    'dnd.copied': 'Copied to {place}',
    'dnd.moved': 'Moved to {place}',
    'dnd.refused': 'Nothing changed',
    'dnd.refusedSelf': 'An item cannot be moved into itself.',
    'dnd.refusedSubtree': 'A folder cannot be moved into itself.',
    'dnd.refusedSameParent': 'The item is already in that place.',
    'dnd.refusedNameTaken': 'A file with that name is already there.',
    'dnd.refusedNotDirectory': 'That place is not a folder.',
    'dnd.refusedMissing': 'That place does not exist.',
    'dnd.refusedUnknown': 'The operation could not be done.',
    'clip.copied': 'Copied to the clipboard',
    'clip.copiedBody': 'Paste it with Ctrl+V wherever you like.',
    'shot.hint': 'Drag to select an area',
    'shot.full': 'Full screen',
    'shot.cancel': 'Cancel',
    'shot.saved': 'Screenshot saved to Pictures',
    'shot.failed': 'Could not save the screenshot',

    // Context menus
    'ctx.open': 'Open',
    'ctx.newWindow': 'New window',
    'ctx.addToDesktop': 'Add to desktop',
    'ctx.removeFromDesktop': 'Remove from desktop',
    'ctx.addToDash': 'Add to dash',
    'ctx.removeFromDash': 'Remove from dash',
    'ctx.appDetails': 'App details',
    'ctx.uninstall': 'Uninstall',

    'ctx.openFiles': 'Open Files',
    'ctx.openInFiles': 'Open in Files',
    'ctx.delete': 'Delete',
    'ctx.openTerminal': 'Open Terminal',
    'ctx.newFolder': 'New folder',
    'ctx.changeBackground': 'Change background…',
    'ctx.display': 'Display',
    'ctx.displayDark': 'Switch to dark mode',
    'ctx.displayLight': 'Switch to light mode',
    'ctx.arrangeIcons': 'Arrange icons',
    'ctx.about': 'About Fai$al OS',

    'ctx.minimize': 'Minimize',
    'ctx.maximizeWindow': 'Maximize',
    'ctx.restoreWindow': 'Restore',
    'ctx.alwaysOnTop': 'Always on top',
    'ctx.closeWindow': 'Close',

    'uninstall.title': 'Uninstall {name}?',
    'uninstall.body': 'All windows of {name} will close and it will be removed from this device. You can reinstall it later from the Store.',
    'uninstall.confirm': 'Uninstall',
    'uninstall.cancel': 'Cancel',
    'uninstall.done': '{name} was uninstalled',

    'desktop.newFolder': 'New folder',

    // Desktop entries (files and folders living in ~/Desktop)
    'fileDelete.title': 'Delete {name}?',
    'fileDelete.fileBody': 'This file will be permanently removed from the file system.',
    'fileDelete.folderBody': 'This folder and everything inside it will be permanently removed from the file system.',
    'fileDelete.failed': 'Could not delete {name}',

    // Session lock (opt-in privacy curtain)
    'lock.title': 'Lock screen',
    'lock.subtitle': 'Enter your password to unlock this session',
    'lock.password': 'Password',
    'lock.confirm': 'Confirm password',
    'lock.hint': 'Hint (optional)',
    'lock.unlock': 'Unlock',
    'lock.save': 'Set password',
    'lock.remove': 'Remove lock',
    'lock.now': 'Lock session',
    'lock.change': 'Lock password…',
    'lock.setTitle': 'Set a lock password',
    'lock.setSubtitle': 'Pick your own password; you can change or remove it later.',
    'lock.manageTitle': 'Manage the lock password',
    'lock.manageSubtitle': 'Enter the current password to continue.',
    'lock.current': 'Current password',
    'lock.continue': 'Continue',
    'lock.changeTitle': 'Change the lock password',
    'lock.errShort': 'Too short — 4 characters minimum',
    'lock.errMismatch': 'The two passwords do not match',
    'lock.errWrong': 'Wrong password',
    'lock.errUnsupported': 'This browser has no WebCrypto',
    'lock.warnWeak': 'Set — under 8 characters; longer is better',
    'lock.hintShown': 'Your hint',
    'lock.forgot': 'Forgot the password? There is no back door: DevTools → Application → Local Storage → delete the key faisal.lock.record (or clear site data, which also deletes the OS files).',
    'lock.scope': 'This is a privacy curtain inside the page, not device encryption: whoever owns the browser profile can bypass it. Real protection is the operating system login.',
  },
});

/*
 * «حفظ باسم / تصدير» — نصوص المكوّن الموحّد (`save-as.ts`).
 *
 * A SECOND registration at the end of the file, deliberately: `defineStrings` merges into the
 * namespace, so this block can be added, edited or rebased on its own without touching a single
 * line of the table above — which matters because another workstream edits it in parallel.
 * Rules kept here: Arabic first, every key in both languages, identical `{placeholders}`.
 */
defineStrings('shell', {
  ar: {
    'saveas.title': 'حفظ باسم',
    'saveas.close': 'إغلاق',
    'saveas.path': 'المجلد',
    'saveas.up': 'المجلد الأعلى',
    'saveas.home': 'الرئيسية',
    'saveas.folders': 'المجلدات',
    'saveas.emptyFolder': 'ما فيه مجلدات فرعية هنا. تقدر تنشئ واحداً من الأسفل.',
    'saveas.newFolder': 'مجلد جديد',
    'saveas.newFolderHint': 'اسم المجلد الجديد',
    'saveas.create': 'إنشاء',
    'saveas.name': 'اسم الملف',
    'saveas.format': 'الصيغة',
    'saveas.keepBoth': 'حفظ باسم آخر',
    'saveas.replaceNote': 'يوجد ملف باسم {name} — عند الحفظ نسألك، وتبقى نسخة واحدة باسم {bak}.',
    'saveas.cancel': 'إلغاء',
    'saveas.download': 'تنزيل لجهازي',
    'saveas.save': 'حفظ',
    'saveas.working': 'جاري التحضير…',
    'saveas.untitled': 'بدون عنوان',
    'saveas.badFolder': 'تعذّر قراءة هذا المجلد. اختر مجلداً ثانياً.',
    'saveas.outOfHome': 'الحفظ داخل مجلد المستخدم فقط.',
    'saveas.nameRequired': 'اكتب اسم الملف.',
    'saveas.folderExists': 'يوجد مجلد باسم {name} أصلاً.',
    'saveas.folderFailed': 'تعذّر إنشاء المجلد. جرّب اسماً ثانياً.',
    'saveas.folderCreated': 'أُنشئ المجلد {name}.',
    'saveas.reserved': 'ما ينفع نهاية الاسم تكون .bak — هذا اسم النسخة الاحتياطية.',
    'saveas.writeFailed': 'تعذّر الحفظ: {reason}',
    'saveas.emptyBytes': 'ما فيه محتوى للحفظ.',
    'saveas.replaceTitle': 'استبدال {name}؟',
    'saveas.replaceBody': 'سيُستبدل الملف الموجود في مكانه، وتبقى نسخة احتياطية واحدة باسم {bak}.',
    'saveas.replaceOk': 'استبدال',
    'saveas.changed': 'الملف صار موجوداً أثناء الحفظ، فما كتبنا عليه. راجع الاسم.',
    'saveas.verifyFailed': 'كُتب الملف لكن القراءة بعد الحفظ ما طابقت، فما نعرض «تم الحفظ». جرّب مرة ثانية.',
    'saveas.downloadFailed': 'تعذّر التنزيل: {reason}',
    'saveas.quota': 'المساحة المتاحة لا تكفي لحفظ هذا الملف.',
  },
  en: {
    'saveas.title': 'Save as',
    'saveas.close': 'Close',
    'saveas.path': 'Folder',
    'saveas.up': 'Parent folder',
    'saveas.home': 'Home',
    'saveas.folders': 'Folders',
    'saveas.emptyFolder': 'No subfolders here. You can create one below.',
    'saveas.newFolder': 'New folder',
    'saveas.newFolderHint': 'New folder name',
    'saveas.create': 'Create',
    'saveas.name': 'File name',
    'saveas.format': 'Format',
    'saveas.keepBoth': 'Save under another name',
    'saveas.replaceNote': '{name} already exists — you will be asked before it is replaced, and one backup is kept as {bak}.',
    'saveas.cancel': 'Cancel',
    'saveas.download': 'Download to my device',
    'saveas.save': 'Save',
    'saveas.working': 'Preparing…',
    'saveas.untitled': 'Untitled',
    'saveas.badFolder': 'This folder could not be read. Pick another one.',
    'saveas.outOfHome': 'Saving is only allowed inside your home folder.',
    'saveas.nameRequired': 'Type a file name.',
    'saveas.folderExists': 'A folder named {name} is already here.',
    'saveas.folderFailed': 'The folder could not be created. Try another name.',
    'saveas.folderCreated': 'Created the folder {name}.',
    'saveas.reserved': 'A name cannot end in .bak — that is the backup file.',
    'saveas.writeFailed': 'Could not save: {reason}',
    'saveas.emptyBytes': 'There is nothing to save.',
    'saveas.replaceTitle': 'Replace {name}?',
    'saveas.replaceBody': 'The existing file is replaced in place, and exactly one backup is kept as {bak}.',
    'saveas.replaceOk': 'Replace',
    'saveas.changed': 'The file appeared while saving, so nothing was overwritten. Check the name.',
    'saveas.verifyFailed': 'The file was written but reading it back did not match, so "Saved" is not shown. Please try again.',
    'saveas.downloadFailed': 'Could not download: {reason}',
    'saveas.quota': 'There is not enough space to save this file.',
  },
});

/*
 * «الجولة التعريفية» — نصوص مكوّن الصدفة الموحّد (`tour.ts`).
 *
 * A THIRD registration at the end of the file, for the same reason as the block above:
 * `defineStrings` merges into the namespace, so this one can be added, edited or rebased on its
 * own without touching a line of what came before it — which matters because another workstream
 * edits this table in parallel. Arabic first, every key in both languages, identical `{n}` /
 * `{total}` placeholders. The step text itself is NOT here: it belongs to each app's own
 * `strings.ts`, next to the controls it talks about.
 */
defineStrings('shell', {
  ar: {
    'tour.skip': 'تخطي',
    'tour.next': 'التالي',
    'tour.back': 'السابق',
    'tour.done': 'تم',
    'tour.close': 'إغلاق الجولة',
    'tour.replay': 'إعادة الجولة التعريفية',
    'tour.step': 'الخطوة {n} من {total}',
  },
  en: {
    'tour.skip': 'Skip',
    'tour.next': 'Next',
    'tour.back': 'Back',
    'tour.done': 'Done',
    'tour.close': 'Close the tour',
    'tour.replay': 'Replay the tour',
    'tour.step': 'Step {n} of {total}',
  },
});
