/**
 * Fai$al OS — the in-OS Search app's network layer, kept pure and injectable.
 *
 * Two halves, both unit-tested with no network at all:
 *  1. `mapWikipediaPages` / `mapGoogleItems` turn one provider's real JSON into
 *     the app's own `SearchResult` list. They are total: a missing field, a
 *     wrong type or a malformed entry is dropped, never invented or guessed.
 *  2. `searchProvider` is the only thing that calls the network. It validates the
 *     credential set, asserts the request host, then maps. Every distinct outcome
 *     is a distinct `SearchErrorCode` so the window can say exactly what happened
 *     instead of a vague "error".
 *
 * NOTHING here ranks, re-orders, expands or summarises a result. The provider's
 * own order and its own snippet text are what the user sees, and the app says
 * which provider produced them.
 *
 * CSP NOTE (important, and measured): the OS page declares
 * `connect-src 'self' blob: https://api.groq.com https://api.deepseek.com`, so a
 * request to any other host — including both providers below — is refused by the
 * page's own Content-Security-Policy before it leaves the browser. That is
 * reported honestly as `network` (the window tells the user the search could not
 * be reached and to try again), and the two hosts are listed for the owner in
 * docs. There is no proxy and no bypass: widening `connect-src` is a security
 * decision for the OS owner, not something this app may do for itself.
 */
import type { Locale } from '../../kernel/types';
import {
  assertProviderHost,
  isProviderReady,
  missingFields,
  redactUrl,
  type ProviderConfig,
  type SearchProvider,
} from './searchProviders';

/** One result, in the app's own provider-independent shape. */
export interface SearchResult {
  title: string;
  /** The provider's own snippet, reduced to plain text. Never generated by us. */
  snippet: string;
  /** The canonical page for a human — what "open externally" opens. */
  pageUrl: string;
  /**
   * The URL an embedded web app window should load. Wikipedia articles are the
   * only pages here that allow framing, so a Google result (whose site refuses
   * framing) has `embedUrl === pageUrl` and the window's own measured
   * `blocked-domain` rule then offers the honest fallback card.
   */
  embedUrl: string;
}

/** Every way a search can end without results. Each one gets its own sentence. */
export type SearchErrorCode =
  /** The provider needs a key/engine id the user has not given yet. */
  | 'config'
  /** The request never completed: offline, or refused by the page's CSP. */
  | 'network'
  /** The provider answered with a non-2xx status. */
  | 'http'
  /** The provider answered 2xx but not with the shape this app understands. */
  | 'shape';

export interface SearchFailure {
  ok: false;
  code: SearchErrorCode;
  /** HTTP status when `code === 'http'`. */
  status?: number;
  /** Missing credential storage keys when `code === 'config'`. */
  missing?: string[];
  /** The request host that failed, or the refused host. Never a credential. */
  host?: string;
  /** Redacted request URL, for the owner looking at devtools — never a key. */
  url?: string;
}

export interface SearchSuccess {
  ok: true;
  results: SearchResult[];
  /** The provider is echoed back so the window labels the list honestly. */
  provider: SearchProvider;
}

export type SearchOutcome = SearchSuccess | SearchFailure;

/* ───────────────────────────── plain-text extraction ───────────────────────────── */

/** The few named entities the providers' snippets actually use. */
const NAMED_ENTITIES: Readonly<Record<string, string>> = {
  amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ',
  ndash: '–', mdash: '—', hellip: '…', laquo: '«', raquo: '»',
  lsquo: '\u2018', rsquo: '\u2019', ldquo: '\u201c', rdquo: '\u201d',
};

/**
 * Pure: HTML/entity → plain text, with no DOM and no `innerHTML` anywhere.
 *
 * Wikipedia's `excerpt` and Google's `snippet` both arrive with markup in them
 * (Wikipedia wraps the matched words in `<span class="searchmatch">`; Google
 * returns `&quot;`-style entities and sometimes `<b>`). Rather than interpret
 * that markup — which would mean assigning third-party HTML to the page — the
 * tags are dropped and the remaining entities are decoded, so the text is shown
 * as the provider wrote it, just without the highlighting.
 */
export function toPlainText(input: string): string {
  // 1. Drop tags, replacing each with a space so words never run together.
  let text = input.replace(/<[^>]*>/g, ' ');
  // 2. Decode numeric entities (&#8211; / &#x2013;).
  text = text.replace(/&#(x?)([0-9a-f]+);/gi, (whole, hex: string, digits: string) => {
    const code = Number.parseInt(digits, hex ? 16 : 10);
    return Number.isFinite(code) && code > 0 && code <= 0x10ffff ? String.fromCodePoint(code) : whole;
  });
  // 3. Decode the named entities above; anything unknown is left as written.
  text = text.replace(/&([a-z]+);/gi, (whole, name: string) => NAMED_ENTITIES[name.toLowerCase()] ?? whole);
  // 4. Collapse the whitespace the tag removal left behind.
  return text.replace(/\s+/g, ' ').trim();
}

/* ───────────────────────────── safe JSON navigation ───────────────────────────── */

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function prop(value: unknown, key: string): unknown {
  return isRecord(value) ? value[key] : undefined;
}

function asString(value: unknown): string {
  return typeof value === 'string' ? value : '';
}

function asArray(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

/* ───────────────────────────── Wikipedia mapping ───────────────────────────── */

/** The subdomain a Wikipedia article URL should use for the current locale. */
export function wikipediaSubdomain(locale: Locale): 'ar' | 'en' {
  return locale === 'ar' ? 'ar' : 'en';
}

/**
 * Wikipedia article URL for a search hit. The REST search endpoint answers with
 * a `key` (its title with spaces as underscores, e.g. `Faisal_I` or
 * `Wikipedia:Featured_pictures`) — never a full URL — so the canonical
 * `/wiki/<title>` URL is built here, in the article's own language subdomain.
 * The segments matter: a `key` may legitimately contain a slash, and each part
 * has to be encoded separately or the path breaks.
 */
export function wikipediaArticleUrl(subdomain: 'ar' | 'en', key: string): string {
  const path = key
    .split('/')
    .filter((segment) => segment.length > 0)
    .map((segment) => encodeURIComponent(segment))
    .join('/');
  // An empty key would produce a bare "/wiki/", which is not an article: refuse it
  // rather than offering a link that leads nowhere.
  return path ? `https://${subdomain}.wikipedia.org/wiki/${path}` : '';
}

/**
 * Pure: the Wikipedia REST search payload → results, in the provider's own order.
 *
 * Measured shape (2026-09-23, GET api.wikimedia.org/core/v1/wikipedia/en/search/page):
 *   { "pages": [ { "id": 521681, "key": "Faisal", "title": "Faisal",
 *                  "description": "Topics referred to by the same term",
 *                  "excerpt": "…<span class=\"searchmatch\">Faisal</span>…" } ] }
 * An entry with no `key` cannot be turned into an article and is dropped.
 */
export function mapWikipediaPages(payload: unknown, subdomain: 'ar' | 'en'): SearchResult[] {
  const results: SearchResult[] = [];
  for (const raw of asArray(prop(payload, 'pages'))) {
    const key = asString(prop(raw, 'key'));
    const pageUrl = wikipediaArticleUrl(subdomain, key);
    if (!pageUrl) continue;
    const title = asString(prop(raw, 'title')) || key.replace(/_/g, ' ');
    // `description` is a short disambiguator; `excerpt` is the matched text. Both
    // are the provider's words, joined with the app's own separator.
    const description = toPlainText(asString(prop(raw, 'description')));
    const excerpt = toPlainText(asString(prop(raw, 'excerpt')));
    const snippet = [description, excerpt].filter(Boolean).join(' — ');
    results.push({ title, snippet, pageUrl, embedUrl: pageUrl });
  }
  return results;
}

/* ─────────────────────────────── Google mapping ─────────────────────────────── */

/**
 * Pure: the Programmable Search JSON payload → results, in Google's own order.
 *
 * Documented shape (requested with `fields=items(title,snippet,link)`):
 *   { "items": [ { "title": "…", "snippet": "…", "link": "https://…" } ] }
 * `items` is absent entirely when there are no matches — that is an empty list,
 * not an error. An entry without an https link is dropped: the window only ever
 * offers links it can actually open, and an embedded window must never be handed
 * a non-https URL (see isAllowedFrameUrl in the browser's URL policy).
 */
export function mapGoogleItems(payload: unknown): SearchResult[] {
  const results: SearchResult[] = [];
  for (const raw of asArray(prop(payload, 'items'))) {
    const link = asString(prop(raw, 'link'));
    if (!link.startsWith('https://')) continue;
    const title = toPlainText(asString(prop(raw, 'title'))) || link;
    results.push({
      title,
      snippet: toPlainText(asString(prop(raw, 'snippet'))),
      pageUrl: link,
      embedUrl: link,
    });
  }
  return results;
}

/* ─────────────────────────────── the one network call ─────────────────────────────── */

/** What `searchProvider` needs from the environment; a test passes its own stub. */
export interface SearchDeps {
  /** Defaults to the real `fetch`. A test injects one; it is never called in tests. */
  fetchImpl?: typeof fetch;
  locale: Locale;
}

/** True when a value is usable as a `fetch` implementation. */
function hasFetch(value: unknown): value is typeof fetch {
  return typeof value === 'function';
}

/** Builds the failure for a provider whose credentials are incomplete. */
function configFailure(config: ProviderConfig): SearchFailure {
  return {
    ok: false,
    code: 'config',
    missing: missingFields(config),
    host: config.provider.host,
  };
}

/**
 * Pure: the failure code for an HTTP status and a payload check, or null when the
 * call succeeded. Kept separate so the mapping is testable without a request.
 *
 * A 2xx whose body is not the shape this provider documents is `shape`, not "no
 * results": an unauthenticated or rate-limited endpoint (Google answers 403 for a
 * bad key, and an HTML error page for some misconfigurations) must never look
 * like a legitimate empty search.
 */
export function classifyStatus(status: number, payloadOk: boolean): SearchErrorCode | null {
  if (status < 200 || status >= 300) return 'http';
  return payloadOk ? null : 'shape';
}

/**
 * Pure: does this payload carry the field the provider's mapper is going to read?
 *
 * Checking for the actual key — rather than "is it an object" — is what catches a
 * genuinely unexpected answer. An array is an object in JavaScript, so a bare
 * object check would have accepted `[1,2,3]` or an HTML-ish JSON error and then
 * silently reported zero results, which is the one thing this app must never do.
 * `items` is optional on purpose: Google omits it entirely when there are no
 * matches, and an absent list means an empty list.
 */
export function payloadHasExpectedShape(provider: SearchProvider, payload: unknown): boolean {
  if (!isRecord(payload)) return false;
  if (provider.id === 'google') {
    return payload.items === undefined || Array.isArray(payload.items);
  }
  return Array.isArray(payload.pages);
}

/**
 * Runs one search against one provider.
 *
 * The order is deliberate: credentials first (so a missing key is never reported
 * as a network fault), then the host assertion (so a query can never be sent
 * anywhere but the provider's own host), then the request, then the map.
 */
export async function searchProvider(
  config: ProviderConfig,
  query: string,
  deps: SearchDeps,
): Promise<SearchOutcome> {
  const provider = config.provider;
  const trimmed = query.trim();
  if (!trimmed) return { ok: true, results: [], provider };
  if (!isProviderReady(config)) return configFailure(config);

  let url: string;
  try {
    url = provider.apiUrl(trimmed, config, deps.locale);
    assertProviderHost(provider, url);
  } catch {
    // A provider that cannot produce its own host's URL must not be called at all.
    return { ok: false, code: 'config', host: provider.host };
  }

  const fetchImpl = deps.fetchImpl ?? (typeof fetch === 'function' ? fetch : undefined);
  if (!hasFetch(fetchImpl)) return { ok: false, code: 'network', host: provider.host, url: redactUrl(url) };

  let response: Response;
  try {
    // Credentials only ever ride in the provider's own URL (Google's design); no
    // cookie is ever attached to a cross-origin call we make on the user's behalf.
    response = await fetchImpl(url, { credentials: 'omit', referrerPolicy: 'no-referrer' });
  } catch {
    // Offline, DNS failure, or the page's CSP refusing the host. All three are
    // "we could not reach it" from the user's point of view, and all three are
    // recoverable by trying again — so they share one honest code.
    return { ok: false, code: 'network', host: provider.host, url: redactUrl(url) };
  }

  let payload: unknown;
  try {
    payload = await response.json();
  } catch {
    payload = undefined;
  }

  const code = classifyStatus(response.status, payloadHasExpectedShape(provider, payload));
  if (code) {
    return {
      ok: false,
      code,
      status: response.status,
      host: provider.host,
      url: redactUrl(url),
    };
  }

  const results = provider.id === 'google'
    ? mapGoogleItems(payload)
    : mapWikipediaPages(payload, wikipediaSubdomain(deps.locale));
  return { ok: true, results, provider };
}
