import { defineStrings } from '../../kernel/i18n';

/** Every user-visible string of the Web App window, in both languages. */
defineStrings('web', {
  ar: {
    // toolbar
    back: 'رجوع',
    forward: 'تقدّم',
    reload: 'إعادة التحميل',
    go: 'انتقال',
    addressPlaceholder: 'اكتب عنواناً أو كلمة بحث…',
    openExternal: 'فتح في المتصفح',
    openExternalHint: 'افتح هذا الموقع في تبويب حقيقي',

    // states
    loading: 'جارٍ التحميل…',
    loadingSite: 'جارٍ تحميل {site}…',
    embedWarningBody: 'قد لا يظهر هذا الموقع هنا: السجلات تقول إنه يمنع العرض داخل إطار. إن ظهرت المساحة فارغة، افتحه في المتصفح.',
    blockedTitle: 'لا يمكن عرض هذا الموقع داخل نافذة',
    blockedBody: 'هذا الموقع يطلب من المتصفح عدم عرضه داخل إطار (X-Frame-Options أو سياسة CSP)، وهذا حقّه. لا يحاول Fai$al OS تجاوز ذلك ولا تمرير المحتوى عبر وسيط — تبقى طريقة العرض الوحيدة فتح الموقع نفسه.',
    tryAnyway: 'المحاولة على أي حال',
    timedOutTitle: 'لم يظهر الموقع',
    timedOutBody: 'مرّ وقت طويل دون أن يكتمل تحميل الصفحة. إما أنها بطيئة، أو أنها ترفض العرض داخل إطار. يمكنك إعادة المحاولة أو فتح الموقع في تبويب حقيقي.',
    retry: 'إعادة المحاولة',
    searchNotice: 'بحث في ويكيبيديا عن «{query}» — وهي المحرّك الوحيد الذي يسمح بالعرض داخل إطار.',
    rewrittenNotice: 'تم تحويل الرابط إلى صيغة /embed/ لأن الأصلية ترفض العرض المضمّن.',
    unusableInputTitle: 'لا يوجد ما يمكن فتحه هنا',
    unusableInputBody: 'تطبيق «{site}» لا يعرف هذا العنوان. الصق رابط فيديو كاملاً أو معرّف الفيديو وحده، أو استخدم زر «فتح في المتصفح».',
    backToHome: 'العودة إلى البداية',

    // local proxy (opt-in) — الوسيط المحلي الاختياري
    proxyAction: 'العرض عبر الوسيط المحلي',
    proxyHint: 'الوسيط المحلي يعمل على جهازك أنت، ولا يمرّ عبر أي طرف ثالث. يُشغَّل يدوياً: node tools/local-proxy.mjs',
    proxyTokenTitle: 'رمز الوسيط',
    proxyTokenLabel: 'ألصق الرمز الذي طبعه الوسيط عند التشغيل',
    proxyTokenPlaceholder: 'الرمز (32 خانة)',
    proxyTokenSubmit: 'تحقّق واعرض',
    proxyTokenCancel: 'إلغاء',
    proxyTokenNeeded: 'هذا الوسيط يطلب رمزاً. الصقه هنا؛ لا يُسجَّل ولا يُرسل إلا إلى وسيطك المحلي.',
    proxyTokenRejected: 'الرمز غير صحيح. لم يُحفظ أي شيء. راجع السطر الذي طبعه الوسيط.',
    proxyTokenUnreachable: 'لم يستجب الوسيط المحلي. تأكد أنه ما زال يعمل على 127.0.0.1:{port}.',
    proxyModeTitle: 'كيف تعرض الصفحة؟',
    proxyModeReader: 'قراءة',
    proxyModeReaderHint: 'نص الصفحة فقط، يُعرض داخل النظام. لا تُشغَّل سكربتات الموقع.',
    proxyModeRaw: 'تضمين خام',
    proxyModeRawHint: 'الصفحة كما هي داخل إطار.',
    proxyBadgeReader: 'الوسيط المحلي — قراءة',
    proxyBadgeRaw: 'متصفح عبر الوسيط المحلي — وضع الصفحة كما هي',
    proxyStop: 'إيقاف الوسيط',
    proxyRawWarning: 'تحذير: هذا أفضل ما يمكن. المواقع المعتمدة على JavaScript بكثافة ستبدو مكسورة أو فارغة، لأن الوسيط لا يصلح شيئاً — فقط يزيل ترويسة الرفض.',
    proxyRawLoading: 'جارٍ تجهيز الإطار عبر الوسيط…',
    proxyRawTicketUnauthorized: 'الوسيط رفض الرمز: الرمز غير صحيح أو مفقود. لم يُنشأ أي إطار. راجع السطر الذي طبعه الوسيط عند التشغيل.',
    proxyRawTicketUnreachable: 'الوسيط المحلي لا يستجيب. تأكد أنه ما زال يعمل على 127.0.0.1:{port}، ثم أعد المحاولة.',
    proxyRawTicketRefused: 'الوسيط رفض هذا العنوان رفضاً صريحاً: عنوان محلي أو خاص، أو بروتوكول غير مدعوم. لم يُنشأ أي إطار.',
    proxyRawTicketMalformed: 'أجاب الوسيط المحلي بإجابة غير صالحة، فلم يُنشأ أي إطار. أعد تشغيل الوسيط ثم حاول مرة أخرى.',
    proxyOpenOriginal: 'فتح الصفحة الأصلية',
    proxyReaderLoading: 'جارٍ القراءة عبر الوسيط…',
    proxyReaderEmpty: 'لم يُعثر على نص في هذه الصفحة. جرّب «تضمين خام» أو افتح الأصل.',
    proxyReaderError: 'تعذّر جلب الصفحة عبر الوسيط. تحقّق من أن الوسيط ما زال يعمل، ثم أعد المحاولة.',
    proxyBlockedTarget: 'الوسيط يرفض هذا العنوان: عنوان محلي أو خاص أو بروتوكول غير مدعوم. لم يُرسل أي طلب.',
    proxyTitle: 'وسيط محلي',
    // the owner's cloud proxy (reader only) — الوسيط السحابي الخاص
    proxyActionCloud: 'القراءة عبر وسيطك السحابي',
    proxyHintCloud: 'وسيطك السحابي الخاص على Cloudflare: يجلب نص الصفحة ويعرضه داخل النظام بوضع القراءة. يعمل برمزك السري فقط.',
    proxyTokenLabelCloud: 'ألصق الرمز السري الذي وضعته في Cloudflare (FAISAL_PROXY_TOKEN)',
    proxyTokenPlaceholderCloud: 'الرمز السري',
    proxyTokenNeededCloud: 'هذا وسيطك السحابي ويطلب رمزك السري. يُحفظ في هذا المتصفح فقط ولا يُرسل إلا إلى وسيطك.',
    proxyTokenRejectedCloud: 'الرمز غير صحيح. لم يُحفظ أي شيء. راجع قيمة FAISAL_PROXY_TOKEN في إعدادات Cloudflare.',
    proxyBadgeReaderCloud: 'الوسيط السحابي — قراءة',
    proxyReaderErrorCloud: 'تعذّر جلب الصفحة عبر الوسيط السحابي. قد يكون الموقع رفض الطلب؛ أعد المحاولة أو افتح الأصل.',
    proxyReaderEmptyCloud: 'لم يُعثر على نص في هذه الصفحة (غالباً تطبيق JavaScript). افتح الأصل.',
    proxyTitleCloud: 'وسيط سحابي',

    // ── in-OS search app (src/apps/web/searchApp.ts) ──
    placeholder: 'ابحث…',
    providerLabel: 'مزوّد البحث',
    idle: 'اكتب كلمة ثم اضغط «ابحث». المزوّد الحالي: {provider}.',
    emptyQuery: 'اكتب كلمة للبحث أولاً.',
    searching: 'جارٍ البحث في {provider}…',
    noResults: 'لا نتائج لـ «{query}». هذه إجابة المزوّد نفسه، ولم نضف أي نتيجة من عندنا.',
    openInside: 'افتح داخل النظام',
    openResultExternal: 'فتح في المتصفح',
    noInsideApp: 'لا يوجد تطبيق مضمَّن لهذا الموقع ({host})، فهو ممنوع من العرض داخل إطار. استخدم «فتح في المتصفح».',
    openFailed: 'تعذّر فتح النافذة المضمَّنة.',
    sourceWikipedia: 'النتائج من واجهة ويكيبيديا الرسمية',
    sourceGoogle: 'النتائج من واجهة جوجل الرسمية للبحث المخصّص',

    // search provider setup
    setupOpen: 'إعداد مزوّد البحث',
    setupTitle: 'إعداد {provider}',
    setupKeyless: 'لا يحتاج هذا المزوّد إلى أي مفتاح: يتصل مباشرة بـ {host} بلا حساب ولا تسجيل.',
    setupWikipedia: 'يبحث هذا المزوّد في ويكيبيديا عبر واجهتها البرمجية العامة على {host}. لا يحتاج مفتاحاً ولا حساباً، ولا يُرسل عنك غير كلمة البحث.',
    setupGoogle: 'يبحث هذا المزوّد عبر «واجهة جوجل للبحث المخصّص» على {host}. تحتاج إلى مفتاح API خاص بك ومعرّف محرك البحث (cx) من لوحة تحكم جوجل. يبقى المفتاح في هذا الجهاز داخل localStorage ولا يُعرض ولا يُسجَّل ولا يظهر في أي رابط.',
    googleApiKey: 'مفتاح واجهة جوجل (API key)',
    googleApiKeyHint: 'من Google Cloud Console بعد تمكين Custom Search API.',
    googleCx: 'معرّف محرك البحث (cx)',
    googleCxHint: 'من programmablesearchengine.google.com — يحدّد أي مواقع تُبحث.',
    setupSave: 'حفظ',
    errorConfig: 'هذا المزوّد يحتاج إعداداً قبل البحث.',
    errorNetwork: 'لم نتمكّن من الوصول إلى {host}. إما أن الشبكة متوقّفة، أو أن سياسة أمان النظام (CSP) لا تسمح لهذا التطبيق بالاتصال بهذا المضيف. لا وسيط ولا تجاوز: يمكنك إعادة المحاولة أو فتح الموقع في المتصفح.',
    errorHttp: 'أجاب {host} برفض الطلب (رمز {status}). تحقّق من الإعداد ثم أعد المحاولة.',
    errorShape: 'أجاب {host} بصيغة لم نفهمها. لم نخمّن ولم نعرض نتائج غير حقيقية.',

    // refusals
    'refused.not-embeddable': 'لا يمكن عرض هذا العنوان: يجب أن يبدأ بـ https:// وأن يكون موقعاً خارجياً، وليس نسخة أخرى من النظام نفسه.',
    'refused.blocked-domain': 'هذا الموقع معروف برفض العرض داخل إطار، فلا نحاول فتحه هنا. استخدم زر «فتح في المتصفح».',
    'refused.unsafe-scheme': 'هذا ليس عنوان ويب. البروتوكولات مثل javascript: و data: و file: لا تُفتح ولا تُعرض هنا إطلاقاً.',
    'refused.empty': 'اكتب عنواناً أو كلمة بحث أولاً.',

    // window titles
    windowTitle: 'تطبيق ويب',
  },
  en: {
    // toolbar
    back: 'Back',
    forward: 'Forward',
    reload: 'Reload',
    go: 'Go',
    addressPlaceholder: 'Type an address or a search…',
    openExternal: 'Open externally',
    openExternalHint: 'Open this site in a real tab',

    // states
    loading: 'Loading…',
    loadingSite: 'Loading {site}…',
    embedWarningBody: 'This site may not appear here: it is recorded as refusing embedded viewing. If the area stays blank, open it in the browser.',
    blockedTitle: 'This site cannot be shown in a window',
    blockedBody: 'This site asks browsers not to display it inside a frame (X-Frame-Options or a CSP frame-ancestors rule), and that is its right. Fai$al OS does not try to bypass that and never proxies the content — the only way to view it is to open the site itself.',
    tryAnyway: 'Try embedding anyway',
    timedOutTitle: 'The site did not appear',
    timedOutBody: 'The page did not finish loading within the time allowed. It may be slow, or it may refuse embedded viewing. You can retry or open the site in a real tab.',
    retry: 'Retry',
    searchNotice: 'Searching Wikipedia for “{query}” — the only engine that permits embedded viewing.',
    rewrittenNotice: "The link was rewritten to its /embed/ form because the original refuses embedded viewing.",
    unusableInputTitle: "There is nothing to open here",
    unusableInputBody: "\u201C{site}\u201D does not recognise that address. Paste a full video link or just the video id, or use \u201COpen externally\u201D.",
    backToHome: "Back to the start",

    // local proxy (opt-in)
    proxyAction: 'Use my local proxy',
    proxyHint: 'The local proxy runs on your own machine and never goes through a third party. Start it by hand: node tools/local-proxy.mjs',
    proxyTokenTitle: 'Proxy token',
    proxyTokenLabel: 'Paste the token the proxy printed on start',
    proxyTokenPlaceholder: 'Token (32 hex characters)',
    proxyTokenSubmit: 'Verify and show',
    proxyTokenCancel: 'Cancel',
    proxyTokenNeeded: 'This proxy asks for a token. Paste it here; it is never logged and is sent only to your own local proxy.',
    proxyTokenRejected: 'Wrong token. Nothing was stored. Check the line the proxy printed when it started.',
    proxyTokenUnreachable: 'The local proxy did not answer. Make sure it is still running on 127.0.0.1:{port}.',
    proxyModeTitle: 'How should the page be shown?',
    proxyModeReader: 'Reader',
    proxyModeReaderHint: 'The page text only, rendered by the OS. The site’s scripts do not run.',
    proxyModeRaw: 'Raw embed',
    proxyModeRawHint: 'The page as-is inside a frame.',
    proxyBadgeReader: 'Local proxy — reader',
    proxyBadgeRaw: 'Browsing through the local proxy — the page as it is',
    proxyStop: 'Stop the proxy',
    proxyRawWarning: 'Warning: this is best effort. Heavy JavaScript sites will look broken or empty, because the proxy fixes nothing — it only removes the refusal header.',
    proxyRawLoading: 'Preparing the frame through the proxy…',
    proxyRawTicketUnauthorized: 'The proxy refused the token: it is wrong or missing. No frame was created. Check the line the proxy printed when it started.',
    proxyRawTicketUnreachable: 'The local proxy is not answering. Make sure it is still running on 127.0.0.1:{port}, then retry.',
    proxyRawTicketRefused: 'The proxy explicitly refused this target: a local or private address, or an unsupported scheme. No frame was created.',
    proxyRawTicketMalformed: 'The local proxy answered with something unusable, so no frame was created. Restart the proxy and try again.',
    proxyOpenOriginal: 'Open the original page',
    proxyReaderLoading: 'Reading through the proxy…',
    proxyReaderEmpty: 'No text was found on this page. Try “Raw embed”, or open the original.',
    proxyReaderError: 'Could not fetch the page through the proxy. Check that it is still running, then retry.',
    proxyBlockedTarget: 'The proxy refuses this address: a local or private address, or an unsupported scheme. No request was sent.',
    proxyTitle: "Local proxy",
    // the owner's cloud proxy (reader only)
    proxyActionCloud: 'Read through my cloud proxy',
    proxyHintCloud: 'Your own proxy on Cloudflare: it fetches the page text and shows it inside the OS in reader mode. It works only with your secret token.',
    proxyTokenLabelCloud: 'Paste the secret you set in Cloudflare (FAISAL_PROXY_TOKEN)',
    proxyTokenPlaceholderCloud: 'Secret token',
    proxyTokenNeededCloud: 'This is your cloud proxy and it asks for your secret. It is kept in this browser only and sent only to your proxy.',
    proxyTokenRejectedCloud: 'Wrong token. Nothing was stored. Check FAISAL_PROXY_TOKEN in your Cloudflare settings.',
    proxyBadgeReaderCloud: 'Cloud proxy — reader',
    proxyReaderErrorCloud: 'Could not fetch the page through the cloud proxy. The site may have refused it; retry or open the original.',
    proxyReaderEmptyCloud: 'No text was found on this page (it is probably a JavaScript app). Open the original.',
    proxyTitleCloud: 'Cloud proxy',

    // in-OS search app (src/apps/web/searchApp.ts)
    placeholder: "Search…",
    providerLabel: "Search provider",
    idle: "Type a word and press Search. Current provider: {provider}.",
    emptyQuery: "Type a word to search for first.",
    searching: "Searching {provider}…",
    noResults: "No results for \u201C{query}\u201D. That is the provider's own answer; we added nothing to it.",
    openInside: "Open inside the OS",
    openResultExternal: "Open externally",
    noInsideApp: "No embedded app exists for {host}: it refuses to be framed. Use \u201COpen externally\u201D.",
    openFailed: "The embedded window could not be opened.",
    sourceWikipedia: "Results from Wikipedia's official API",
    sourceGoogle: "Results from Google's official Programmable Search API",

    // search provider setup
    setupOpen: "Set up the search provider",
    setupTitle: "Set up {provider}",
    setupKeyless: "This provider needs no key at all: it connects straight to {host}, with no account and no sign-up.",
    setupWikipedia: "This provider searches Wikipedia through its public API on {host}. It needs no key and no account, and nothing about you is sent except the words you searched for.",
    setupGoogle: "This provider searches through Google's Programmable Search JSON API on {host}. It needs your own API key and a search-engine id (cx) from the Google control panel. The key stays on this device in localStorage: it is never displayed, never logged and never put in a link.",
    googleApiKey: "Google API key",
    googleApiKeyHint: "From Google Cloud Console, after enabling the Custom Search API.",
    googleCx: "Search engine id (cx)",
    googleCxHint: "From programmablesearchengine.google.com — it decides which sites are searched.",
    setupSave: "Save",
    errorConfig: "This provider needs to be set up before it can search.",
    errorNetwork: "We could not reach {host}. Either the network is down, or the OS security policy (CSP) does not let this app connect to that host. There is no proxy and no bypass: you can retry, or open the site in the browser.",
    errorHttp: "{host} refused the request (status {status}). Check the setup, then try again.",
    errorShape: "{host} answered in a form we do not understand. We did not guess, and we showed no results that are not real.",

    // refusals
    'refused.not-embeddable': 'This address cannot be shown: it must be https:// and an external site, not another copy of the OS itself.',
    'refused.blocked-domain': 'This site is known to refuse embedded viewing, so we do not try to open it here. Use “Open externally”.',
    'refused.unsafe-scheme': 'That is not a web address. Schemes such as javascript:, data: and file: are never opened or displayed here.',
    'refused.empty': 'Type an address or a search first.',

    // window titles
    windowTitle: 'Web App',
  },
});
