import { defineStrings } from '../../kernel/i18n';

defineStrings('settings', {
  ar: {
    title: 'الإعدادات',
    'nav.appearance': 'المظهر',
    'nav.language': 'اللغة',
    'nav.about': 'حول',
    'appearance.theme': 'السمة',
    'appearance.themeDesc': 'اختر مظهر فاتح أو داكن أو اتباع إعدادات النظام.',
    'appearance.accent': 'اللون المميز',
    'appearance.accentDesc': 'يُستخدم في شريط العنوان والأزرار.',
    'theme.light': 'فاتح',
    'theme.dark': 'داكن',
    'theme.system': 'النظام',
    'language.label': 'لغة الواجهة',
    'language.desc': 'يتطلب تغيير اللغة إعادة تحميل النظام.',
    'about.version': 'الإصدار {v}',
    'about.versionLabel': 'الإصدار',
    'about.arabicName': 'الاسم العربي: {name}',
    'about.browser': 'المتصفح',
    'about.tagline': 'نظام تشغيل افتراضي أنيق يعمل داخل متصفحك.',
  },
  en: {
    title: 'Settings',
    'nav.appearance': 'Appearance',
    'nav.language': 'Language',
    'nav.about': 'About',
    'appearance.theme': 'Theme',
    'appearance.themeDesc': 'Choose a light or dark look, or follow the system.',
    'appearance.accent': 'Accent Color',
    'appearance.accentDesc': 'Used in title bars and buttons.',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System',
    'language.label': 'Interface language',
    'language.desc': 'Changing the language reloads the system.',
    'about.version': 'Version {v}',
    'about.versionLabel': 'Version',
    'about.arabicName': 'Arabic name: {name}',
    'about.browser': 'Browser',
    'about.tagline': 'A virtual desktop OS running in your browser.',
  },
});
