import { defineStrings } from '../../kernel/i18n';

defineStrings('settings', {
  ar: {
    title: 'الإعدادات',
    'nav.appearance': 'المظهر',
    'nav.language': 'اللغة',
    'nav.about': 'حول',
    'appearance.theme': 'السمة',
    'appearance.themeDesc': 'اختر مظهر فاتح أو داكن أو اتباع إعدادات النظام.',
    'appearance.accent': 'اللون المميز',
    'appearance.accentDesc': 'يُستخدم في شريط العنوان والأزرار.',
    'theme.light': 'فاتح',
    'theme.dark': 'داكن',
    'theme.system': 'النظام',
    'language.label': 'لغة الواجهة',
    'language.desc': 'يتطلب تغيير اللغة إعادة تحميل النظام.',
    'about.versionLabel': 'الإصدار',
    'about.arabicName': 'الاسم العربي: {name}',
    'about.browser': 'المتصفح',
    'about.tagline': 'نظام تشغيل افتراضي أنيق يعمل داخل متصفحك.',
    'nav.system': 'النظام',
    'system.restore': 'استعادة التطبيقات المفتوحة',
    'system.restoreDesc': 'يعيد فتح التطبيقات التي كانت مفتوحة عند آخر إغلاق، في أماكنها.',
    'system.on': 'تشغيل',
    'system.off': 'إيقاف',
    'system.storage': 'التخزين',
    'system.storageDesc': 'الملفات والإعدادات محفوظة في هذا المتصفح.',
    'system.storageUsed': '{used} مستخدم من {quota}',
    'system.storageUnknown': 'غير متاح في هذا المتصفح',
    'system.shortcuts': 'اختصارات لوحة المفاتيح',
    'system.shortcutsNote': 'اختصارات زر الويندوز تعمل في وضع ملء الشاشة فقط، لأن النظام يلتقطها قبل المتصفح.',
    'system.reset': 'إعادة ضبط النظام',
    'system.resetDesc': 'يحذف كل الملفات والإعدادات والمفاتيح المحفوظة والبيانات المخزّنة مؤقتاً، ويعيد النظام كما كان أول مرة.',
    'system.resetBtn': 'إعادة الضبط…',
    'system.resetTitle': 'إعادة ضبط Fai$al OS؟',
    'system.resetBody': 'سيتم حذف كل ملفاتك وإعداداتك ومفاتيح API المحفوظة والبيانات المخزّنة مؤقتاً في هذا المتصفح نهائياً، ثم يُعاد تحميل النظام.',
    'system.resetConfirm': 'حذف كل شيء',
    'system.cancel': 'إلغاء',
    'sc.overview': 'عرض الأنشطة',
    'sc.terminal': 'فتح الطرفية',
    'sc.close': 'إغلاق النافذة',
    'sc.maximize': 'تكبير النافذة',
    'sc.restore': 'استعادة / تصغير النافذة',
    'sc.snap': 'وضع النافذة في نصف الشاشة',
    'sc.desktop': 'إظهار سطح المكتب',
    'sc.screenshot': 'لقطة شاشة',
  },
  en: {
    title: 'Settings',
    'nav.appearance': 'Appearance',
    'nav.language': 'Language',
    'nav.about': 'About',
    'appearance.theme': 'Theme',
    'appearance.themeDesc': 'Choose a light or dark look, or follow the system.',
    'appearance.accent': 'Accent Color',
    'appearance.accentDesc': 'Used in title bars and buttons.',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System',
    'language.label': 'Interface language',
    'language.desc': 'Changing the language reloads the system.',
    'about.versionLabel': 'Version',
    'about.arabicName': 'Arabic name: {name}',
    'about.browser': 'Browser',
    'about.tagline': 'A virtual desktop OS running in your browser.',
    'nav.system': 'System',
    'system.restore': 'Reopen apps on startup',
    'system.restoreDesc': 'Reopens the apps that were open last time, where you left them.',
    'system.on': 'On',
    'system.off': 'Off',
    'system.storage': 'Storage',
    'system.storageDesc': 'Files and settings are kept in this browser.',
    'system.storageUsed': '{used} used of {quota}',
    'system.storageUnknown': 'Not available in this browser',
    'system.shortcuts': 'Keyboard shortcuts',
    'system.shortcutsNote': 'Windows-key shortcuts only work in full screen, because the OS takes them before the browser does.',
    'system.reset': 'Reset system',
    'system.resetDesc': 'Deletes all files, settings, saved keys and cached data, and starts fresh.',
    'system.resetBtn': 'Reset…',
    'system.resetTitle': 'Reset Fai$al OS?',
    'system.resetBody': 'All your files, settings, saved API keys and cached data in this browser will be permanently deleted, then the system reloads.',
    'system.resetConfirm': 'Delete everything',
    'system.cancel': 'Cancel',
    'sc.overview': 'Show Activities',
    'sc.terminal': 'Open Terminal',
    'sc.close': 'Close window',
    'sc.maximize': 'Maximize window',
    'sc.restore': 'Restore / minimize window',
    'sc.snap': 'Snap window to half the screen',
    'sc.desktop': 'Show desktop',
    'sc.screenshot': 'Screenshot',
  },
});
