import { defineStrings } from '../../kernel/i18n';

defineStrings('settings', {
  ar: {
    title: 'الإعدادات',
    'nav.appearance': 'المظهر',
    'nav.language': 'اللغة',
    'nav.keyboard': 'لوحة المفاتيح',
    'nav.privacy': 'الخصوصية',
    'nav.about': 'حول',
    'appearance.theme': 'السمة',
    'appearance.themeDesc': 'اختر مظهر فاتح أو داكن أو اتباع إعدادات النظام.',
    'appearance.accent': 'اللون المميز',
    'appearance.accentDesc': 'يُستخدم في شريط العنوان والأزرار.',
    'theme.light': 'فاتح',
    'theme.dark': 'داكن',
    'theme.system': 'النظام',
    'language.label': 'لغة الواجهة',
    'language.desc': 'يتطلب تغيير اللغة إعادة تحميل النظام.',
    'about.versionLabel': 'الإصدار',
    'about.arabicName': 'الاسم العربي: {name}',
    'about.browser': 'المتصفح',
    'about.tagline': 'نظام تشغيل افتراضي أنيق يعمل داخل متصفحك.',
    'about.taglineDesktop': 'نظام تشغيل افتراضي أنيق، يعمل كتطبيق على جهازك.',
    'about.updatesLabel': 'التحديثات',
    'about.update.check': 'التحقق من التحديثات',
    'about.update.install': 'إعادة التشغيل للتثبيت',
    'about.update.dev': 'تعمل من الكود المصدري؛ التحديث التلقائي للنسخة المثبّتة فقط.',
    'about.update.idle': 'التحقق تلقائي عند التشغيل وكل 6 ساعات.',
    'about.update.checking': 'جارٍ التحقق…',
    'about.update.latest': 'لديك أحدث إصدار.',
    'about.update.downloading': 'جارٍ تنزيل التحديث… {percent}٪',
    'about.update.ready': 'تحديث جديد جاهز للتثبيت.',
    'about.update.error': 'تعذّر التحقق من التحديثات. تأكد من الاتصال ثم أعد المحاولة.',
    'nav.system': 'النظام',
    'system.restore': 'استعادة التطبيقات المفتوحة',
    'system.restoreDesc': 'يعيد فتح التطبيقات التي كانت مفتوحة عند آخر إغلاق، في أماكنها.',
    'system.on': 'تشغيل',
    'system.off': 'إيقاف',
    'system.storage': 'التخزين',
    'system.storageDesc': 'الملفات والإعدادات محفوظة في هذا المتصفح.',
    'system.storageUsed': '{used} مستخدم من {quota}',
    'system.storageUnknown': 'غير متاح في هذا المتصفح',
    'system.shortcuts': 'اختصارات لوحة المفاتيح',
    'system.shortcutsNote': 'تعمل اختصارات زر ويندوز في وضع ملء الشاشة فقط، لأن النظام يلتقطها قبل المتصفح. أما Alt+F1 فيعمل في أي وضع. القائمة للعرض فقط.',
    'system.shortcutsMoved': 'أصبحت قائمة اختصارات لوحة المفاتيح في قسم «لوحة المفاتيح».',
    'system.reset': 'إعادة ضبط النظام',
    'system.resetDesc': 'يحذف كل الملفات والإعدادات ومفاتيح API المحفوظة لكل المزوّدين والبيانات المخزّنة مؤقتاً، ويعيد النظام كما كان أول مرة.',
    'system.resetBtn': 'إعادة الضبط…',
    'system.resetTitle': 'إعادة ضبط Fai$al OS؟',
    'system.resetBody': 'سيتم حذف كل ملفاتك وإعداداتك وسجل الإشعارات والمفضلة ومفاتيح API المحفوظة في هذا المتصفح نهائياً، ثم يُعاد تحميل النظام. لا يمكن التراجع.',
    'system.resetConfirm': 'حذف كل شيء',
    'system.cancel': 'إلغاء',
    'privacy.storedHeading': 'ما يحفظه هذا المتصفح من أجل Fai$al OS',
    'privacy.actionsHeading': 'حذف عنصر واحد',
    'privacy.count': '{n}',
    'privacy.none': 'لا شيء محفوظ',
    'privacy.settings': 'قيم الإعدادات',
    'privacy.settingsDesc': 'السمة واللغة واللون المميز وخيارات النظام، في مفتاح واحد.',
    'privacy.notifications': 'سجل الإشعارات',
    'privacy.notificationsDesc': 'الإشعارات المحفوظة، ويُحتفظ بأحدث ٥٠ إشعاراً.',
    'privacy.windows': 'أماكن النوافذ والتطبيقات المفتوحة',
    'privacy.windowsDesc': 'حجم وموضع كل تطبيق، وقائمة التطبيقات التي كانت مفتوحة.',
    'privacy.bookmarks': 'مفضلة المتصفح',
    'privacy.bookmarksDesc': 'الروابط المحفوظة في تطبيق المتصفح، ومحرك البحث المختار.',
    'privacy.webApps': 'تطبيقات الويب المضمّنة',
    'privacy.webAppsDesc': 'آخر صفحة فتحها كل موقع مضمّن، محفوظة في هذا المتصفح.',
    'privacy.webAppsRemembered': 'الصفحات المتذكّرة: {urls}',
    'privacy.aiKeyDesc': 'مفتاح API المحفوظ. لا يُعرض المفتاح نفسه هنا أبداً.',
    'privacy.aiSaved': 'مفتاح محفوظ',
    'privacy.aiNotSaved': 'لا يوجد مفتاح',
    'privacy.ai.groq': 'GroqCloud',
    'privacy.ai.deepseek': 'DeepSeek',
    'privacy.files': 'نظام الملفات',
    'privacy.filesDesc': 'ملفاتك محفوظة في قاعدة بيانات IndexedDB باسم faisal-vfs داخل هذا المتصفح، وليست على أي خادم.',
    'privacy.filesNote': 'الحجم أعلاه هو تقدير المتصفح لكل ما يحفظه هذا الموقع، ويشمل الملفات والإعدادات. لحذف ملفات بعينها استخدم تطبيق الملفات؛ ولحذف كل شيء استخدم إعادة ضبط النظام.',
    'privacy.vsResetNote': 'حذف عنصر واحد يمس مفتاح التخزين المذكور في رسالة التأكيد فقط. أما «إعادة ضبط النظام» فتحذف كل ما سبق — الإعدادات وسجل الإشعارات والمفضلة ومفاتيح API لكل المزوّدين وروابط المواقع المتذكّرة — إضافة إلى ملفاتك وذاكرة التخزين المؤقت.',
    'privacy.clearNotifications': 'حذف سجل الإشعارات',
    'privacy.clearNotificationsDesc': 'يمسح الإشعارات المحفوظة فقط.',
    'privacy.clearNotificationsBtn': 'حذف السجل',
    'privacy.clearNotificationsTitle': 'حذف سجل الإشعارات؟',
    'privacy.clearNotificationsBody': 'سيتم حذف كل الإشعارات المحفوظة نهائياً عبر المفتاح: {keys}. لا يمكن التراجع.',
    'privacy.clearNotificationsConfirm': 'حذف السجل',
    'privacy.forgetKey': 'نسيان مفتاح API',
    'privacy.forgetKeyDesc': 'يحذف المفتاح المحفوظ لهذا المزوّد وحده، ولا يمس مفتاح المزوّد الآخر.',
    'privacy.forgetKeyBtn': 'نسيان المفتاح…',
    'privacy.forgetKeyAria': 'نسيان مفتاح {provider} المحفوظ',
    'privacy.forgetKeyTitle': 'نسيان مفتاح API؟',
    'privacy.forgetKeyBody': 'سيتم حذف مفتاح {provider} المحفوظ نهائياً عبر المفتاح: {keys}. سيتوقف التطبيق عن العمل حتى تُدخل مفتاحاً جديداً. لا يمكن التراجع.',
    'privacy.forgetKeyConfirm': 'نسيان المفتاح',
    'privacy.clearBrowser': 'حذف بيانات التصفح',
    'privacy.clearBrowserDesc': 'يحذف المفضلة ومحرك البحث المتذكّر، ويعود المتصفح إلى محركه الافتراضي.',
    'privacy.clearBrowserBtn': 'حذف البيانات',
    'privacy.clearBrowserTitle': 'حذف بيانات التصفح؟',
    'privacy.clearBrowserBody': 'سيتم حذف المفضلة ومحرك البحث المتذكّر نهائياً عبر المفتاحين: {keys}. لا يمكن التراجع.',
    'privacy.clearBrowserConfirm': 'حذف البيانات',
    'privacy.clearWebUrls': 'حذف روابط المواقع المتذكّرة',
    'privacy.clearWebUrlsDesc': 'ينسى آخر صفحة لكل تطبيق ويب مضمّن، فتعود كلها إلى صفحتها الرئيسية.',
    'privacy.clearWebUrlsBtn': 'حذف الروابط',
    'privacy.clearWebUrlsTitle': 'حذف روابط المواقع المتذكّرة؟',
    'privacy.clearWebUrlsBody': 'سيتم حذف الصفحة المتذكّرة لكل تطبيق ويب مضمّن نهائياً عبر المفاتيح: {keys}. تعود التطبيقات بعدها إلى صفحاتها الرئيسية. لا يمكن التراجع.',
    'privacy.clearWebUrlsConfirm': 'حذف الروابط',
    'privacy.fullReset': 'إعادة ضبط النظام بالكامل',
    'privacy.fullResetDesc': 'لحذف كل شيء دفعة واحدة: الإعدادات وسجل الإشعارات والمفضلة ومفاتيح API لكل المزوّدين والملفات والبيانات المؤقتة.',
    'sc.overview': 'عرض الأنشطة',
    'sc.terminal': 'فتح الطرفية',
    'sc.close': 'إغلاق النافذة',
    'sc.switchWindow': 'التبديل بين النوافذ (مع Shift للعكس)',
    'sc.maximize': 'تكبير النافذة',
    'sc.restore': 'استعادة / تصغير النافذة',
    'sc.snap': 'وضع النافذة في نصف الشاشة',
    'sc.desktop': 'إظهار سطح المكتب',
    'sc.screenshot': 'لقطة شاشة',
    'sc.clipboard': 'سجل الحافظة',
  },
  en: {
    title: 'Settings',
    'nav.appearance': 'Appearance',
    'nav.language': 'Language',
    'nav.keyboard': 'Keyboard',
    'nav.privacy': 'Privacy',
    'nav.about': 'About',
    'appearance.theme': 'Theme',
    'appearance.themeDesc': 'Choose a light or dark look, or follow the system.',
    'appearance.accent': 'Accent Color',
    'appearance.accentDesc': 'Used in title bars and buttons.',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System',
    'language.label': 'Interface language',
    'language.desc': 'Changing the language reloads the system.',
    'about.versionLabel': 'Version',
    'about.arabicName': 'Arabic name: {name}',
    'about.browser': 'Browser',
    'about.tagline': 'A virtual desktop OS running in your browser.',
    'about.taglineDesktop': 'A virtual desktop OS, running as an app on your computer.',
    'about.updatesLabel': 'Updates',
    'about.update.check': 'Check for updates',
    'about.update.install': 'Restart to install',
    'about.update.dev': 'Running from source; only installed copies update themselves.',
    'about.update.idle': 'Checked automatically at start-up and every 6 hours.',
    'about.update.checking': 'Checking…',
    'about.update.latest': 'You have the latest version.',
    'about.update.downloading': 'Downloading the update… {percent}%',
    'about.update.ready': 'An update is ready to install.',
    'about.update.error': "Couldn't check for updates. Check your connection and try again.",
    'nav.system': 'System',
    'system.restore': 'Reopen apps on startup',
    'system.restoreDesc': 'Reopens the apps that were open last time, where you left them.',
    'system.on': 'On',
    'system.off': 'Off',
    'system.storage': 'Storage',
    'system.storageDesc': 'Files and settings are kept in this browser.',
    'system.storageUsed': '{used} used of {quota}',
    'system.storageUnknown': 'Not available in this browser',
    'system.shortcuts': 'Keyboard shortcuts',
    'system.shortcutsNote': 'Windows-key shortcuts only work in full screen, because the OS takes them before the browser does. Alt+F1 works either way. This list is a reference only.',
    'system.shortcutsMoved': 'The shortcut list now lives in the Keyboard section.',
    'system.reset': 'Reset system',
    'system.resetDesc': 'Deletes all files, settings, saved API keys for both providers and cached data, and starts fresh.',
    'system.resetBtn': 'Reset…',
    'system.resetTitle': 'Reset Fai$al OS?',
    'system.resetBody': 'All your files, settings, notification history, bookmarks and saved API keys in this browser will be permanently deleted, then the system reloads. This cannot be undone.',
    'system.resetConfirm': 'Delete everything',
    'system.cancel': 'Cancel',
    'privacy.storedHeading': 'What this browser stores for Fai$al OS',
    'privacy.actionsHeading': 'Delete one item',
    'privacy.count': '{n}',
    'privacy.none': 'Nothing stored',
    'privacy.settings': 'Settings values',
    'privacy.settingsDesc': 'Theme, language, accent and system options, in one key.',
    'privacy.notifications': 'Notification history',
    'privacy.notificationsDesc': 'Stored notifications; the newest 50 are kept.',
    'privacy.windows': 'Window positions and open apps',
    'privacy.windowsDesc': 'Each app’s last size and position, plus the apps that were open.',
    'privacy.bookmarks': 'Browser bookmarks',
    'privacy.bookmarksDesc': 'Links saved in the browser app, and the chosen search engine.',
    'privacy.webApps': 'Embedded web apps',
    'privacy.webAppsDesc': 'The last page each embedded site opened, remembered in this browser.',
    'privacy.webAppsRemembered': 'Remembered pages: {urls}',
    'privacy.aiKeyDesc': 'The saved API key. The key itself is never shown here.',
    'privacy.aiSaved': 'Key saved',
    'privacy.aiNotSaved': 'No key saved',
    'privacy.ai.groq': 'GroqCloud',
    'privacy.ai.deepseek': 'DeepSeek',
    'privacy.files': 'File system',
    'privacy.filesDesc': 'Your files live in an IndexedDB database named faisal-vfs inside this browser, not on any server.',
    'privacy.filesNote': 'The size above is the browser’s estimate for everything this site stores, files and settings together. To delete individual files use the Files app; to delete everything use Reset system.',
    'privacy.vsResetNote': 'Deleting one item touches only the storage key named in its confirmation message. “Reset system” deletes all of the above — settings, notification history, bookmarks, the API keys of both providers and the remembered site URLs — plus your files and cached data.',
    'privacy.clearNotifications': 'Delete notification history',
    'privacy.clearNotificationsDesc': 'Erases the stored notifications only.',
    'privacy.clearNotificationsBtn': 'Delete history',
    'privacy.clearNotificationsTitle': 'Delete notification history?',
    'privacy.clearNotificationsBody': 'All stored notifications will be permanently deleted through the key: {keys}. This cannot be undone.',
    'privacy.clearNotificationsConfirm': 'Delete history',
    'privacy.forgetKey': 'Forget API key',
    'privacy.forgetKeyDesc': 'Deletes this provider’s saved key only; the other provider is untouched.',
    'privacy.forgetKeyBtn': 'Forget key…',
    'privacy.forgetKeyAria': 'Forget the saved {provider} key',
    'privacy.forgetKeyTitle': 'Forget the API key?',
    'privacy.forgetKeyBody': 'The saved {provider} key will be permanently deleted through the key: {keys}. The app stops working until you enter a new one. This cannot be undone.',
    'privacy.forgetKeyConfirm': 'Forget key',
    'privacy.clearBrowser': 'Clear browsing data',
    'privacy.clearBrowserDesc': 'Deletes bookmarks and the remembered search engine, returning the browser to its default.',
    'privacy.clearBrowserBtn': 'Clear data',
    'privacy.clearBrowserTitle': 'Clear browsing data?',
    'privacy.clearBrowserBody': 'Bookmarks and the remembered search engine will be permanently deleted through the keys: {keys}. This cannot be undone.',
    'privacy.clearBrowserConfirm': 'Clear data',
    'privacy.clearWebUrls': 'Delete remembered site URLs',
    'privacy.clearWebUrlsDesc': 'Forgets the last page of each embedded web app, so every one of them opens on its home page again.',
    'privacy.clearWebUrlsBtn': 'Delete URLs',
    'privacy.clearWebUrlsTitle': 'Delete remembered site URLs?',
    'privacy.clearWebUrlsBody': 'The page each embedded web app remembers will be permanently deleted through the keys: {keys}. Each app opens on its home page afterwards. This cannot be undone.',
    'privacy.clearWebUrlsConfirm': 'Delete URLs',
    'privacy.fullReset': 'Reset the whole system',
    'privacy.fullResetDesc': 'To delete everything at once: settings, notification history, bookmarks, the API keys of both providers, your files and cached data.',
    'sc.overview': 'Show Activities',
    'sc.terminal': 'Open Terminal',
    'sc.close': 'Close window',
    'sc.switchWindow': 'Switch between windows (add Shift to go back)',
    'sc.maximize': 'Maximize window',
    'sc.restore': 'Restore / minimize window',
    'sc.snap': 'Snap window to half the screen',
    'sc.desktop': 'Show desktop',
    'sc.screenshot': 'Screenshot',
    'sc.clipboard': 'Clipboard history',
  },
});
