import { defineStrings } from '../../../kernel/i18n';

/**
 * Writer — the strings of the WPS-style ribbon, page layout, header/footer, the
 * context menu and the phone's reading/editing modes, in Arabic and English.
 * They join the `office` namespace (`t('office.wCut')`); the key sets are identical.
 */
defineStrings('office', {
  ar: {
    wTabLayout: 'تخطيط الصفحة',
    wTabReferences: 'مراجع',
    wGroupClipboard: 'الحافظة',
    wGroupIllustrations: 'رسومات',
    wGroupLinks: 'روابط',
    wGroupHeaderFooter: 'الرأس والتذييل',
    wGroupSymbols: 'رموز',
    wGroupPageSetup: 'إعداد الصفحة',
    wGroupToc: 'جدول المحتويات',
    wGroupShow: 'إظهار',
    wCut: 'قص',
    wCopy: 'نسخ',
    wPaste: 'لصق',
    wPasteFailed: 'تعذّر اللصق من الحافظة. استخدم Ctrl+V.',
    wSuperscript: 'مرتفع',
    wSubscript: 'منخفض',
    wClearFormat: 'مسح التنسيق',
    wIndent: 'زيادة المسافة البادئة',
    wOutdent: 'إنقاص المسافة البادئة',
    wStyleGallery: 'معرض الأنماط',
    wMoreStyles: 'كل الأنماط',
    wShape: 'شكل',
    wShapeRect: 'مستطيل',
    wShapeRounded: 'مستطيل مستدير',
    wShapeEllipse: 'شكل بيضاوي',
    wShapeArrow: 'سهم',
    wShapeLine: 'خط',
    wShapeStar: 'نجمة',
    wLink: 'رابط',
    wLinkTitle: 'إدراج رابط',
    wLinkUrl: 'العنوان (URL)',
    wLinkText: 'النص الظاهر',
    wLinkBad: 'اكتب عنواناً يبدأ بـ http:// أو https:// أو mailto:',
    wHeader: 'رأس الصفحة',
    wFooter: 'تذييل الصفحة',
    wHeaderFooterTitle: 'الرأس والتذييل',
    wHeaderText: 'نص الرأس',
    wFooterText: 'نص التذييل',
    wHfAlign: 'المحاذاة',
    wHfPageNo: 'أضف رقم الصفحة',
    wPageNumber: 'رقم الصفحة',
    wPageNumberBottom: 'أسفل الصفحة (في الوسط)',
    wPageNumberTop: 'أعلى الصفحة (في الوسط)',
    wPageNumberOfTotal: 'صفحة X من Y (أسفل)',
    wPageNumberRemove: 'إزالة أرقام الصفحات',
    wPageWord: 'صفحة',
    wOfWord: 'من',
    wSymbol: 'رمز',
    wSymbolTitle: 'إدراج رمز',
    wColumnBreak: 'فاصل عمود',
    wBreaks: 'فواصل',
    wMargins: 'الهوامش',
    wMarginsNormal: 'عادية (2.54 سم)',
    wMarginsNarrow: 'ضيقة (1.27 سم)',
    wMarginsModerate: 'متوسطة',
    wMarginsWide: 'عريضة',
    wMarginsCustom: 'هوامش مخصّصة…',
    wMarginTop: 'أعلى (سم)',
    wMarginBottom: 'أسفل (سم)',
    wMarginLeft: 'يسار (سم)',
    wMarginRight: 'يمين (سم)',
    wMarginsBad: 'الهوامش كبيرة جداً على هذه الصفحة.',
    wOrientation: 'الاتجاه',
    wPortrait: 'عمودي',
    wLandscape: 'أفقي',
    wSize: 'الحجم',
    wColumns: 'أعمدة',
    wColumnsN: '{n} أعمدة',
    wColumnsOne: 'عمود واحد',
    wColumnsTwo: 'عمودان',
    wCrossRef: 'إسناد ترافقي',
    wCrossRefEmpty: 'لا عناوين في المستند بعد. طبّق نمط «عنوان 1» على فقرة أولاً.',
    wRuler: 'المسطرة',
    wReadingMode: 'وضع القراءة',
    wEdit: 'تحرير',
    wDoneEditing: 'تم',
    wMobileFormat: 'تنسيق',
    wMobileInsert: 'إدراج',
    wMobileTools: 'أدوات التحرير',
    wReadOnlyFile: 'هذا الملف للقراءة فقط.',
    wFont: 'الخط…',
    wParagraph: 'الفقرة…',
    wFontTitle: 'الخط',
    wParagraphTitle: 'الفقرة',
    wIndentPt: 'المسافة البادئة (نقطة)',
    wTableOps: 'الجدول',
    wRowAbove: 'إدراج صف أعلى',
    wRowBelow: 'إدراج صف أسفل',
    wColBefore: 'إدراج عمود قبل',
    wColAfter: 'إدراج عمود بعد',
    wDeleteRow: 'حذف الصف',
    wDeleteCol: 'حذف العمود',
    wDeleteTable: 'حذف الجدول',
    wTableFileOnly: 'تعديل صفوف وأعمدة جدول من الملف غير متاح بعد؛ الجداول الجديدة تُعدَّل من هنا.',
    wSelectAll: 'تحديد الكل',
    wContextMenu: 'قائمة التحرير',
    wDirection: 'الاتجاه',
    wHfFieldsHint: 'اكتب {PAGE} لرقم الصفحة و{PAGES} لعدد الصفحات.',
  },
  en: {
    wTabLayout: 'Layout',
    wTabReferences: 'References',
    wGroupClipboard: 'Clipboard',
    wGroupIllustrations: 'Illustrations',
    wGroupLinks: 'Links',
    wGroupHeaderFooter: 'Header & footer',
    wGroupSymbols: 'Symbols',
    wGroupPageSetup: 'Page setup',
    wGroupToc: 'Table of contents',
    wGroupShow: 'Show',
    wCut: 'Cut',
    wCopy: 'Copy',
    wPaste: 'Paste',
    wPasteFailed: 'Could not paste from the clipboard. Use Ctrl+V.',
    wSuperscript: 'Superscript',
    wSubscript: 'Subscript',
    wClearFormat: 'Clear formatting',
    wIndent: 'Increase indent',
    wOutdent: 'Decrease indent',
    wStyleGallery: 'Style gallery',
    wMoreStyles: 'All styles',
    wShape: 'Shape',
    wShapeRect: 'Rectangle',
    wShapeRounded: 'Rounded rectangle',
    wShapeEllipse: 'Oval',
    wShapeArrow: 'Arrow',
    wShapeLine: 'Line',
    wShapeStar: 'Star',
    wLink: 'Link',
    wLinkTitle: 'Insert link',
    wLinkUrl: 'Address (URL)',
    wLinkText: 'Text to display',
    wLinkBad: 'Type an address that starts with http://, https:// or mailto:',
    wHeader: 'Header',
    wFooter: 'Footer',
    wHeaderFooterTitle: 'Header & footer',
    wHeaderText: 'Header text',
    wFooterText: 'Footer text',
    wHfAlign: 'Alignment',
    wHfPageNo: 'Add the page number',
    wPageNumber: 'Page number',
    wPageNumberBottom: 'Bottom of page (centred)',
    wPageNumberTop: 'Top of page (centred)',
    wPageNumberOfTotal: 'Page X of Y (bottom)',
    wPageNumberRemove: 'Remove page numbers',
    wPageWord: 'Page',
    wOfWord: 'of',
    wSymbol: 'Symbol',
    wSymbolTitle: 'Insert symbol',
    wColumnBreak: 'Column break',
    wBreaks: 'Breaks',
    wMargins: 'Margins',
    wMarginsNormal: 'Normal (2.54 cm)',
    wMarginsNarrow: 'Narrow (1.27 cm)',
    wMarginsModerate: 'Moderate',
    wMarginsWide: 'Wide',
    wMarginsCustom: 'Custom margins…',
    wMarginTop: 'Top (cm)',
    wMarginBottom: 'Bottom (cm)',
    wMarginLeft: 'Left (cm)',
    wMarginRight: 'Right (cm)',
    wMarginsBad: 'The margins are too large for this page.',
    wOrientation: 'Orientation',
    wPortrait: 'Portrait',
    wLandscape: 'Landscape',
    wSize: 'Size',
    wColumns: 'Columns',
    wColumnsN: '{n} columns',
    wColumnsOne: 'One column',
    wColumnsTwo: 'Two columns',
    wCrossRef: 'Cross-reference',
    wCrossRefEmpty: 'No headings in the document yet. Apply “Heading 1” to a paragraph first.',
    wRuler: 'Ruler',
    wReadingMode: 'Reading mode',
    wEdit: 'Edit',
    wDoneEditing: 'Done',
    wMobileFormat: 'Format',
    wMobileInsert: 'Insert',
    wMobileTools: 'Editing tools',
    wReadOnlyFile: 'This file is read-only.',
    wFont: 'Font…',
    wParagraph: 'Paragraph…',
    wFontTitle: 'Font',
    wParagraphTitle: 'Paragraph',
    wIndentPt: 'Indent (pt)',
    wTableOps: 'Table',
    wRowAbove: 'Insert row above',
    wRowBelow: 'Insert row below',
    wColBefore: 'Insert column before',
    wColAfter: 'Insert column after',
    wDeleteRow: 'Delete row',
    wDeleteCol: 'Delete column',
    wDeleteTable: 'Delete table',
    wTableFileOnly: 'Rows and columns of a table from the file cannot be changed yet; new tables can be edited here.',
    wSelectAll: 'Select all',
    wContextMenu: 'Editing menu',
    wDirection: 'Direction',
    wHfFieldsHint: 'Type {PAGE} for the page number and {PAGES} for the page count.',
  },
});
