import { defineStrings } from '../../kernel/i18n';

/**
 * Office — every string this window can show, in Arabic and English.
 * The two key sets are identical; a repo-wide test proves it.
 */
defineStrings('office', {
  ar: {
    title: 'المكتب',
    kindDoc: 'مستند Word',
    kindSheet: 'جدول Excel',
    kindCsv: 'قيم مفصولة',
    kindSlides: 'عرض PowerPoint',
    kindText: 'نص',
    kindOther: 'ملف',
    loading: 'جارٍ فتح الملف…',
    noFile: 'افتح ملف Word أو Excel أو PowerPoint أو CSV أو نصاً من تطبيق الملفات، وسيُحرَّر هنا.',
    outsideTitle: 'خارج مجلد المستخدم',
    outsideBody: 'هذا الملف خارج /home/user، والتطبيق لا يقرأ ولا يكتب إلا داخله.',
    tooLargeTitle: 'ملف نصي أكبر من الحد',
    tooLargeBody: 'حد عرض النص وتحريره 4 ميجابايت، وهذا الملف أكبر. لن يُفتح هنا بدل أن تتجمد النافذة.',

    readErrorTitle: 'تعذّر قراءة الملف',
    readErrorBody: 'الملف تالف، أو أن القارئ المدمج لهذه الصيغة لم يفهمه. لن يُحفظ شيء، حتى لا يتغيّر الأصل.',
    legacyTitle: 'صيغة ثنائية قديمة',
    legacyBody: 'ملفات .doc و .xls و .ppt صيغ قديمة غير مدعومة ولا يوجد قارئ لها في النظام. افتحها في برنامجها ثم احفظها بصيغة .docx أو .xlsx أو .pptx.',
    unknownTitle: 'صيغة لا يدعمها تطبيق المكتب',
    unknownBody: 'الصيغ المدعومة للتحرير: {edit}. وللقراءة فقط: {read}. أما البقية فلا تُفتح هنا.',
    binaryTitle: 'ملف نصي ليس نصاً',
    binaryBody: 'الملف يحمل امتداد .txt أو .md لكن محتواه ثنائي، فلا يُعرض ولا يُحفظ.',
    macrosTitle: 'قراءة فقط: يحتوي ماكرو',
    macrosBody: 'ملف .xlsm يحمل ماكرو، والحفظ يعيد بناء الملف من النص فيمحو الماكرو. لذلك يُعرض هنا للقراءة فقط، بلا تعديل ولا حفظ.',
    markdownNote: 'ملف .md يُعرض ويُعدَّل كنص خام؛ لا معاينة Markdown في هذا التطبيق.',
    emptyNote: 'الملف فارغ — بدأنا محتوى جديداً، وسيُكتب عند الحفظ.',

    save: 'حفظ',
    saved: 'تم الحفظ.',
    savedWithBackup: 'تم الحفظ، والنسخة السابقة في {name}.',
    saveFailed: 'تعذّر الحفظ: {message}',
    undo: 'تراجع',
    redo: 'إعادة',
    revert: 'الرجوع إلى القرص',
    revertTitle: 'الرجوع إلى نسخة القرص؟',
    revertBody: 'ستضيع كل التغييرات غير المحفوظة في «{name}» ويعود ما على القرص.',
    revertOk: 'ارجع للقرص',
    cancel: 'إلغاء',
    dirty: 'تغييرات غير محفوظة',
    clean: 'محفوظ',
    readOnlyBadge: 'قراءة فقط',
    truncatedBadge: 'مقروء جزئياً',

    addRow: 'إضافة صف',
    addColumn: 'إضافة عمود',
    deleteRow: 'حذف الصف',
    deleteColumn: 'حذف العمود',
    toolsHint: 'اختر خلية أولاً، ثم استخدم أزرار الصفوف والأعمدة.',
    paragraphLabel: 'فقرة {n}',
    slide: 'الشريحة {n}',
    emptySlide: 'لا نص في هذه الشريحة.',
    cutNote: 'الملف أطول من حد القارئ: يُقرأ أول {rows} صف و{cols} عمود فقط، وما بعدها لا يظهر ولا يُحفظ.',
    viewLimit: 'يُعرض أول {rows} صف و{cols} عمود؛ وبقية الملف محفوظ كما هو ويُحفظ مع التغييرات.',
    moreParagraphs: 'يُعرض أول {n} فقرة؛ والباقي محفوظ كما هو ويُحفظ مع التغييرات.',

    formatBar: 'تنسيق الفقرة',
    formatBold: 'عريض',
    formatItalic: 'مائل',
    formatUnderline: 'تسطير',
    formatSize: 'حجم الخط',
    formatSizeDefault: 'الحجم الافتراضي',
    formatSizeValue: '{n} نقطة',
    formatAlignRight: 'يمين',
    formatAlignCenter: 'وسط',
    formatAlignLeft: 'يسار',
    formatAlignJustify: 'ضبط',
    formatHint: 'اختر فقرة أولاً، ثم نسّقها.',
    formulaResult: 'ناتج الصيغة: {value}',

    statBar: 'إحصاءات المستند',
    statWords: 'الكلمات: {n}',
    statChars: 'الأحرف: {n}',
    statEdits: 'التعديلات: {n}',
    statEditsTitle: 'عدد خطوات التعديل المسجّلة في سجل التراجع (حتى {n}).',
    statScopeDoc: 'الإحصاءات على فقرات المستند.',
    statScopeSlides: 'الإحصاءات على فقرات كل الشرائح.',
    statScopeText: 'الإحصاءات على النص كاملاً.',
    statScopeSheet: 'الإحصاءات على الورقة النشطة فقط.',

    focusOn: 'وضع التركيز',
    focusOff: 'إنهاء التركيز',
    focusTitle: 'يخفي الأشرطة ويعرض النص وحده.',
    focusNote: 'وضع التركيز: الأشرطة مخفية، ويبقى هذا الشريط للرجوع.',

    findOpen: 'بحث واستبدال',
    findClose: 'إغلاق البحث',
    findPanel: 'بحث واستبدال',
    findQuery: 'ابحث عن',
    findReplacement: 'استبدل بـ',
    findCountAction: 'عدّ المطابقات',
    replaceOne: 'استبدال الأول',
    replaceAll: 'استبدال الكل',
    findFound: 'عدد المطابقات: {n}.',
    findNone: 'لا مطابقة.',
    findEmptyQuery: 'اكتب نصاً للبحث.',
    replaced: 'استُبدل {n} موضعاً.',
    replaceNone: 'لا شيء ليُستبدل.',
    findCaseNote: 'النص العربي يُطابق كما هو تماماً بلا تغيير حالة، والنص اللاتيني بلا اعتبار لحالة الأحرف افتراضياً.',
    findScopeDoc: 'يُبحث داخل فقرات المستند.',
    findScopeSlides: 'يُبحث داخل فقرات الشرائح.',
    findScopeSheet: 'يُبحث في الورقة النشطة، والخلايا التي تحمل صيغة تُعدَّل كصيغة.',
    findScopeText: 'يُبحث داخل النص كاملاً.',

    ioTitle: 'استيراد وتصدير (محلي)',
    ioImport: 'استيراد .txt أو .csv',
    ioImportHint: 'يُقرأ الملف من جهازك ويُكتب في مجلد المستخدم باسمه ثم يُفتح هنا. لا يُرسل شيء إلى أي خادم.',
    ioDropHint: 'أو أفلت ملف .txt / .csv على النافذة.',
    ioExportTxt: 'تنزيل .txt',
    ioExportCsv: 'تنزيل .csv',
    ioExportHtml: 'تنزيل .html',
    ioExportPdf: 'PDF عبر المتصفح',
    ioTextNote: 'ملف .txt: نص الفقرات فقط (وفي الجدول: خلايا الورقة النشطة مفصولة بعلامة جدولة)، بلا أي تنسيق.',
    ioCsvNote: 'ملف .csv: الورقة النشطة صفوفاً وخلايا بترميز UTF-8؛ وبقية الأوراق لا تدخل فيه.',
    ioHtmlNote: 'ملف .html: المستند صفحة واحدة كاملة تُفتح في أي متصفح، ونصها يبقى نصاً لا وسوماً.',
    ioPdfNote: 'ملف PDF: عبر نافذة الطباعة في المتصفح (اختر «حفظ كملف PDF») على صفحة مهيّأة للطباعة. التطبيق لا يكتب PDF بنفسه، لأن تضمين خط عربي في PDF يدوي خارج نطاقه.',
    ioExported: 'نُزّل {name}.',
    ioExportFailed: 'تعذّر تنزيل الملف: {message}',
    ioPrint: 'فُتحت نافذة الطباعة في المتصفح؛ اختر «حفظ كملف PDF».',
    ioImported: 'استُورد {name} إلى {path} وفُتح هنا.',
    ioImportUnsupported: 'الاستيراد يقبل .txt و .csv فقط، و«{name}» ليس منهما.',
    ioImportTooLarge: '«{name}» أكبر من حد النص ({limit} ميجابايت)، فلن يُقرأ.',
    ioImportBinary: '«{name}» يحمل امتداد نص ولكن محتواه ثنائي، فلا يُستورد.',
    ioImportDamaged: 'تعذّر استيراد «{name}»: الملف تالف أو غير مفهوم.',
    ioImportNone: 'لم يصل أي ملف من الإفلات؛ أفلت ملف .txt أو .csv.',
    ioImportFirst: 'يُستورد الملف الأول فقط، والبقية تُتجاهل.',
    ioImportDirtyTitle: 'استيراد ملف مع تغييرات غير محفوظة؟',
    ioImportDirtyBody: 'الاستيراد يفتح ملفاً آخر، وستضيع تغييرات «{name}» غير المحفوظة.',
    ioImportOk: 'استورد وافتح',
    ioImportFailed: 'تعذّر كتابة الملف المستورد: {message}',

    discardTitle: 'تجاهل التغييرات غير المحفوظة؟',
    discardBody: 'في «{name}» تغييرات لم تُحفظ، وستضيع إذا أُغلقت النافذة.',
    discard: 'تجاهل',
    keep: 'متابعة التحرير',

    truncatedTitle: 'الحفظ سيكتب المقروء فقط',
    truncatedBody: 'الملف أطول من حد القراءة في القارئ المدمج ({rows} صف و{cols} عمود)، وما بعده لم يُقرأ. النسخة الاحتياطية .bak ستحتوي الأصل كاملاً، لكن الملف بعد الحفظ سيحتوي المقروء فقط.',
    truncatedOk: 'احفظ على أي حال',

    rebuildTitle: 'الحفظ سيعيد بناء الملف',
    rebuildBody: 'هذا التعديل — صف أو عمود مضاف أو محذوف، أو تغيير لا يقدر عليه الحفظ الجزئي — يجعل الحفظ يعيد بناء «{name}» من النص المقروء وحده. الصور والتنسيق والترويسات وكل ما لم يقرأه القارئ لن تبقى إلا في النسخة الاحتياطية، وستختفي من الملف المحفوظ.',
    rebuildOk: 'أعد البناء واحفظ',

    limitsTitle: 'حدود صريحة',
    limitFormulas: 'المعادلات المدعومة تُحسب وتُكتب في الملف مع الصيغة نفسها؛ وما عداها يبقى كما قرأه القارئ — نصاً أو قيمة مخزّنة — ولا يُحسب أبداً.',
    limitFormulaEngine: 'المعادلات المدعومة: + - * / والأقواس ومراجع الخلايا والنطاقات (A1، A1:B5)، ودالتا SUM وAVERAGE (المتوسط) فقط. تُكتب الصيغة في <f> ويُكتب ناتجها في الورقة.',
    limitStyling: 'التنسيق المدعوم في Word: عريض، مائل، تسطير، حجم الخط، ومحاذاة الفقرة. أما الخطوط والألوان والتخطيط وأنماط الجداول فلا تُعدَّل وتبقى كما هي في الملف عند الحفظ الجزئي.',
    limitRewrite: 'الحفظ يعدّل الأجزاء المتغيّرة فقط ويحفظ البقية كما هي؛ وإذا لم يقدر على التعديل (صف أو عمود مضاف أو محذوف) أعاد بناء الملف من النص وحده وأخبرك قبل الحفظ.',
    limitImages: 'لا صور مضمّنة ولا رسوم بيانية ولا ملاحظات متحدث ولا حركات: لا تُقرأ ولا تُعدَّل، وتبقى في الملف كما هي عند الحفظ الجزئي.',
    limitLegacy: 'لا دعم لصيغ .doc و .xls و .ppt القديمة، ولا لسواها من الصيغ خارج القائمة أدناه.',
    limitTruncated: 'يُقرأ أول {rows} صف و{cols} عمود فقط؛ وما بعدها لا يظهر ولا يُحفظ.',
    limitSlideBlank: 'الفقرات الفارغة في الشرائح لا يعيدها القارئ، وقد تُفقد عند إعادة بناء الملف، لا عند الحفظ الجزئي.',
    limitBackup: 'قبل كل حفظ تُكتب نسخة واحدة بامتداد .bak بجانب الملف، وتُستبدل في كل مرة.',
    limitText: 'الأرقام تُحفظ كأرقام، وما عداها كنص؛ أنواع الخلايا الأصلية (تاريخ، عملة، منطقي) لا يحفظها القارئ فلا تعود.',

    formatsTitle: 'الصيغ المدعومة (مُتحقَّق منها من القارئ نفسه)',
    formatsEdit: 'للتحرير: {list}',
    formatsReadOnly: 'للقراءة فقط: {list}',
    formatsUnsupported: 'غير مدعومة: {list}',
  },
  en: {
    title: 'Office',
    kindDoc: 'Word document',
    kindSheet: 'Excel sheet',
    kindCsv: 'Delimited text',
    kindSlides: 'PowerPoint show',
    kindText: 'Text',
    kindOther: 'File',
    loading: 'Opening the file…',
    noFile: 'Open a Word, Excel, PowerPoint, CSV or text file from the Files app and it is edited here.',
    outsideTitle: 'Outside the user folder',
    outsideBody: 'This file is outside /home/user, and this app reads and writes only inside it.',
    tooLargeTitle: 'A text file past the limit',
    tooLargeBody: 'Showing and editing text is limited to 4 MB and this file is larger, so it is not opened here rather than freezing the window.',

    readErrorTitle: 'Could not read the file',
    readErrorBody: 'The file is damaged, or the built-in reader for this format did not understand it. Nothing will be saved, so the original cannot change.',
    legacyTitle: 'An old binary format',
    legacyBody: '.doc, .xls and .ppt are legacy formats this system has no reader for. Open them in their own program and save as .docx, .xlsx or .pptx.',
    unknownTitle: 'A format Office does not support',
    unknownBody: 'Editable formats: {edit}. Read-only: {read}. Anything else does not open here.',
    binaryTitle: 'A text file that is not text',
    binaryBody: 'The file has a .txt or .md extension but its content is binary, so it is neither shown nor saved.',
    macrosTitle: 'Read-only: it holds macros',
    macrosBody: 'A .xlsm file carries macros, and saving rebuilds the file from text alone, which would erase them. So it is shown here read-only: no editing, no saving.',
    markdownNote: 'A .md file is shown and edited as raw text; this app has no Markdown preview.',
    emptyNote: 'The file is empty — a new document was started and will be written on save.',

    save: 'Save',
    saved: 'Saved.',
    savedWithBackup: 'Saved; the previous content is in {name}.',
    saveFailed: 'Could not save: {message}',
    undo: 'Undo',
    redo: 'Redo',
    revert: 'Revert to disk',
    revertTitle: 'Revert to the file on disk?',
    revertBody: 'Every unsaved change in “{name}” will be lost and the file on disk comes back.',
    revertOk: 'Revert to disk',
    cancel: 'Cancel',
    dirty: 'Unsaved changes',
    clean: 'Saved',
    readOnlyBadge: 'Read-only',
    truncatedBadge: 'Partially read',

    addRow: 'Add row',
    addColumn: 'Add column',
    deleteRow: 'Delete row',
    deleteColumn: 'Delete column',
    toolsHint: 'Select a cell first, then use the row and column buttons.',
    paragraphLabel: 'Paragraph {n}',
    slide: 'Slide {n}',
    emptySlide: 'No text on this slide.',
    cutNote: 'The file is past the reader’s limit: only the first {rows} rows and {cols} columns are read, and the rest is neither shown nor saved.',
    viewLimit: 'Only the first {rows} rows and {cols} columns are shown; the rest of the file is kept and saved with your changes.',
    moreParagraphs: 'Only the first {n} paragraphs are shown; the rest is kept and saved with your changes.',

    formatBar: 'Paragraph formatting',
    formatBold: 'Bold',
    formatItalic: 'Italic',
    formatUnderline: 'Underline',
    formatSize: 'Font size',
    formatSizeDefault: 'Default size',
    formatSizeValue: '{n} pt',
    formatAlignRight: 'Right',
    formatAlignCenter: 'Center',
    formatAlignLeft: 'Left',
    formatAlignJustify: 'Justify',
    formatHint: 'Choose a paragraph first, then format it.',
    formulaResult: 'Formula result: {value}',

    statBar: 'Document counts',
    statWords: 'Words: {n}',
    statChars: 'Characters: {n}',
    statEdits: 'Edits: {n}',
    statEditsTitle: 'Recorded edit steps in the undo history (up to {n}).',
    statScopeDoc: 'The counts cover the document’s paragraphs.',
    statScopeSlides: 'The counts cover every slide’s paragraphs.',
    statScopeText: 'The counts cover the whole text.',
    statScopeSheet: 'The counts cover the active sheet only.',

    focusOn: 'Focus mode',
    focusOff: 'Exit focus',
    focusTitle: 'Hides the toolbars and shows the text alone.',
    focusNote: 'Focus mode: the toolbars are hidden and this bar is the way back.',

    findOpen: 'Find & replace',
    findClose: 'Close find',
    findPanel: 'Find and replace',
    findQuery: 'Find',
    findReplacement: 'Replace with',
    findCountAction: 'Count matches',
    replaceOne: 'Replace one',
    replaceAll: 'Replace all',
    findFound: 'Matches: {n}.',
    findNone: 'No matches.',
    findEmptyQuery: 'Type something to search for.',
    replaced: 'Replaced {n} occurrence(s).',
    replaceNone: 'Nothing to replace.',
    findCaseNote: 'Arabic is matched exactly as written with no case folding; Latin text ignores letter case by default.',
    findScopeDoc: 'Searches inside the document’s paragraphs.',
    findScopeSlides: 'Searches inside the slides’ paragraphs.',
    findScopeSheet: 'Searches the active sheet; a cell that holds a formula is edited as a formula.',
    findScopeText: 'Searches the whole text.',

    ioTitle: 'Import & export (local)',
    ioImport: 'Import .txt or .csv',
    ioImportHint: 'The file is read from your device, written into the user folder under its own name and opened here. Nothing is sent to any server.',
    ioDropHint: 'Or drop a .txt / .csv file on the window.',
    ioExportTxt: 'Download .txt',
    ioExportCsv: 'Download .csv',
    ioExportHtml: 'Download .html',
    ioExportPdf: 'PDF via the browser',
    ioTextNote: '.txt: the paragraphs’ text only (in a sheet: the active sheet’s cells, tab-separated), with no formatting at all.',
    ioCsvNote: '.csv: the active sheet as rows and cells in UTF-8; the other sheets are not included.',
    ioHtmlNote: '.html: the document as one complete page that opens in any browser, its text kept as text and never as markup.',
    ioPdfNote: '.pdf: through the browser’s print dialog (choose “Save as PDF”) on a print-ready page. The app does not write a PDF itself, because embedding an Arabic font in a hand-written PDF is out of scope.',
    ioExported: 'Downloaded {name}.',
    ioExportFailed: 'Could not download the file: {message}',
    ioPrint: 'The browser’s print dialog is open; choose “Save as PDF”.',
    ioImported: 'Imported {name} into {path} and opened it here.',
    ioImportUnsupported: 'Import accepts only .txt and .csv, and “{name}” is neither.',
    ioImportTooLarge: '“{name}” is larger than the {limit} MB text limit, so it is not read.',
    ioImportBinary: '“{name}” has a text extension but binary content, so it is not imported.',
    ioImportDamaged: 'Could not import “{name}”: the file is damaged or unreadable.',
    ioImportNone: 'No file arrived from the drop. Drop a .txt or .csv file.',
    ioImportFirst: 'Only the first file is imported; the rest are ignored.',
    ioImportDirtyTitle: 'Import a file while there are unsaved changes?',
    ioImportDirtyBody: 'Importing opens another file, and the unsaved changes in “{name}” will be lost.',
    ioImportOk: 'Import and open',
    ioImportFailed: 'Could not write the imported file: {message}',

    discardTitle: 'Discard unsaved changes?',
    discardBody: '“{name}” has changes that were not saved and will be lost when the window closes.',
    discard: 'Discard',
    keep: 'Keep editing',

    truncatedTitle: 'Saving will write only what was read',
    truncatedBody: 'The file is longer than the built-in reader’s limit ({rows} rows, {cols} columns) and the rest was never read. The .bak copy will hold the whole original, but the saved file will hold only what was read.',
    truncatedOk: 'Save anyway',

    rebuildTitle: 'Saving will rebuild the file',
    rebuildBody: 'This edit — a row or a column added or removed, or a change the surgical save cannot express — makes saving rebuild “{name}” from the text that was read alone. Images, styling, headers and anything else the reader never saw will exist only in the backup and will be gone from the saved file.',
    rebuildOk: 'Rebuild and save',

    limitsTitle: 'Honest limits',
    limitFormulas: 'The supported formulas are calculated and written into the file together with the formula itself; anything else stays exactly as the reader saw it — text or the cached value — and is never calculated.',
    limitFormulaEngine: 'Supported formulas: + - * /, parentheses, cell and range references (A1, A1:B5) and only the two functions SUM and AVERAGE (المتوسط). The formula goes into <f> and its result into the sheet.',
    limitStyling: 'Word formatting supported here: bold, italic, underline, font size and paragraph alignment. Fonts, colours, layout and table styles are not edited and stay as they are in the file on a surgical save.',
    limitRewrite: 'A save rewrites only the parts that changed and keeps the rest as it is; when it cannot (a row or a column added or removed) it rebuilds the file from text alone, after telling you first.',
    limitImages: 'No embedded images, no charts, no speaker notes, no animations: they are neither read nor edited, and a surgical save leaves them in the file as they are.',
    limitLegacy: 'The legacy formats .doc, .xls and .ppt are not supported, nor is anything outside the list below.',
    limitTruncated: 'Only the first {rows} rows and {cols} columns are read; the rest is neither shown nor saved.',
    limitSlideBlank: 'Blank slide paragraphs are dropped by the reader and can be lost when a save rebuilds the file — not on a surgical save.',
    limitBackup: 'Before every save one .bak copy is written next to the file, and it is replaced each time.',
    limitText: 'Numbers are saved as numbers and everything else as text; the original cell types (date, currency, boolean) are not kept by the reader and cannot come back.',

    formatsTitle: 'Supported formats (verified against the reader itself)',
    formatsEdit: 'Editable: {list}',
    formatsReadOnly: 'Read-only: {list}',
    formatsUnsupported: 'Not supported: {list}',
  },
});
