import { defineStrings } from '../../kernel/i18n';

/**
 * Office — every string this window can show, in Arabic and English.
 * The two key sets are identical; a repo-wide test proves it.
 */
defineStrings('office', {
  ar: {
    title: 'المكتب',
    kindDoc: 'مستند Word',
    kindSheet: 'جدول Excel',
    kindCsv: 'قيم مفصولة',
    kindSlides: 'عرض PowerPoint',
    kindText: 'نص',
    kindOther: 'ملف',
    loading: 'جارٍ فتح الملف…',
    noFile: 'افتح ملف Word أو Excel أو PowerPoint أو CSV أو نصاً من تطبيق الملفات، وسيُحرَّر هنا.',
    outsideTitle: 'خارج مجلد المستخدم',
    outsideBody: 'هذا الملف خارج /home/user، والتطبيق لا يقرأ ولا يكتب إلا داخله.',
    tooLargeTitle: 'ملف نصي أكبر من الحد',
    tooLargeBody: 'حد عرض النص وتحريره 4 ميجابايت، وهذا الملف أكبر. لن يُفتح هنا بدل أن تتجمد النافذة.',

    readErrorTitle: 'تعذّر قراءة الملف',
    readErrorBody: 'الملف تالف، أو أن القارئ المدمج لهذه الصيغة لم يفهمه. لن يُحفظ شيء، حتى لا يتغيّر الأصل.',
    legacyTitle: 'صيغة ثنائية قديمة',
    legacyBody: 'ملفات .doc و .xls و .ppt صيغ قديمة غير مدعومة ولا يوجد قارئ لها في النظام. افتحها في برنامجها ثم احفظها بصيغة .docx أو .xlsx أو .pptx.',
    unknownTitle: 'صيغة لا يدعمها تطبيق المكتب',
    unknownBody: 'الصيغ المدعومة للتحرير: {edit}. وللقراءة فقط: {read}. أما البقية فلا تُفتح هنا.',
    binaryTitle: 'ملف نصي ليس نصاً',
    binaryBody: 'الملف يحمل امتداد .txt أو .md لكن محتواه ثنائي، فلا يُعرض ولا يُحفظ.',
    macrosTitle: 'قراءة فقط: يحتوي ماكرو',
    macrosBody: 'ملف .xlsm يحمل ماكرو، والحفظ يعيد بناء الملف من النص فيمحو الماكرو. لذلك يُعرض هنا للقراءة فقط، بلا تعديل ولا حفظ.',
    markdownNote: 'ملف .md يُعرض ويُعدَّل كنص خام؛ لا معاينة Markdown في هذا التطبيق.',
    emptyNote: 'الملف فارغ — بدأنا محتوى جديداً، وسيُكتب عند الحفظ.',

    save: 'حفظ',
    saved: 'تم الحفظ.',
    savedWithBackup: 'تم الحفظ، والنسخة السابقة في {name}.',
    saveFailed: 'تعذّر الحفظ: {message}',
    undo: 'تراجع',
    redo: 'إعادة',
    revert: 'الرجوع إلى القرص',
    revertTitle: 'الرجوع إلى نسخة القرص؟',
    revertBody: 'ستضيع كل التغييرات غير المحفوظة في «{name}» ويعود ما على القرص.',
    revertOk: 'ارجع للقرص',
    cancel: 'إلغاء',
    dirty: 'تغييرات غير محفوظة',
    clean: 'محفوظ',
    readOnlyBadge: 'قراءة فقط',
    truncatedBadge: 'مقروء جزئياً',

    addRow: 'إضافة صف',
    addColumn: 'إضافة عمود',
    deleteRow: 'حذف الصف',
    deleteColumn: 'حذف العمود',
    toolsHint: 'اختر خلية أولاً، ثم استخدم أزرار الصفوف والأعمدة.',
    paragraphLabel: 'فقرة {n}',
    slide: 'الشريحة {n}',
    emptySlide: 'لا نص في هذه الشريحة.',
    cutNote: 'الملف أطول من حد القارئ: يُقرأ أول {rows} صف و{cols} عمود فقط، وما بعدها لا يظهر ولا يُحفظ.',
    viewLimit: 'يُعرض أول {rows} صف و{cols} عمود؛ وبقية الملف محفوظ كما هو ويُحفظ مع التغييرات.',
    moreParagraphs: 'يُعرض أول {n} فقرة؛ والباقي محفوظ كما هو ويُحفظ مع التغييرات.',

    discardTitle: 'تجاهل التغييرات غير المحفوظة؟',
    discardBody: 'في «{name}» تغييرات لم تُحفظ، وستضيع إذا أُغلقت النافذة.',
    discard: 'تجاهل',
    keep: 'متابعة التحرير',

    truncatedTitle: 'الحفظ سيكتب المقروء فقط',
    truncatedBody: 'الملف أطول من حد القراءة في القارئ المدمج ({rows} صف و{cols} عمود)، وما بعده لم يُقرأ. النسخة الاحتياطية .bak ستحتوي الأصل كاملاً، لكن الملف بعد الحفظ سيحتوي المقروء فقط.',
    truncatedOk: 'احفظ على أي حال',

    limitsTitle: 'حدود صريحة',
    limitFormulas: 'لا محرّك صيغ: الصيغة تبقى كما قرأها القارئ — نصاً أو قيمة مخزّنة — ولا تُحسب أبداً.',
    limitStyling: 'لا تنسيق: الخطوط والألوان والتخطيط وأنماط الجداول لا تُقرأ ولا تُحفظ.',
    limitRewrite: 'الحفظ يعيد بناء الملف من النص وحده؛ كل ما لم يقرأه القارئ (الصور، الرسوم، الماكرو، التنسيق) يُفقد في الملف المحفوظ.',
    limitImages: 'لا صور مضمّنة ولا رسوم بيانية ولا ملاحظات متحدث ولا حركات.',
    limitLegacy: 'لا دعم لصيغ .doc و .xls و .ppt القديمة، ولا لسواها من الصيغ خارج القائمة أدناه.',
    limitTruncated: 'يُقرأ أول {rows} صف و{cols} عمود فقط؛ وما بعدها لا يظهر ولا يُحفظ.',
    limitSlideBlank: 'الفقرات الفارغة في الشرائح لا يعيدها القارئ، وقد تُفقد عند إعادة الحفظ.',
    limitBackup: 'قبل كل حفظ تُكتب نسخة واحدة بامتداد .bak بجانب الملف، وتُستبدل في كل مرة.',
    limitText: 'الأرقام تُحفظ كأرقام، وما عداها كنص؛ أنواع الخلايا الأصلية (تاريخ، عملة، منطقي) لا يحفظها القارئ فلا تعود.',

    formatsTitle: 'الصيغ المدعومة (مُتحقَّق منها من القارئ نفسه)',
    formatsEdit: 'للتحرير: {list}',
    formatsReadOnly: 'للقراءة فقط: {list}',
    formatsUnsupported: 'غير مدعومة: {list}',
  },
  en: {
    title: 'Office',
    kindDoc: 'Word document',
    kindSheet: 'Excel sheet',
    kindCsv: 'Delimited text',
    kindSlides: 'PowerPoint show',
    kindText: 'Text',
    kindOther: 'File',
    loading: 'Opening the file…',
    noFile: 'Open a Word, Excel, PowerPoint, CSV or text file from the Files app and it is edited here.',
    outsideTitle: 'Outside the user folder',
    outsideBody: 'This file is outside /home/user, and this app reads and writes only inside it.',
    tooLargeTitle: 'A text file past the limit',
    tooLargeBody: 'Showing and editing text is limited to 4 MB and this file is larger, so it is not opened here rather than freezing the window.',

    readErrorTitle: 'Could not read the file',
    readErrorBody: 'The file is damaged, or the built-in reader for this format did not understand it. Nothing will be saved, so the original cannot change.',
    legacyTitle: 'An old binary format',
    legacyBody: '.doc, .xls and .ppt are legacy formats this system has no reader for. Open them in their own program and save as .docx, .xlsx or .pptx.',
    unknownTitle: 'A format Office does not support',
    unknownBody: 'Editable formats: {edit}. Read-only: {read}. Anything else does not open here.',
    binaryTitle: 'A text file that is not text',
    binaryBody: 'The file has a .txt or .md extension but its content is binary, so it is neither shown nor saved.',
    macrosTitle: 'Read-only: it holds macros',
    macrosBody: 'A .xlsm file carries macros, and saving rebuilds the file from text alone, which would erase them. So it is shown here read-only: no editing, no saving.',
    markdownNote: 'A .md file is shown and edited as raw text; this app has no Markdown preview.',
    emptyNote: 'The file is empty — a new document was started and will be written on save.',

    save: 'Save',
    saved: 'Saved.',
    savedWithBackup: 'Saved; the previous content is in {name}.',
    saveFailed: 'Could not save: {message}',
    undo: 'Undo',
    redo: 'Redo',
    revert: 'Revert to disk',
    revertTitle: 'Revert to the file on disk?',
    revertBody: 'Every unsaved change in “{name}” will be lost and the file on disk comes back.',
    revertOk: 'Revert to disk',
    cancel: 'Cancel',
    dirty: 'Unsaved changes',
    clean: 'Saved',
    readOnlyBadge: 'Read-only',
    truncatedBadge: 'Partially read',

    addRow: 'Add row',
    addColumn: 'Add column',
    deleteRow: 'Delete row',
    deleteColumn: 'Delete column',
    toolsHint: 'Select a cell first, then use the row and column buttons.',
    paragraphLabel: 'Paragraph {n}',
    slide: 'Slide {n}',
    emptySlide: 'No text on this slide.',
    cutNote: 'The file is past the reader’s limit: only the first {rows} rows and {cols} columns are read, and the rest is neither shown nor saved.',
    viewLimit: 'Only the first {rows} rows and {cols} columns are shown; the rest of the file is kept and saved with your changes.',
    moreParagraphs: 'Only the first {n} paragraphs are shown; the rest is kept and saved with your changes.',

    discardTitle: 'Discard unsaved changes?',
    discardBody: '“{name}” has changes that were not saved and will be lost when the window closes.',
    discard: 'Discard',
    keep: 'Keep editing',

    truncatedTitle: 'Saving will write only what was read',
    truncatedBody: 'The file is longer than the built-in reader’s limit ({rows} rows, {cols} columns) and the rest was never read. The .bak copy will hold the whole original, but the saved file will hold only what was read.',
    truncatedOk: 'Save anyway',

    limitsTitle: 'Honest limits',
    limitFormulas: 'No formula engine: a formula stays exactly as the reader saw it — text or the cached value — and is never calculated.',
    limitStyling: 'No styling: fonts, colours, layout and table styles are neither read nor saved.',
    limitRewrite: 'Saving rebuilds the file from text alone; everything the reader never saw (images, charts, macros, styling) is lost in the saved file.',
    limitImages: 'No embedded images, no charts, no speaker notes, no animations.',
    limitLegacy: 'The legacy formats .doc, .xls and .ppt are not supported, nor is anything outside the list below.',
    limitTruncated: 'Only the first {rows} rows and {cols} columns are read; the rest is neither shown nor saved.',
    limitSlideBlank: 'Blank slide paragraphs are dropped by the reader and can be lost when the file is written back.',
    limitBackup: 'Before every save one .bak copy is written next to the file, and it is replaced each time.',
    limitText: 'Numbers are saved as numbers and everything else as text; the original cell types (date, currency, boolean) are not kept by the reader and cannot come back.',

    formatsTitle: 'Supported formats (verified against the reader itself)',
    formatsEdit: 'Editable: {list}',
    formatsReadOnly: 'Read-only: {list}',
    formatsUnsupported: 'Not supported: {list}',
  },
});
