/**
 * Impress — the WPS-style editor's strings (الشريط والتصميم ولوحة التنسيق).
 *
 * Same `impress.…` namespace as `strings.ts` (which imports this file), kept apart so the ribbon,
 * the design themes, the format pane and the phone bar keep their words next to each other.
 * Arabic and English are registered together; `parafmt.test.ts` proves the key sets stay equal.
 */
import { defineStrings } from '../../../kernel/i18n';

defineStrings('impress', {
  ar: {
    'showEnd': 'انتهى عرض الشرائح — انقر للخروج.',
    'readOnly': 'هذا الملف للقراءة فقط.',
    // tabs and groups
    'tabInsert': 'إدراج',
    'tabDesign': 'تصميم',
    'tabTransitions': 'انتقالات',
    'tabAnimations': 'حركات',
    'tabView': 'عرض',
    'groupFont': 'الخط',
    'groupParagraph': 'الفقرة',
    'groupArrange': 'ترتيب',
    'groupShapeStyle': 'نمط الشكل',
    'groupText': 'نص',
    'groupIllustrations': 'رسوم',
    'groupLinks': 'روابط',
    'groupEdit': 'تحرير',
    'groupCustomize': 'تخصيص',
    'groupPreview': 'معاينة',
    'groupApply': 'تطبيق',
    'groupStart': 'بدء العرض',
    'groupViews': 'طرق العرض',
    'groupShowPanes': 'إظهار',
    // home
    'layoutPick': 'اختر تخطيط الشريحة الجديدة',
    'font': 'الخط',
    'fontTheme': 'خط السمة',
    'alignJustify': 'ضبط',
    'bringFront': 'إحضار إلى المقدمة',
    'bringForward': 'إحضار للأمام',
    'sendBackward': 'إرسال للخلف',
    'sendBack': 'إرسال إلى الخلفية',
    'align_left': 'محاذاة إلى يسار الشريحة',
    'align_center': 'توسيط أفقي في الشريحة',
    'align_right': 'محاذاة إلى يمين الشريحة',
    'align_top': 'محاذاة إلى أعلى الشريحة',
    'align_middle': 'توسيط عمودي في الشريحة',
    'align_bottom': 'محاذاة إلى أسفل الشريحة',
    'fill': 'تعبئة الشكل',
    'outline': 'حد الشكل',
    'noFill': 'بلا تعبئة',
    'noOutline': 'بلا حد',
    'formatPane': 'تنسيق الشكل',
    'selectShape': 'اختر شكلًا أولًا.',
    // insert
    'table': 'جدول',
    'tablePick': 'اختر عدد الصفوف والأعمدة',
    'tableSize': 'جدول {rows} × {cols}',
    'tableCell': 'الخلية: صف {row}، عمود {col}',
    'tableAdded': 'أُضيف الجدول: انقر عليه نقرًا مزدوجًا لتكتب في خلاياه.',
    'shapesBasic': 'أشكال أساسية',
    'shapesArrows': 'أسهم',
    'shapesLines': 'خطوط',
    'shapeRoundRect': 'مستطيل مستدير الزوايا',
    'shapeTriangle': 'مثلث',
    'shapeRtTriangle': 'مثلث قائم',
    'shapeDiamond': 'معيّن',
    'shapeHexagon': 'سداسي',
    'shapeStar': 'نجمة',
    'shapeRightArrow': 'سهم لليمين',
    'shapeLeftArrow': 'سهم لليسار',
    'shapeUpArrow': 'سهم للأعلى',
    'shapeDownArrow': 'سهم للأسفل',
    'link': 'رابط',
    'linkTitle': 'رابط الشكل',
    'linkHint': 'عنوان ويب أو بريد يُفتح عند النقر على الشكل أثناء العرض.',
    'linkApply': 'حفظ الرابط',
    'linkRemove': 'إزالة الرابط',
    'linkBad': 'العنوان غير صالح — اكتب عنوانًا يبدأ بـ https:// أو mailto:',
    'linkAdded': 'أُضيف الرابط: يُفتح بنقرة على الشكل أثناء العرض.',
    'linkRemoved': 'أُزيل الرابط.',
    'linkSelect': 'اختر شكلًا أولًا لتضيف له رابطًا.',
    // design
    'themes': 'السمات',
    'themeApplied': 'طُبّقت سمة «{name}» على كل الشرائح.',
    'slideSize': 'حجم الشريحة',
    'sizeWide': 'عريض 16:9',
    'sizeStandard': 'قياسي 4:3',
    'sizeCustom': 'حجم مخصص',
    'sizeChanged': 'تغيّر حجم الشريحة، وتغيّرت أماكن الأشكال وأحجامها معه.',
    // transitions and animations
    'transWipe': 'مسح',
    'transCover': 'تغطية',
    'applyAll': 'تطبيق على الكل',
    'appliedAll': 'طُبّق الانتقال على كل الشرائح.',
    'preview': 'معاينة',
    'animFly': 'طيران للداخل',
    'animSelect': 'اختر شكلًا لتضيف له حركة.',
    // view
    'viewNormal': 'عادي',
    'viewSorter': 'فارز الشرائح',
    'viewNotes': 'صفحة الملاحظات',
    'notesPane': 'ملاحظات المتحدث',
    'notesPlaceholder': 'انقر لإضافة ملاحظات المتحدث',
    'guidesToggle': 'أدلة المحاذاة',
    // the format pane
    'paneTitle': 'تنسيق الشكل',
    'paneClose': 'إغلاق لوحة التنسيق',
    'paneEmpty': 'اختر شكلًا أو مربع نص لتنسّقه هنا: التعبئة والحد والنص والحجم.',
    'paneEmptyAction': 'تصميم الشرائح',
    'paneLocked': 'هذا الكائن محفوظ بصيغة لا يعدّلها المحرّر، فيبقى كما هو في الملف.',
    'paneFill': 'التعبئة',
    'paneOutline': 'الحد',
    'paneWidth': 'السُمك',
    'paneText': 'النص',
    'paneSize': 'الحجم والموضع',
    'paneW': 'العرض',
    'paneH': 'الارتفاع',
    'paneX': 'من اليسار',
    'paneY': 'من الأعلى',
    'paneUnit': 'سم',
    'paneLink': 'الرابط',
    'paneCustomColor': 'لون مخصص',
    // the phone
    'phoneTools': 'أدوات العرض التقديمي',
    'phoneNew': 'شريحة',
    'phoneInsert': 'إدراج',
    'phoneFormat': 'تنسيق',
    'phoneDesign': 'تصميم',
    'phonePlay': 'عرض',
    'phoneMore': 'المزيد',
    // a new presentation
    'pickTitle': 'اختر تصميم العرض الجديد',
    'pickHint': 'يمكنك تغييره متى شئت من تبويب «تصميم».',
    'pickCreate': 'إنشاء العرض',
  },
  en: {
    'showEnd': 'End of slide show — click to exit.',
    'readOnly': 'This file is read-only.',
    'tabInsert': 'Insert',
    'tabDesign': 'Design',
    'tabTransitions': 'Transitions',
    'tabAnimations': 'Animations',
    'tabView': 'View',
    'groupFont': 'Font',
    'groupParagraph': 'Paragraph',
    'groupArrange': 'Arrange',
    'groupShapeStyle': 'Shape style',
    'groupText': 'Text',
    'groupIllustrations': 'Illustrations',
    'groupLinks': 'Links',
    'groupEdit': 'Edit',
    'groupCustomize': 'Customize',
    'groupPreview': 'Preview',
    'groupApply': 'Apply',
    'groupStart': 'Start slide show',
    'groupViews': 'Presentation views',
    'groupShowPanes': 'Show',
    'layoutPick': 'Choose the new slide’s layout',
    'font': 'Font',
    'fontTheme': 'Theme font',
    'alignJustify': 'Justify',
    'bringFront': 'Bring to front',
    'bringForward': 'Bring forward',
    'sendBackward': 'Send backward',
    'sendBack': 'Send to back',
    'align_left': 'Align to the slide’s left',
    'align_center': 'Centre on the slide',
    'align_right': 'Align to the slide’s right',
    'align_top': 'Align to the slide’s top',
    'align_middle': 'Middle of the slide',
    'align_bottom': 'Align to the slide’s bottom',
    'fill': 'Shape fill',
    'outline': 'Shape outline',
    'noFill': 'No fill',
    'noOutline': 'No outline',
    'formatPane': 'Format shape',
    'selectShape': 'Select a shape first.',
    'table': 'Table',
    'tablePick': 'Pick rows and columns',
    'tableSize': '{rows} × {cols} table',
    'tableCell': 'Cell: row {row}, column {col}',
    'tableAdded': 'Table added: double-click it to type in its cells.',
    'shapesBasic': 'Basic shapes',
    'shapesArrows': 'Arrows',
    'shapesLines': 'Lines',
    'shapeRoundRect': 'Rounded rectangle',
    'shapeTriangle': 'Triangle',
    'shapeRtTriangle': 'Right triangle',
    'shapeDiamond': 'Diamond',
    'shapeHexagon': 'Hexagon',
    'shapeStar': 'Star',
    'shapeRightArrow': 'Right arrow',
    'shapeLeftArrow': 'Left arrow',
    'shapeUpArrow': 'Up arrow',
    'shapeDownArrow': 'Down arrow',
    'link': 'Link',
    'linkTitle': 'Shape link',
    'linkHint': 'A web or mail address that opens when the shape is clicked during the show.',
    'linkApply': 'Save link',
    'linkRemove': 'Remove link',
    'linkBad': 'That address is not valid — use one that starts with https:// or mailto:',
    'linkAdded': 'Link added: a click on the shape opens it during the show.',
    'linkRemoved': 'Link removed.',
    'linkSelect': 'Select a shape first to give it a link.',
    'themes': 'Themes',
    'themeApplied': 'Theme “{name}” applied to every slide.',
    'slideSize': 'Slide size',
    'sizeWide': 'Widescreen 16:9',
    'sizeStandard': 'Standard 4:3',
    'sizeCustom': 'Custom size',
    'sizeChanged': 'Slide size changed; the shapes were scaled with it.',
    'transWipe': 'Wipe',
    'transCover': 'Cover',
    'applyAll': 'Apply to all',
    'appliedAll': 'Transition applied to every slide.',
    'preview': 'Preview',
    'animFly': 'Fly in',
    'animSelect': 'Select a shape to give it an effect.',
    'viewNormal': 'Normal',
    'viewSorter': 'Slide sorter',
    'viewNotes': 'Notes page',
    'notesPane': 'Speaker notes',
    'notesPlaceholder': 'Click to add speaker notes',
    'guidesToggle': 'Smart guides',
    'paneTitle': 'Format shape',
    'paneClose': 'Close the format pane',
    'paneEmpty': 'Select a shape or a text box to format it here: fill, outline, text and size.',
    'paneEmptyAction': 'Slide design',
    'paneLocked': 'This object is stored in a form the editor does not change, so it stays exactly as it is in the file.',
    'paneFill': 'Fill',
    'paneOutline': 'Outline',
    'paneWidth': 'Weight',
    'paneText': 'Text',
    'paneSize': 'Size and position',
    'paneW': 'Width',
    'paneH': 'Height',
    'paneX': 'From left',
    'paneY': 'From top',
    'paneUnit': 'cm',
    'paneLink': 'Link',
    'paneCustomColor': 'Custom colour',
    'phoneTools': 'Presentation tools',
    'phoneNew': 'Slide',
    'phoneInsert': 'Insert',
    'phoneFormat': 'Format',
    'phoneDesign': 'Design',
    'phonePlay': 'Play',
    'phoneMore': 'More',
    'pickTitle': 'Choose a design for the new presentation',
    'pickHint': 'You can change it any time from the Design tab.',
    'pickCreate': 'Create presentation',
  },
});
